// 文法（フェーズ9）の中身：修行場6〜10（小学校の復習）。書き方は items-01-05.mjs の先頭を参照。
const 小 = '小学校学習指導要領（平成29年告示）解説 外国語活動・外国語編'
const 中 = '中学校学習指導要領（平成29年告示）解説 外国語編'

export default [
  {
    id: 'g06',
    title: 'can（〜できる）',
    stage: '小学校の復習',
    sources: [
      { doc: 小, where: '第2部第2章第2節 2(1)エ（ｱ）b 否定の平叙文（I can’t play the piano.）、d 疑問文（Can you dance well?）', page: '93〜94' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）c 助動詞（小学校の can は「能力」に限る）', page: '45' },
    ],
    points: [
      { text: '「〜できる」は、動詞の前に can を置きます。can の後ろの動詞は原形（-s を付けない形）。', en: ['I can swim.', 'He can swim.'] },
      { text: '主語が he や she でも can の形は変わりません（cans とはしない）。' },
      { text: '否定は can’t（cannot）＋動詞の原形。', en: ["I can't drive."] },
      { text: '疑問文は Can を主語の前に出します。答えも can を使います。', en: ['Can you swim?', 'Yes, I can.', "No, I can't."] },
      { text: 'ここでは「能力（〜できる）」を扱います。「〜してもいい（許可）」「〜してくれる？（依頼）」の can は修行場15で扱います。' },
    ],
    examples: [
      { tatoeba: 256178, en: 'I can swim.' },
      { tatoeba: 293936, en: 'He can swim.' },
      { tatoeba: 744722, en: 'I can drive.' },
      { tatoeba: 312642, en: "She can't swim." },
      { tatoeba: 69237, en: 'Can you drive?' },
      { tatoeba: 26170, en: 'Can you speak English?' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'She can swims.', right: 'She can swim.', note: 'can の後ろは動詞の原形（swims は -s の付いた形）。', basis: { doc: 中, page: '39', find: "She can swim fast." }, dict: { lemma: 'swim', pos: 'verb', form: 'swims', tags: ['third-person', 'singular', 'present'] } },
      { kind: 'error', wrong: 'He can speaks English.', right: 'He can speak English.', note: 'can の後ろは動詞の原形。', basis: { doc: 中, page: '37', find: "She can play baseball well." }, dict: { lemma: 'speak', pos: 'verb', form: 'speaks', tags: ['third-person', 'singular', 'present'] } },
      { kind: 'meaning', wrong: "I can't speak English.", intended: '英語はあまり上手ではありません', right: "I can't speak English very well.", note: 'I can’t speak English. は「英語がまったく話せない」と聞こえる。少しは話せるなら very well を付ける。' },
    ],
    exercises: [
      { type: 'fill', ja: '私の兄は車を運転できます。', text: 'My brother ___ drive.', choices: ['can', 'cans', 'can to'], answers: ['can'] },
      { type: 'fill', ja: '彼女は中国語が話せます。', text: 'She can ___ Chinese.', choices: ['speak', 'speaks', 'speaking'], answers: ['speak'] },
      { type: 'order', ja: 'あなたはピアノが弾けますか。', tokens: ['Can', 'you', 'play', 'the', 'piano'], answers: ['Can you play the piano?'] },
      { type: 'order', ja: '私は速く走れません。', tokens: ['I', "can't", 'run', 'fast'], answers: ["I can't run fast."] },
      { type: 'rewrite', ja: 'can を使って「〜できる」の文にする。', from: 'I cook.', answers: ['I can cook.'] },
      { type: 'rewrite', ja: '疑問文に書き直す。', from: 'He can ski.', answers: ['Can he ski?'] },
      { type: 'oral', ja: '私は英語とスペイン語が話せます。', answers: ['I can speak English and Spanish.'] },
      { type: 'oral', ja: '明日来られますか。', answers: ['Can you come tomorrow?'] },
      { type: 'oral', ja: '私は運転ができません。', answers: ["I can't drive."] },
    ],
    myself: {
      task: 'can を使って、自分ができること（できないこと）を1文で言ってみましょう。仕事で役に立つことだとなおよいです。',
      samples: ['I can use Excel well.', "I can't speak Chinese."],
      checks: ['can の後ろは動詞の原形にした'],
    },
  },
  {
    id: 'g07',
    title: '命令文（〜しなさい・〜しないで・Let’s 〜）',
    stage: '小学校の復習',
    sources: [
      { doc: 小, where: '第2部第2章第2節 2(1)エ（ｱ）c 肯定，否定の命令文', page: '93〜94' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｱ）b（小学校の命令文の例文）', page: '39' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｲ）d（小学校で Let’s ... に触れている）', page: '42' },
    ],
    points: [
      { text: '「〜しなさい」は、主語を言わずに動詞の原形で始めます。', en: ['Sit down, please.', 'Turn right there.'] },
      { text: 'be動詞の命令文は Be で始めます（am・are・is ではない）。', en: ['Be quiet.'] },
      { text: '「〜しないで」は Don’t＋動詞の原形。be動詞なら Don’t be ～。', en: ["Don't run here.", "Don't be late."] },
      { text: '「〜しましょう」は Let’s＋動詞の原形。', en: ["Let's eat lunch."] },
      { text: '命令文は強く聞こえることがあります。please を付ける、相手や場面を選ぶなど、言い方に気を配りましょう。' },
    ],
    examples: [
      { tatoeba: 38571, en: 'Sit down, please.' },
      { tatoeba: 50853, en: 'Turn right there.' },
      { tatoeba: 61929, en: "Don't run here." },
      { tatoeba: 277394, en: "Don't be late." },
      { tatoeba: 277613, en: "Let's eat lunch." },
      { tatoeba: 31484, en: "Let's try again." },
    ],
    mistakes: [
      { kind: 'meaning', wrong: 'Send me the report.', intended: '（上司・取引先に）報告書を送っていただけますか', right: 'Could you send me the report?', note: '命令文は指示に聞こえる。目上の人への依頼は Could you ～? などを使う（修行場15）。' },
    ],
    exercises: [
      { type: 'fill', ja: '静かにしなさい。', text: '___ quiet.', choices: ['Be', 'Are', 'Do'], answers: ['Be'] },
      { type: 'fill', ja: '遅れないでね。', text: "___ be late.", choices: ["Don't", 'Not', 'No'], answers: ["Don't"] },
      { type: 'fill', ja: '一緒に昼ごはんを食べましょう。', text: "___ have lunch together.", choices: ["Let's", 'Lets', 'We'], answers: ["Let's"] },
      { type: 'order', ja: 'ここで写真を撮らないでください。', tokens: ['Please', "don't", 'take', 'pictures', 'here'], answers: ["Please don't take pictures here.", "Don't take pictures here please."] },
      { type: 'order', ja: '会議を始めましょう。', tokens: ["Let's", 'start', 'the', 'meeting'], answers: ["Let's start the meeting."] },
      { type: 'rewrite', ja: '「〜しないで」の命令文にする。', from: 'You run here.', answers: ["Don't run here."] },
      { type: 'rewrite', ja: 'Let’s を使って「〜しましょう」にする。', from: 'We take a break.', answers: ["Let's take a break."] },
      { type: 'oral', ja: 'ここに座ってください。', answers: ['Please sit here.', 'Sit here, please.'] },
      { type: 'oral', ja: '心配しないで。', answers: ["Don't worry."] },
      { type: 'oral', ja: '休憩しましょう。', answers: ["Let's take a break."] },
    ],
    myself: {
      task: '同僚や友人を誘う文を Let’s で1文言ってみましょう。',
      samples: ["Let's have lunch together.", "Let's start the meeting."],
      checks: ['Let’s の後ろは動詞の原形にした'],
    },
  },
  {
    id: 'g08',
    title: '代名詞（I・my・me・mine など）',
    stage: '小学校の復習',
    sources: [
      { doc: 小, where: '第2部第2章第2節 2(1)エ（ｱ）e 代名詞のうち，I，you，he，she などの基本的なもの', page: '95' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）a（a）人称や指示，疑問，数量を表すもの', page: '44' },
    ],
    points: [
      { text: '代名詞は文の中の働きで形が変わります。「〜は」（主語）、「〜の」（持ち主）、「〜を・〜に」（目的語）、「〜のもの」。' },
      { text: 'I・my・me・mine／you・your・you・yours／he・his・him・his／she・her・her・hers／it・its・it／we・our・us・ours／they・their・them・theirs。' },
      { text: '「〜の」は名詞の前に置きます（my book）。「〜のもの」は1語で名詞の代わりになります（This is mine.）。', en: ['This is my desk.', 'This is mine.'] },
      { text: '動詞や前置詞の後ろは「〜を・〜に」の形（me、him、her、us、them）。', en: ['I know him.', "Let's ask him."] },
      { text: 'its（それの）と it’s（it is）はちがいます。' },
      { text: '近くのものは this（複数は these）、離れたものは that（複数は those）。', en: ['These are my books.', 'Those are my trousers.'] },
    ],
    examples: [
      { tatoeba: 55618, en: 'This is my dictionary.' },
      { tatoeba: 55021, en: 'These are my books.' },
      { tatoeba: 2233709, en: 'This is mine.' },
      { tatoeba: 42378, en: "It isn't mine." },
      { tatoeba: 71751, en: 'I know him.' },
      { tatoeba: 68131, en: "Let's ask him." },
      { tatoeba: 2302, en: 'Whose is this?' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'Him is my brother.', right: 'He is my brother.', note: '主語（〜は）には he を使う。him は「彼を・彼に」。', basis: { doc: 中, page: '44', find: "She is cool." }, dict: { lemma: 'him', pos: 'pron', gloss: 'he as a grammatical object' } },
      { kind: 'error', wrong: 'Its my car.', right: "It's my car.", note: '「それは〜です」は it’s（it is）。its は「それの」。', basis: { doc: 中, page: '38', find: "Itʼs my idea." }, dict: { lemma: 'its', pos: 'det', gloss: 'Belonging to it.' } },
      { kind: 'error', wrong: 'These is my books.', right: 'These are my books.', note: 'these（複数）には are を使う。', basis: { doc: 中, page: '45', find: "These are the pictures that Masaki painted in the country." }, dict: { lemma: 'be', pos: 'verb', form: 'are', tags: ['plural', 'present'] } },
    ],
    exercises: [
      { type: 'fill', ja: 'これは彼女のかばんです。', text: 'This is ___ bag.', choices: ['her', 'she', 'hers'], answers: ['her'] },
      { type: 'fill', ja: 'そのペンは私のです。', text: 'The pen is ___.', choices: ['mine', 'my', 'me'], answers: ['mine'] },
      { type: 'fill', ja: '私は彼らをよく知っています。', text: 'I know ___ well.', choices: ['them', 'they', 'their'], answers: ['them'] },
      { type: 'order', ja: 'これらは私たちの机です。', tokens: ['These', 'are', 'our', 'desks'], answers: ['These are our desks.'] },
      { type: 'order', ja: '彼に聞いてみましょう。', tokens: ["Let's", 'ask', 'him'], answers: ["Let's ask him."] },
      { type: 'rewrite', ja: 'my car を1語（「私のもの」）に変えて書き直す。', from: 'This is my car.', answers: ['This is mine.'] },
      { type: 'rewrite', ja: 'Tom を代名詞に変えて書き直す。', from: 'I called Tom yesterday.', answers: ['I called him yesterday.'] },
      { type: 'oral', ja: 'これは私の名刺です。', answers: ['This is my business card.', 'This is my card.'] },
      { type: 'oral', ja: 'あのかばんは彼のです。', answers: ['That bag is his.'] },
      { type: 'oral', ja: '彼女に電話します。', answers: ["I'll call her.", 'I will call her.'] },
    ],
    myself: {
      task: '自分の持ち物か家族・同僚について、代名詞を使って1文言ってみましょう。',
      samples: ['This is my laptop.', 'My boss is kind. I like her.'],
      checks: ['「〜の」は my など、「〜を」は me・him などにした'],
    },
  },
  {
    id: 'g09',
    title: '名詞の複数形と a / an / the',
    stage: '小学校の復習',
    sources: [
      { doc: 小, where: '第2部第2章第2節 2(1)エ（ｲ）b、c の例文（a good tennis player、apples など。独立した項目としては挙がっていない）', page: '96〜97' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｲ）a の例文（an astronaut、a pianist）', page: '40' },
    ],
    points: [
      { text: '学習指導要領の文法事項には独立した項目として挙がっていませんが、例文の中で使われている基本です。' },
      { text: '数えられる名詞が2つ以上のときは複数形にします。ふつうは -s（books）。s、x、ch、sh で終わる語は -es（boxes、watches）。「子音字＋y」は y を i に変えて -es（cities）。', en: ['I have two brothers.'] },
      { text: 'man → men、woman → women、child → children のように形が変わる語もあります。' },
      { text: '数えられる名詞が1つのときは a を付けます。母音の音で始まる語の前は an。', en: ['I have a car.', 'I have an idea.'] },
      { text: '話し手と聞き手の両方が「どれのことか」わかるものには the を付けます。', en: ['The station is nearby.'] },
      { text: 'water、money、information など数えない名詞には a を付けず、複数形にもしません。量は some などで表します。', en: ['We need some money.'] },
    ],
    examples: [
      { tatoeba: 252272, en: 'I have a car.' },
      { tatoeba: 34684, en: 'I have an idea.' },
      { tatoeba: 249765, en: 'I have two brothers.' },
      { tatoeba: 253340, en: 'I have two cameras.' },
      { tatoeba: 319648, en: 'I need an envelope.' },
      { tatoeba: 247911, en: 'We need some money.' },
      { tatoeba: 26044, en: 'The station is nearby.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'I have two brother.', right: 'I have two brothers.', note: '2人以上は複数形にする。', basis: { doc: 中, page: '46', find: "There are seven days in a week." }, dict: { lemma: 'brother', pos: 'noun', form: 'brothers', tags: ['plural'] } },
      { kind: 'error', wrong: 'I want an book.', right: 'I want a book.', note: 'an は母音の音で始まる語の前だけ。', basis: { doc: 中, page: '37', find: "I want a new ball." }, dict: { lemma: 'an', pos: 'article', gloss: 'Used before a vowel sound.' } },
      { kind: 'error', wrong: 'I have a apple.', right: 'I have an apple.', note: 'apple は母音の音で始まるので an。', basis: { doc: 中, page: '43', find: "There is an old tree in front of my house." }, dict: { lemma: 'an', pos: 'article', gloss: 'Used before a vowel sound.' } },
    ],
    exercises: [
      { type: 'fill', ja: '私には子どもが3人います。', text: 'I have three ___.', choices: ['children', 'childs', 'child'], answers: ['children'] },
      { type: 'fill', ja: '私はエンジニアです。', text: "I'm ___ engineer.", choices: ['an', 'a', 'the'], answers: ['an'] },
      { type: 'fill', ja: '駅はどこですか（その町の駅）。', text: 'Where is ___ station?', choices: ['the', 'a', 'an'], answers: ['the'] },
      { type: 'order', ja: '私は封筒が1枚必要です。', tokens: ['I', 'need', 'an', 'envelope'], answers: ['I need an envelope.'] },
      { type: 'order', ja: '私たちには少しお金が必要です。', tokens: ['We', 'need', 'some', 'money'], answers: ['We need some money.'] },
      { type: 'rewrite', ja: 'a camera を two cameras に変えて書き直す。', from: 'I have a camera.', answers: ['I have two cameras.'] },
      { type: 'rewrite', ja: 'a box を three boxes に変えて書き直す。', from: 'There is a box on the desk.', answers: ['There are three boxes on the desk.'] },
      { type: 'oral', ja: '私には兄弟が2人います。', answers: ['I have two brothers.'] },
      { type: 'oral', ja: 'いい考えがあります。', answers: ['I have an idea.', 'I have a good idea.'] },
      { type: 'oral', ja: '会議室はどこですか。', answers: ['Where is the meeting room?'] },
    ],
    myself: {
      task: '自分の家族か持ち物について、数を入れて1文言ってみましょう。',
      samples: ['I have two sisters.', 'I have a laptop and two phones.'],
      checks: ['2つ以上は複数形にした', '1つのときは a / an を付けた'],
    },
  },
  {
    id: 'g10',
    title: '前置詞（時・場所・出身）',
    stage: '小学校の復習',
    sources: [
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）d 前置詞（出身、時間・期間、場所）', page: '46' },
    ],
    points: [
      { text: '前置詞は名詞の前に置いて、時・場所などを表します。' },
      { text: '時刻は at、曜日・日付は on、月・年・季節は in。', en: ['School begins at nine.', "I'm free on Sunday.", 'School begins in April.'] },
      { text: '期間（〜の間）は for。', en: ['We walked for two hours.'] },
      { text: '場所：in（〜の中に・都市や国に）、on（〜の上に・接して）、under（〜の下に）、at（〜という地点で）。', en: ["It's under the table.", 'I live in Tokyo.'] },
      { text: '出身は from。', en: ["I'm from Australia."] },
    ],
    examples: [
      { tatoeba: 21526, en: 'School begins at nine.' },
      { tatoeba: 57545, en: "I'm free on Sunday." },
      { tatoeba: 21520, en: 'School begins in April.' },
      { tatoeba: 247813, en: 'We walked for two hours.' },
      { tatoeba: 39623, en: "It's under the table." },
      { tatoeba: 279745, en: 'I live in Tokyo.' },
      { tatoeba: 253217, en: "I'm from Australia." },
    ],
    mistakes: [
      { kind: 'error', wrong: 'See you in Monday.', right: 'See you on Monday.', note: '曜日には on を使う。', basis: { doc: 中, page: '46', find: "On Tuesdays he goes to a swimming club." }, dict: { lemma: 'on', pos: 'prep', gloss: 'At or during the date or day of.' } },
      { kind: 'error', wrong: 'We met in Monday.', right: 'We met on Monday.', note: '曜日には on を使う。', basis: { doc: 中, page: '46', find: "On Tuesdays he goes to a swimming club." }, dict: { lemma: 'on', pos: 'prep', gloss: 'At or during the date or day of.' } },
      { kind: 'meaning', wrong: "I'll finish it in two hours.", intended: '2時間以内に終えます', right: "I'll finish it within two hours.", note: 'in two hours は「2時間後に」の意味でも使われる。「以内」をはっきり言うなら within。' },
    ],
    exercises: [
      { type: 'fill', ja: '会議は3時に始まります。', text: 'The meeting starts ___ three.', choices: ['at', 'on', 'in'], answers: ['at'] },
      { type: 'fill', ja: '月曜日に会いましょう。', text: "Let's meet ___ Monday.", choices: ['on', 'in', 'at'], answers: ['on'] },
      { type: 'fill', ja: '私は2020年に入社しました。', text: 'I joined the company ___ 2020.', choices: ['in', 'on', 'at'], answers: ['in'] },
      { type: 'order', ja: '私たちは3時間待ちました。', tokens: ['We', 'waited', 'for', 'three', 'hours'], answers: ['We waited for three hours.'] },
      { type: 'order', ja: 'それはテーブルの下にあります。', tokens: ["It's", 'under', 'the', 'table'], answers: ["It's under the table."] },
      { type: 'rewrite', ja: 'at seven を on Friday に変えて書き直す。', from: "I'll call you at seven.", answers: ["I'll call you on Friday."] },
      { type: 'rewrite', ja: 'in Osaka を from Osaka に変え、「大阪出身です」の文にする。', from: 'I live in Osaka.', answers: ["I'm from Osaka.", 'I am from Osaka.'] },
      { type: 'oral', ja: '私は9時に出社します。', answers: ['I get to work at nine.', 'I arrive at the office at nine.'] },
      { type: 'oral', ja: '金曜日は空いています。', answers: ["I'm free on Friday."] },
      { type: 'oral', ja: '私は東京出身です。', answers: ["I'm from Tokyo."] },
    ],
    myself: {
      task: '前置詞を使って、自分の予定か出身を1文で言ってみましょう。',
      samples: ["I'm from Hokkaido.", 'I have a meeting on Monday at ten.'],
      checks: ['時刻は at、曜日は on、月・年は in にした'],
    },
  },
]
