// 文法（フェーズ9）の中身：修行場17〜26（中学校：文の形とつなぎ方）。書き方は items-01-05.mjs の先頭を参照。
const 中 = '中学校学習指導要領（平成29年告示）解説 外国語編'

export default [
  {
    id: 'g17',
    title: 'There is / There are（〜がある・いる）',
    stage: '中学校：文の形',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｲ）e（a）There＋be動詞＋〜', page: '43' }],
    points: [
      { text: '「（ある場所に）〜がある・いる」は There is / There are＋名詞（＋場所）。', en: ['There is a cat.', 'There were three men.'] },
      { text: 'be動詞は後ろの名詞に合わせます。1つ・数えない名詞は is、2つ以上は are。過去は was / were。' },
      { text: '疑問文は Is there 〜? / Are there 〜?。「いくつありますか」は How many 〜 are there?', en: ['Is there time?'] },
      { text: 'no を使うと「1つも〜ない」。', en: ['There is no choice.'] },
      { text: 'my bag や the station のように、聞き手がどれか分かっているものの場所を言うときは、ふつう There is を使わず My bag is on the desk. のように言います。' },
    ],
    examples: [
      { tatoeba: 35821, en: 'There is a cat.' },
      { tatoeba: 72664, en: 'There were three men.' },
      { tatoeba: 370590, en: 'There are many factors.' },
      { tatoeba: 245477, en: 'There is no choice.' },
      { tatoeba: 24809, en: 'There is no hurry.' },
      { tatoeba: 2248503, en: 'Is there time?' },
    ],
    mistakes: [
      { kind: 'informal', wrong: "There's two books on the desk.", right: 'There are two books on the desk.', note: '会話では、後ろが複数でも There’s と言うことがとても多い（短い形のときだけ。There is two … とはあまり言わない）。正式な場面や書くときは There are を使う。', dict: { lemma: 'is', pos: 'verb', label: 'colloquial', gloss: 'existential there' }, spoken: { wrong: "there's two", wrongCount: 15383, right: 'there are two', rightCount: 24029 } },
      { kind: 'error', wrong: 'There are a cat under the table.', right: 'There is a cat under the table.', note: '1つなら is。', basis: { doc: 中, page: '43', find: "There is an old tree in front of my house." }, dict: { lemma: 'be', pos: 'verb', form: 'is', tags: ['third-person', 'singular', 'present'] } },
      { kind: 'meaning', wrong: 'There is my bag on the desk.', intended: '私のかばんは机の上にあります', right: 'My bag is on the desk.', note: 'There is my bag は「ほら、私のかばんがあった」のような言い方になる。分かっているものの場所は 主語＋be動詞＋場所。' },
    ],
    exercises: [
      { type: 'fill', ja: 'この階には会議室が3つあります。', text: 'There ___ three meeting rooms on this floor.', choices: ['are', 'is', 'have'], answers: ['are'] },
      { type: 'fill', ja: 'この近くに銀行はありますか。', text: '___ there a bank near here?', choices: ['Is', 'Are', 'Do'], answers: ['Is'] },
      { type: 'order', ja: 'この近くにコンビニはありますか。', tokens: ['Is', 'there', 'a', 'convenience', 'store', 'near', 'here'], answers: ['Is there a convenience store near here?'] },
      { type: 'order', ja: '会議室には椅子が10脚あります。', tokens: ['There', 'are', 'ten', 'chairs', 'in', 'the', 'meeting', 'room'], answers: ['There are ten chairs in the meeting room.', 'In the meeting room there are ten chairs.'] },
      { type: 'rewrite', ja: 'one printer を three printers に変えて書き直す。', from: 'There is one printer in the office.', answers: ['There are three printers in the office.'] },
      { type: 'rewrite', ja: '否定文に書き直す。', from: 'There is a problem.', answers: ["There isn't a problem.", 'There is not a problem.', 'There is no problem.', "There's no problem."] },
      { type: 'oral', ja: '質問はありますか。', answers: ['Are there any questions?', 'Do you have any questions?'] },
      { type: 'oral', ja: '問題が1つあります。', answers: ['There is a problem.', "There's a problem.", 'There is one problem.'] },
      { type: 'oral', ja: '駅の近くにホテルがあります。', answers: ['There is a hotel near the station.', "There's a hotel near the station."] },
    ],
    myself: {
      task: '家や職場の近くにあるものを、There is / There are で1文言ってみましょう。',
      samples: ['There is a big park near my house.', 'There are three coffee shops near my office.'],
      checks: ['後ろの名詞に合わせて is / are を選んだ'],
    },
  },
  {
    id: 'g18',
    title: '「〜になる」「〜に見える」（become・look など＋名詞・形容詞）',
    stage: '中学校：文の形',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｲ）a［主語＋動詞＋補語］のうち，主語＋be動詞以外の動詞＋名詞・形容詞', page: '40' }],
    points: [
      { text: 'become＋名詞・形容詞で「〜になる」。', en: ['She became happy.'] },
      { text: 'look＋形容詞で「〜に見える・〜そうだ」。sound（〜に聞こえる）、feel（〜に感じる）、get（〜になる）も同じ形です。', en: ['You look tired.', 'It sounds great!', 'He got angry.'] },
      { text: '後ろには形容詞を置きます（look happy。happily のような副詞にはしない）。' },
      { text: '名詞を続けて「〜のように見える・聞こえる」と言うときは look like / sound like＋名詞。', en: ['That sounds like a good idea.'] },
    ],
    examples: [
      { tatoeba: 16224, en: 'You look pale.' },
      { tatoeba: 63218, en: 'You look tired.' },
      { tatoeba: 313111, en: 'She looks happy.' },
      { tatoeba: 313588, en: 'She became happy.' },
      { tatoeba: 66736, en: 'It sounds great!' },
      { tatoeba: 507233, en: 'He got angry.' },
    ],
    mistakes: [],
    exercises: [
      { type: 'fill', ja: '彼女は昨年マネージャーになりました。', text: 'She ___ a manager last year.', choices: ['became', 'looked', 'felt'], answers: ['became'] },
      { type: 'fill', ja: '今日は疲れているようですね。', text: 'You look ___ today.', choices: ['tired', 'tiredly', 'tire'], answers: ['tired'] },
      { type: 'order', ja: '彼はうれしそうに見えます。', tokens: ['He', 'looks', 'happy'], answers: ['He looks happy.'] },
      { type: 'order', ja: 'それはいい考えのようですね。', tokens: ['That', 'sounds', 'like', 'a', 'good', 'idea'], answers: ['That sounds like a good idea.'] },
      { type: 'rewrite', ja: 'became と last year を使って「〜になった」の文にする。', from: 'He is a lawyer.', answers: ['He became a lawyer last year.', 'Last year he became a lawyer.'] },
      { type: 'rewrite', ja: 'look を使って「〜そうに見える」の文にする。', from: 'You are busy.', answers: ['You look busy.'] },
      { type: 'oral', ja: '疲れているようですね。', answers: ['You look tired.'] },
      { type: 'oral', ja: 'いいですね（それはよさそうですね）。', answers: ['That sounds good.', 'Sounds good.', 'That sounds great.'] },
      { type: 'oral', ja: '彼は昨年、部長になりました。', answers: ['He became a manager last year.', 'He became a department manager last year.'] },
    ],
    myself: {
      task: '今日の自分の様子か、将来なりたいものを1文で言ってみましょう（feel・become など）。',
      samples: ['I feel great today.', 'I want to become a project manager.'],
      checks: ['feel・look などの後ろは形容詞、become の後ろは名詞か形容詞にした'],
    },
  },
  {
    id: 'g19',
    title: '「人に物を〜する」（give・show・tell＋人＋物）',
    stage: '中学校：文の形',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｲ）c［主語＋動詞＋間接目的語＋直接目的語］（a）名詞・代名詞', page: '41〜42' }],
    points: [
      { text: 'give・show・tell・send・buy・teach などは、動詞＋人＋物 の順で「人に物を〜する」と言えます。', en: ['Tom gave me a pen.', 'I bought him a tie.'] },
      { text: '人と物の順番を入れかえるときは、give・show・tell・send は 物＋to＋人、buy は 物＋for＋人 にします（I gave a pen to Tom. / I bought a tie for him.）。' },
      { text: '「人に」が代名詞のときは me・him・her・us・them の形。' },
      { text: 'teach は知識や技能を教えるとき。連絡先や道などを「教えて」と頼むときは tell や give を使います。' },
    ],
    examples: [
      { tatoeba: 37121, en: 'Tom gave me a pen.' },
      { tatoeba: 260429, en: 'I gave him my address.' },
      { tatoeba: 260328, en: 'I bought him a tie.' },
      { tatoeba: 260299, en: 'I told him the big news.' },
      { tatoeba: 2454235, en: 'Show me that.' },
      { tatoeba: 264001, en: 'Give me time.' },
    ],
    mistakes: [
      { kind: 'meaning', wrong: 'Teach me your email address.', intended: 'メールアドレスを教えてください', right: 'Could you give me your email address?', note: 'teach は勉強や技能を教えるときの語。連絡先は tell / give で頼む。' },
    ],
    exercises: [
      { type: 'fill', ja: 'そのファイルを送っていただけますか。', text: 'Could you ___ me the file?', choices: ['send', 'say', 'speak'], answers: ['send'] },
      { type: 'fill', ja: '上司が私に助言をくれました。', text: 'My boss ___ me some advice.', choices: ['gave', 'said', 'spoke'], answers: ['gave'] },
      { type: 'order', ja: '彼女は私にその地図を見せてくれました。', tokens: ['She', 'showed', 'me', 'the', 'map'], answers: ['She showed me the map.'] },
      { type: 'order', ja: '彼に私の住所を教えました。', tokens: ['I', 'gave', 'him', 'my', 'address'], answers: ['I gave him my address.'] },
      { type: 'rewrite', ja: '「人」を動詞のすぐ後ろに置いて書き直す。', from: 'I gave a present to her.', answers: ['I gave her a present.'] },
      { type: 'rewrite', ja: '「人」を動詞のすぐ後ろに置いて書き直す。', from: 'Tom bought a tie for me.', answers: ['Tom bought me a tie.'] },
      { type: 'oral', ja: 'その資料を送っていただけますか。', answers: ['Could you send me the document?', 'Could you send me the file?'] },
      { type: 'oral', ja: '電話番号を教えていただけますか。', answers: ['Could you give me your phone number?', 'Could you tell me your phone number?'] },
      { type: 'oral', ja: '彼は私にいい助言をくれました。', answers: ['He gave me good advice.', 'He gave me some good advice.'] },
    ],
    myself: {
      task: '最近、誰かにもらったもの・あげたものを、動詞＋人＋物 の形で1文言ってみましょう。',
      samples: ['My friend gave me a nice book.', 'I sent my client a thank-you email.'],
      checks: ['動詞＋人＋物 の順にした（人は me・him などの形）'],
    },
  },
  {
    id: 'g20',
    title: '「AをBと呼ぶ」「AをBにする」（call・make・keep＋人・物＋名詞・形容詞）',
    stage: '中学校：文の形',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｲ）d［主語＋動詞＋目的語＋補語］（a）名詞・形容詞', page: '42〜43' }],
    points: [
      { text: 'call・name＋人＋名詞で「人を〜と呼ぶ・名付ける」。', en: ['We call him Tom.', 'They call me captain.'] },
      { text: 'make＋人・物＋形容詞で「〜を…にする」。', en: ['She makes me happy.', 'The news made her sad.'] },
      { text: 'keep＋物＋形容詞で「〜を…のままにしておく」。', en: ['Keep the door open.'] },
      { text: '「人に物を〜する」（修行場19）と形が似ています。make me happy（私を幸せにする）と make me a cake（私にケーキを作る）のように、後ろが形容詞か物かで意味が変わります。' },
    ],
    examples: [
      { tatoeba: 305366, en: 'They call me captain.' },
      { tatoeba: 4496277, en: 'We call him Tom.' },
      { tatoeba: 314447, en: 'She makes me happy.' },
      { tatoeba: 45158, en: 'The news made her sad.' },
      { tatoeba: 39010, en: 'Keep the door open.' },
      { tatoeba: 274238, en: 'Keep the window closed.' },
    ],
    mistakes: [
      { kind: 'meaning', wrong: 'Please call him Mr. Sato.', intended: '佐藤さんに電話してください', right: 'Please call Mr. Sato.', note: 'call him Mr. Sato は「彼を佐藤さんと呼んでください」の意味になる。' },
    ],
    exercises: [
      { type: 'fill', ja: 'ケンと呼んでください。', text: 'Please call ___ Ken.', choices: ['me', 'my', 'I'], answers: ['me'] },
      { type: 'fill', ja: 'その知らせで私たちはうれしくなりました。', text: 'The news made us ___.', choices: ['happy', 'happily', 'happiness'], answers: ['happy'] },
      { type: 'order', ja: 'ドアは開けたままにしておいてください。', tokens: ['Please', 'keep', 'the', 'door', 'open'], answers: ['Please keep the door open.', 'Keep the door open please.'] },
      { type: 'order', ja: '彼の話を聞いて私は悲しくなりました。', tokens: ['His', 'story', 'made', 'me', 'sad'], answers: ['His story made me sad.'] },
      { type: 'rewrite', ja: 'make を使って「あなたのメールが私をうれしくした」という文にする。', from: 'I was happy because of your email.', answers: ['Your email made me happy.'] },
      { type: 'rewrite', ja: 'call を使って「私たちは彼をボブと呼ぶ」という文にする。', from: 'His name is Robert, but we say "Bob" to him.', answers: ['We call him Bob.'] },
      { type: 'oral', ja: 'ケンと呼んでください。', answers: ['Please call me Ken.', 'Call me Ken.'] },
      { type: 'oral', ja: 'その知らせで彼女はうれしくなりました。', answers: ['The news made her happy.'] },
      { type: 'oral', ja: '窓は閉めたままにしておいてください。', answers: ['Please keep the window closed.', 'Keep the window closed, please.'] },
    ],
    myself: {
      task: '初対面の人に、自分を何と呼んでほしいかを1文で言ってみましょう。',
      samples: ['Please call me Taro.', 'My friends call me Tom.'],
      checks: ['call＋人＋呼び名 の順にした'],
    },
  },
  {
    id: 'g21',
    title: '原形不定詞（let・help・make＋人＋動詞の原形）',
    stage: '中学校：文の形',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｲ）d［主語＋動詞＋目的語＋補語］（b）原形不定詞（Will you let me try? / I helped my father wash the car.）', page: '42〜43' }],
    points: [
      { text: 'let＋人＋動詞の原形で「（人が）〜するのを許す・させてあげる」。Let me 〜 は「私に〜させて」。', en: ['Let me try.', 'Let me think.'] },
      { text: 'help＋人＋動詞の原形で「人が〜するのを手伝う」（help＋人＋to＋原形 とも言います）。', en: ['I helped her wash dishes.'] },
      { text: 'make＋人＋動詞の原形で「（いやでも）人に〜させる」。', en: ['I made him go.'] },
      { text: 'let と make の後ろには to を付けません。' },
    ],
    examples: [
      { tatoeba: 1554612, en: 'Let me try.' },
      { tatoeba: 2249525, en: 'Let me think.' },
      { tatoeba: 1228083, en: 'Let me know.' },
      { tatoeba: 261043, en: 'I helped her wash dishes.' },
      { tatoeba: 423892, en: 'Mary helped her mother cook.' },
      { tatoeba: 260987, en: 'I made him go.' },
      { tatoeba: 2549460, en: 'Tom made me cry.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'Let me to try.', right: 'Let me try.', note: 'let の後ろの動詞には to を付けない。', basis: { doc: 中, page: '43', find: "Will you let me try?" }, dict: { lemma: 'let', pos: 'verb', gloss: 'usually without to' } },
      { kind: 'meaning', wrong: 'I made him go home early.', intended: '（彼が帰りたがっていたので）早く帰らせてあげた', right: 'I let him go home early.', note: 'make は「（いやでも）させる」、let は「（したいように）させてあげる」。' },
    ],
    exercises: [
      { type: 'fill', ja: '手伝わせてください。', text: 'Please let me ___ you.', choices: ['help', 'to help', 'helping'], answers: ['help'] },
      { type: 'fill', ja: '上司は私に報告書を書き直させました。', text: 'My boss made me ___ the report again.', choices: ['write', 'to write', 'writing'], answers: ['write'] },
      { type: 'order', ja: '少し考えさせてください。', tokens: ['Let', 'me', 'think', 'about', 'it'], answers: ['Let me think about it.'] },
      { type: 'order', ja: '私は彼女の引っ越しを手伝いました。', tokens: ['I', 'helped', 'her', 'move'], answers: ['I helped her move.'] },
      { type: 'rewrite', ja: 'Let me で始めて「私にやらせて」と頼む文にする。', from: 'I want to try.', answers: ['Let me try.'] },
      { type: 'rewrite', ja: 'help＋人＋動詞の原形 で1文にする。', from: 'He helped me. I moved.', answers: ['He helped me move.', 'He helped me to move.'] },
      { type: 'oral', ja: '確認させてください。', answers: ['Let me check.', 'Let me check it.'] },
      { type: 'oral', ja: '何かあれば知らせてください。', answers: ['Let me know if you need anything.', 'Please let me know if you have any questions.'] },
      { type: 'oral', ja: '同僚が資料作りを手伝ってくれました。', answers: ['My colleague helped me prepare the documents.', 'My coworker helped me make the materials.'] },
    ],
    myself: {
      task: 'Let me 〜 で、自分が何かをすると申し出る文を1つ言ってみましょう。',
      samples: ['Let me introduce myself.', 'Let me explain the plan.'],
      checks: ['let・make の後ろの動詞は to なしの原形にした'],
    },
  },
  {
    id: 'g22',
    title: '接続詞 and・but・or・so（文と文をつなぐ）',
    stage: '中学校：つなぎ方',
    sources: [
      { doc: 中, where: '第2章第2節 2(1)エ（ｱ）a 重文，複文（重文）', page: '37' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）b 接続詞（and，but，or：文と文を対等につなげる）', page: '45' },
    ],
    points: [
      { text: 'and（そして）、but（しかし）、or（または）、so（だから）で、2つの文をつなげます。', en: ["I'm busy, so I can't go.", 'He tried hard, but he failed.'] },
      { text: 'つなぐ文の主語が同じでも、書くときは2つめの主語を省かないのが基本です（省けるのは and や but で動詞のまとまりを並べるとき）。' },
      { text: '命令文＋or 〜 は「〜しなさい、さもないと…」。命令文＋and 〜 は「〜しなさい、そうすれば…」。' },
      { text: '書くときは、but や so の前にカンマを置くことが多いです。' },
      { text: '話すときは、文を短く切って接続詞でつなぐと伝わりやすくなります。' },
    ],
    examples: [
      { tatoeba: 1439811, en: "I'm busy, so I can't go." },
      { tatoeba: 293750, en: 'He tried hard, but he failed.' },
      { tatoeba: 300227, en: "He likes mathematics, but I don't." },
      { tatoeba: 2626647, en: "Sorry, but I can't stay long." },
      { tatoeba: 33579, en: 'We went to the park, and we played there.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'I like coffee but she like tea.', right: 'I like coffee but she likes tea.', note: 'つないだ後の文も、主語に合わせて動詞の形を決める。', basis: { doc: 中, page: '38', find: "She likes Chinese food." }, dict: { lemma: 'like', pos: 'verb', form: 'likes', tags: ['third-person', 'singular', 'present'] } },
      { kind: 'meaning', wrong: "I'm busy, but I can't go.", intended: '忙しいので行けません', right: "I'm busy, so I can't go.", note: 'but は反対の内容をつなぐ。理由と結果は so でつなぐ。' },
    ],
    exercises: [
      { type: 'fill', ja: '彼に電話しましたが、出ませんでした。', text: "I called him, ___ he didn't answer.", choices: ['but', 'so', 'or'], answers: ['but'] },
      { type: 'fill', ja: '雨が降っていたので、家にいました。', text: 'It was raining, ___ we stayed home.', choices: ['so', 'but', 'or'], answers: ['so'] },
      { type: 'order', ja: '私はコーヒーが好きですが、彼女は紅茶が好きです。', tokens: ['I', 'like', 'coffee', 'but', 'she', 'likes', 'tea'], answers: ['I like coffee, but she likes tea.'] },
      { type: 'order', ja: '急ぎなさい、さもないと遅れますよ。', tokens: ['Hurry', 'up', 'or', "you'll", 'be', 'late'], answers: ["Hurry up, or you'll be late."] },
      { type: 'rewrite', ja: 'so で1文につなぐ。', from: 'I was hungry. I ate a sandwich.', answers: ['I was hungry, so I ate a sandwich.'] },
      { type: 'rewrite', ja: 'but で1文につなぐ。', from: 'He is young. He is very careful.', answers: ['He is young, but he is very careful.', "He's young, but he's very careful."] },
      { type: 'oral', ja: 'すみませんが、明日は行けません。', answers: ["I'm sorry, but I can't go tomorrow.", "Sorry, but I can't come tomorrow."] },
      { type: 'oral', ja: '電車が遅れたので、遅刻しました。', answers: ['The train was late, so I was late.', 'The train was delayed, so I was late.'] },
      { type: 'oral', ja: '会議は10時か11時です。', answers: ['The meeting is at ten or eleven.'] },
    ],
    myself: {
      task: 'and・but・so のどれかで2つの文をつないで、自分のことを1文言ってみましょう。',
      samples: ["I like my job, but it's sometimes hard.", 'I was tired, so I went to bed early.'],
      checks: ['内容に合う接続詞を選んだ（理由→結果は so、反対は but）'],
    },
  },
  {
    id: 'g23',
    title: '接続詞 when・if・because（〜とき・もし〜なら・〜なので）',
    stage: '中学校：つなぎ方',
    sources: [
      { doc: 中, where: '第2章第2節 2(1)エ（ｱ）a 重文，複文（複文）', page: '37' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）b 接続詞（if，when：条件節や時間の副詞節、because：理由の副詞節）', page: '45' },
    ],
    points: [
      { text: 'when＋文で「〜するとき」、if＋文で「もし〜なら」、because＋文で「〜なので」。', en: ['If it rains, call me.', 'He succeeded because he worked hard.'] },
      { text: 'when・if・because のまとまりは、文の前にも後ろにも置けます。前に置くときは、書くときにカンマで区切ります。', en: ['When it rains, she feels blue.', 'Come if you can.'] },
      { text: 'when や if のまとまりの中では、これからのことも現在形で言います（If it rains tomorrow, 〜）。' },
      { text: 'if は「もし（そうなるかは分からない）」、when は「（そうなるのは分かっていて）〜したら」。' },
    ],
    examples: [
      { tatoeba: 371788, en: 'If it rains, call me.' },
      { tatoeba: 26849, en: "I'll stay if it rains." },
      { tatoeba: 450074, en: 'Come if you can.' },
      { tatoeba: 26930, en: 'I stayed indoors because it rained.' },
      { tatoeba: 1003903, en: 'He succeeded because he worked hard.' },
      { tatoeba: 26859, en: 'When it rains, she feels blue.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'If it will rain tomorrow, I will stay home.', right: 'If it rains tomorrow, I will stay home.', note: 'if のまとまりの中は、これからのことでも現在形。', basis: { doc: 中, page: '42', find: "If you want water, I will give you some." }, dict: { lemma: 'rain', pos: 'verb', form: 'rains', tags: ['third-person', 'singular', 'present'] } },
      { kind: 'meaning', wrong: "If I get home, I'll call you.", intended: '家に着いたら電話するね', right: "When I get home, I'll call you.", note: 'if だと「もし家に着けたら」のように、着くかどうか分からない感じになる。' },
    ],
    exercises: [
      { type: 'fill', ja: '着いたら電話します。', text: "I'll call you ___ I arrive.", choices: ['when', 'because', 'but'], answers: ['when'] },
      { type: 'fill', ja: '電車が止まったので遅れました。', text: 'I was late ___ the train stopped.', choices: ['because', 'if', 'so'], answers: ['because'] },
      { type: 'fill', ja: '明日雨なら、催しは中止です。', text: '___ it rains tomorrow, the event will be canceled.', choices: ['If', 'Because', 'But'], answers: ['If'] },
      { type: 'order', ja: '時間があれば手伝いますよ。', tokens: ['If', 'I', 'have', 'time', "I'll", 'help', 'you'], answers: ["If I have time, I'll help you."] },
      { type: 'order', ja: 'かぜをひいたので、家にいました。', tokens: ['I', 'stayed', 'home', 'because', 'I', 'had', 'a', 'cold'], answers: ['I stayed home because I had a cold.', 'Because I had a cold, I stayed home.'] },
      { type: 'rewrite', ja: 'If で1文につなぐ。', from: "It rains tomorrow. I'll stay home.", answers: ["If it rains tomorrow, I'll stay home.", 'If it rains tomorrow, I will stay home.', "I'll stay home if it rains tomorrow.", 'I will stay home if it rains tomorrow.'] },
      { type: 'rewrite', ja: 'because で1文につなぐ。', from: "I was busy. I didn't go.", answers: ["I didn't go because I was busy.", "Because I was busy, I didn't go."] },
      { type: 'oral', ja: '質問があれば、聞いてください。', answers: ['If you have any questions, please ask.', 'Please ask me if you have any questions.'] },
      { type: 'oral', ja: '駅に着いたら電話します。', answers: ["I'll call you when I get to the station.", "When I get to the station, I'll call you."] },
      { type: 'oral', ja: '体調が悪かったので、休みました。', answers: ['I stayed home because I was sick.', 'I took the day off because I was sick.'] },
    ],
    myself: {
      task: 'because を使って、自分が英語を勉強する理由を1文で言ってみましょう。',
      samples: ['I study English because I want to work abroad.', 'I study English because I often talk with overseas clients.'],
      checks: ['because の後ろは 主語＋動詞 の文にした'],
    },
  },
  {
    id: 'g24',
    title: '「〜だと思う」「何が〜か知っている」（that 節・疑問詞の節）',
    stage: '中学校：つなぎ方',
    sources: [
      { doc: 中, where: '第2章第2節 2(1)エ（ｲ）b［主語＋動詞＋目的語］（b）that で始まる節，what などで始まる節', page: '40〜41' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）b 接続詞（that：that 節を作る）', page: '45' },
    ],
    points: [
      { text: 'think・know・hope・believe などの後ろに（that＋）文を続けて、「〜だと思う・知っている」と言います。話すときは that をよく省きます。', en: ['I know you are rich.', 'I hope it helps.'] },
      { text: '「〜ではないと思う」は、ふつう think の方を否定して I don’t think 〜 と言います。' },
      { text: 'what・where・who などで始まるまとまりも続けられます。このときは 疑問詞＋主語＋動詞 の順（疑問文の語順にしない）。', en: ['I know where you live.', 'I wonder what happened.'] },
      { text: '例：Where does she work? → I don’t know where she works.（does を使わず、動詞に -s を付ける）' },
    ],
    examples: [
      { tatoeba: 17881, en: 'I know you are rich.' },
      { tatoeba: 5170489, en: 'I hope it helps.' },
      { tatoeba: 268472, en: 'I think it depends.' },
      { tatoeba: 252673, en: 'I know where you live.' },
      { tatoeba: 17198, en: 'I know what you mean.' },
      { tatoeba: 25162, en: 'I wonder what happened.' },
    ],
    mistakes: [
      { kind: 'informal', wrong: "I think he don't know.", right: "I think he doesn't know.", note: '主語が he・she などのとき、くだけた会話で don’t と言う母語話者もいるが、標準的な英語では doesn’t。正式な場面や書くときは doesn’t を使う。', dict: { lemma: "don't", pos: 'verb', label: 'nonstandard', gloss: 'Does not.' }, spoken: { wrong: "he don't", wrongCount: 27341, right: "he doesn't", rightCount: 257198 } },
    ],
    exercises: [
      { type: 'fill', ja: '彼の言うとおりだと思います。', text: 'I think ___ he is right.', choices: ['that', 'what', 'it'], answers: ['that'] },
      { type: 'fill', ja: '彼がどこに住んでいるか知りません。', text: "I don't know ___ he lives.", choices: ['where', 'that', 'it'], answers: ['where'] },
      { type: 'order', ja: '彼女は来ると思います。', tokens: ['I', 'think', 'she', 'will', 'come'], answers: ['I think she will come.'] },
      { type: 'order', ja: '彼が何を言いたいのかわかります。', tokens: ['I', 'know', 'what', 'he', 'means'], answers: ['I know what he means.'] },
      { type: 'rewrite', ja: 'I think で始めて書き直す。', from: 'He is busy.', answers: ['I think he is busy.', 'I think that he is busy.', "I think he's busy.", "I think that he's busy."] },
      { type: 'rewrite', ja: 'I don’t know で始めて書き直す。', from: 'Where does she work?', answers: ["I don't know where she works."] },
      { type: 'oral', ja: 'それはいい考えだと思います。', answers: ["I think that's a good idea.", "I think it's a good idea."] },
      { type: 'oral', ja: '彼がどこにいるかわかりません。', answers: ["I don't know where he is."] },
      { type: 'oral', ja: '気に入っていただけるといいのですが。', answers: ['I hope you like it.'] },
    ],
    myself: {
      task: 'I think 〜 で、仕事や勉強について自分の意見を1文言ってみましょう。',
      samples: ['I think online meetings are useful.', "I don't think we need more meetings."],
      checks: ['I think の後ろは 主語＋動詞 の文にした'],
    },
  },
  {
    id: 'g25',
    title: '「人に〜だと伝える」（tell・show＋人＋that 節・疑問詞の節）',
    stage: '中学校：つなぎ方',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｲ）c［主語＋動詞＋間接目的語＋直接目的語］（c）that で始まる節，what などで始まる節', page: '41〜42' }],
    points: [
      { text: 'tell・show・teach＋人＋（that＋）文で「人に〜だと伝える・示す」。', en: ['I told him that he was wrong.', "Tom told me he wasn't injured."] },
      { text: '人＋what・where などのまとまりで「人に何が・どこが〜かを伝える」。語順は 疑問詞＋主語＋動詞。', en: ['Please tell me what happened.', 'Please tell me what you think.'] },
      { text: 'たずねるときは Could you tell me 〜? が丁寧です。Where is the station? → Could you tell me where the station is?' },
      { text: '過去のことを伝える文では、that のまとまりの動詞もふつう過去形にします（He told me that he was busy.）。' },
    ],
    examples: [
      { tatoeba: 260479, en: 'I told him that he was wrong.' },
      { tatoeba: 6351022, en: "Tom told me he wasn't injured." },
      { tatoeba: 2199172, en: 'Please tell me what happened.' },
      { tatoeba: 70669, en: 'Please tell me what you think.' },
    ],
    mistakes: [],
    exercises: [
      { type: 'fill', ja: '彼は遅れると私に言いました。', text: 'He told me ___ he would be late.', choices: ['that', 'what', 'where'], answers: ['that'] },
      { type: 'fill', ja: 'あなたの考えを教えてください。', text: 'Please tell me ___ you think.', choices: ['what', 'that', 'it'], answers: ['what'] },
      { type: 'order', ja: '彼は私に、会議が中止になったと言いました。', tokens: ['He', 'told', 'me', 'that', 'the', 'meeting', 'was', 'canceled'], answers: ['He told me that the meeting was canceled.'] },
      { type: 'order', ja: '何が起きたのか教えてください。', tokens: ['Please', 'tell', 'me', 'what', 'happened'], answers: ['Please tell me what happened.', 'Tell me what happened, please.'] },
      { type: 'rewrite', ja: 'Please tell me で始めて書き直す。', from: 'What do you want?', answers: ['Please tell me what you want.'] },
      { type: 'rewrite', ja: 'Could you tell me で始めて書き直す。', from: 'Where is the station?', answers: ['Could you tell me where the station is?'] },
      { type: 'oral', ja: '何が問題なのか教えていただけますか。', answers: ['Could you tell me what the problem is?'] },
      { type: 'oral', ja: '会議室がどこか教えていただけますか。', answers: ['Could you tell me where the meeting room is?'] },
      { type: 'oral', ja: '彼は明日来ると私に言いました。', answers: ['He told me that he would come tomorrow.', 'He told me he would come tomorrow.'] },
    ],
    myself: {
      task: '誰かに言われたうれしかったこと（または伝えたいこと）を、tell＋人＋that で1文言ってみましょう。',
      samples: ['My boss told me that I did a good job.', 'I told my team that the project was a success.'],
      checks: ['tell＋人＋（that）＋文 の順にした'],
    },
  },
  {
    id: 'g26',
    title: '「〜でうれしい」「きっと〜だ」（be動詞＋形容詞＋that 節）',
    stage: '中学校：つなぎ方',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｲ）e（d）主語＋be動詞＋形容詞＋that で始まる節（I’m glad that you like it.）', page: '43〜44' }],
    points: [
      { text: 'glad・happy・sure・sorry・afraid・surprised などの後ろに（that＋）文を続けて、気持ちや確信を言います。that はよく省きます。', en: ["I'm glad you liked it.", "I'm sure they'll win."] },
      { text: 'I’m glad (that) 〜：〜でうれしい。I’m sure (that) 〜：きっと〜だ。I’m sorry (that) 〜：〜で残念・申し訳ない。' },
      { text: 'I’m afraid (that) 〜 は「残念ながら〜」「（よくないことが）〜ではないかと思う」。断るときの丁寧な言い方としてよく使います。', en: ["I'm afraid I can't.", "I'm afraid it will rain."] },
    ],
    examples: [
      { tatoeba: 17999, en: "I'm glad you liked it." },
      { tatoeba: 20675, en: "I'm glad you enjoyed it." },
      { tatoeba: 305593, en: "I'm sure they'll win." },
      { tatoeba: 3819642, en: "I'm sure you're tired." },
      { tatoeba: 245222, en: "I'm afraid I can't." },
      { tatoeba: 28662, en: "I'm sorry I can't go." },
    ],
    mistakes: [
      { kind: 'error', wrong: "I'm sure he come.", right: "I'm sure he comes.", note: 'that のまとまりの中も、主語に合わせて形を決める。', basis: { doc: 中, page: '37', find: "Mary will have lunch before she comes." }, dict: { lemma: 'come', pos: 'verb', form: 'comes', tags: ['third-person', 'singular', 'present'] } },
    ],
    exercises: [
      { type: 'fill', ja: '気に入ってもらえてうれしいです。', text: "I'm ___ you like it.", choices: ['glad', 'sad', 'angry'], answers: ['glad'] },
      { type: 'fill', ja: '彼はきっと来ると思います。', text: "I'm ___ he will come.", choices: ['sure', 'sorry', 'surprised'], answers: ['sure'] },
      { type: 'order', ja: '来てくれてうれしいです。', tokens: ["I'm", 'glad', 'you', 'came'], answers: ["I'm glad you came."] },
      { type: 'order', ja: 'きっと気に入りますよ。', tokens: ["I'm", 'sure', "you'll", 'like', 'it'], answers: ["I'm sure you'll like it."] },
      { type: 'rewrite', ja: 'I’m happy (that) で1文にする。', from: "You passed the exam. I'm happy.", answers: ["I'm happy you passed the exam.", "I'm happy that you passed the exam."] },
      { type: 'rewrite', ja: 'I’m sorry (that) で1文にする。', from: "I can't help you. I'm sorry.", answers: ["I'm sorry I can't help you.", "I'm sorry that I can't help you."] },
      { type: 'oral', ja: '申し訳ありませんが、その日は都合がつきません。', answers: ["I'm afraid I can't make it that day.", "I'm sorry, but I'm not available that day."] },
      { type: 'oral', ja: 'きっとうまくいきますよ。', answers: ["I'm sure it will go well.", "I'm sure it'll work out."] },
      { type: 'oral', ja: '気に入っていただけてうれしいです。', answers: ["I'm glad you like it.", "I'm glad you liked it."] },
    ],
    myself: {
      task: 'I’m glad (that) 〜 で、最近うれしかったことを1文言ってみましょう。',
      samples: ["I'm glad that I passed the test.", "I'm glad my project went well."],
      checks: ['glad などの後ろは 主語＋動詞 の文にした'],
    },
  },
]
