// 文法（フェーズ11）の中身：修行場70〜87（CEFR-J Grammar Profile の B1〜B2）。書き方は items-01-05.mjs と items-65-69.mjs の先頭を参照。
// ✕ は「形の誤り」だけ（CEFR-J の項目の定義＋辞書）。△ には仕事の場面で使ってよいかの一言（work）を付ける。
const GP = 'CEFR-J Grammar Profile 2025（東京外国語大学 投野由紀夫研究室）'

export default [
  {
    id: 'c06',
    title: '「お互いに」「もう一方」「ほかの人たち」（each other・the other・others）',
    stage: 'CEFR B1：会話でよく使う形',
    sources: [{ doc: GP, where: '項目 27 each other（B1.1）・28 one another（B1.2）・29 others（B1.1）・30 the other / the others（B1.2）' }],
    points: [
      { text: 'each other は「お互い（に・を）」。動詞や前置詞の後ろに置きます。', en: ["Let's help each other."] },
      { text: '2つ（2人）のうち、1つ目は one、残りのもう一方は the other。', en: ['One stayed, and the other went away.'] },
      { text: 'Some 〜, others … は「〜な人（物）もいれば、…な人（物）もいる」。others は「（決まっていない）ほかの人たち」。', en: ['Some like tea, others prefer coffee.'] },
      { text: 'the others は「残り全部」。the が付くと、残りがすべて決まっていることを表します。', en: ['Where are all the others?'] },
    ],
    examples: [
      { tatoeba: 240202, en: "Let's help each other." },
      { tatoeba: 305561, en: 'They helped each other.' },
      { tatoeba: 27615, en: 'One stayed and the other went away.' },
      { tatoeba: 240965, en: 'Some like tea, others prefer coffee.' },
      { tatoeba: 51646, en: "Some people like sports, and others don't." },
      { tatoeba: 274644, en: 'Where are all the others?' },
      { tatoeba: 3394014, en: 'Did you ask the others?' },
    ],
    mistakes: [
      { kind: 'meaning', wrong: 'Some like tea, the others prefer coffee.', intended: '紅茶が好きな人もいれば、コーヒーが好きな人もいる', right: 'Some like tea, others prefer coffee.', note: 'the others は「残り全員」。紅茶好き以外が全員コーヒー好き、という意味になる。', work: 'どちらも正しい英語なので仕事で使える。the の有無で意味が変わる。' },
    ],
    exercises: [
      { type: 'fill', ja: 'お互いに助け合いましょう。', text: "Let's help ___.", choices: ['each other', 'the other', 'others'], answers: ['each other'] },
      { type: 'fill', ja: '1人は残り、もう1人は出て行った。', text: 'One stayed, and ___ went away.', choices: ['the other', 'another', 'others'], answers: ['the other'] },
      { type: 'fill', ja: 'スポーツが好きな人もいれば、そうでない人もいる。', text: "Some people like sports, and ___ don't.", choices: ['others', 'other', 'another'], answers: ['others'] },
      { type: 'order', ja: '彼らはお互いに助け合った。', tokens: ['They', 'helped', 'each', 'other'], answers: ['They helped each other.'] },
      { type: 'order', ja: 'ほかの人たちには聞いてみた？', tokens: ['Did', 'you', 'ask', 'the', 'others'], answers: ['Did you ask the others?'] },
      { type: 'rewrite', ja: 'each other を使って1文にする。', from: 'I know him. He knows me.', answers: ['We know each other.'] },
      { type: 'rewrite', ja: 'Some 〜, others … の形で1文にする。', from: "Some students like math. Some students don't.", answers: ["Some students like math, and others don't.", "Some students like math, others don't."] },
      { type: 'oral', ja: '私たちは10年前から知り合いです。', answers: ["We've known each other for ten years.", 'We have known each other for ten years.'] },
      { type: 'oral', ja: '残りの人たちはどこにいますか。', answers: ['Where are the others?', 'Where are all the others?'] },
      { type: 'oral', ja: 'チームのメンバーはお互いに協力すべきだ。', answers: ['Team members should help each other.', 'Team members should work with each other.', 'Team members should cooperate with each other.'] },
    ],
    myself: {
      task: 'each other か Some 〜, others … で、職場や学校の人たちのことを1文で言ってみましょう。',
      samples: ['My colleagues and I help each other a lot.', 'Some people work from home, and others come to the office.'],
      checks: ['「残り全員」のときだけ the others にした'],
    },
  },
  {
    id: 'c07',
    title: '目的と「〜しないように」（in order to・so as to・not to 〜）',
    stage: 'CEFR B1：会話でよく使う形',
    sources: [{ doc: GP, where: '項目 95 in order to（B1.1〜B2.1）・97 so as to（B2.2）・89 not to 不定詞（B1.2）・102 動詞＋not to（B1.1）・104 動詞＋目的語＋not to（B2.1）' }],
    points: [
      { text: 'in order to 〜 は「〜するために」。to 〜 だけより、目的をはっきり言う言い方です。', en: ['He worked hard in order to succeed.'] },
      { text: '「〜しないように」は so as not to 〜 か in order not to 〜。not は to の前に置きます。', en: ['I left early so as not to be late.'] },
      { text: 'decide・try・promise＋not to 〜 は「〜しないことにする・しないようにする・しないと約束する」。', en: ['I decided not to go.'] },
      { text: 'tell・ask・warn＋人＋not to 〜 は「人に〜しないように言う・頼む・注意する」。', en: ['He told me not to smoke.'] },
    ],
    examples: [
      { tatoeba: 300311, en: 'He worked hard in order to succeed.' },
      { tatoeba: 28215, en: 'We use words in order to communicate.' },
      { tatoeba: 277391, en: 'I left early so as not to be late.' },
      { tatoeba: 43449, en: 'I hurried so as not to miss the train.' },
      { tatoeba: 241095, en: 'I decided not to go.' },
      { tatoeba: 258716, en: 'I tried not to laugh.' },
      { tatoeba: 297596, en: 'He told me not to smoke.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'I study hard in order to passing the exam.', right: 'I study hard in order to pass the exam.', note: 'in order to の後ろは動詞の原形。', basis: { doc: GP, item: '95', find: 'in order to V.' }, dict: { lemma: 'pass', pos: 'verb', form: 'pass', tags: ['infinitive'] } },
    ],
    exercises: [
      { type: 'fill', ja: '彼は成功するために一生懸命働いた。', text: 'He worked hard in order ___ succeed.', choices: ['to', 'for', 'that'], answers: ['to'] },
      { type: 'fill', ja: '遅れないように早く出た。', text: 'I left early so as ___ to be late.', choices: ['not', 'no', "don't"], answers: ['not'] },
      { type: 'fill', ja: '彼は私にタバコを吸わないように言った。', text: 'He told me ___ to smoke.', choices: ['not', "don't", 'no'], answers: ['not'] },
      { type: 'order', ja: '電車に乗り遅れないように急いだ。', tokens: ['I', 'hurried', 'so', 'as', 'not', 'to', 'miss', 'the', 'train'], answers: ['I hurried so as not to miss the train.'] },
      { type: 'order', ja: '行かないことにした。', tokens: ['I', 'decided', 'not', 'to', 'go'], answers: ['I decided not to go.'] },
      { type: 'rewrite', ja: 'in order to を使って1文にする。', from: 'She worked hard. She wanted to save money.', answers: ['She worked hard in order to save money.'] },
      { type: 'rewrite', ja: 'told her not to を使って書き直す。', from: 'I said to her, "Don\'t be late."', answers: ['I told her not to be late.'] },
      { type: 'oral', ja: '間違えないように、二度確認しました。', answers: ['I checked it twice so as not to make a mistake.', 'I checked it twice in order not to make a mistake.', 'I checked twice so as not to make mistakes.'] },
      { type: 'oral', ja: '上司に心配しないように言われた。', answers: ['My boss told me not to worry.'] },
      { type: 'oral', ja: '時間を節約するために、オンラインで会議をした。', answers: ['We had an online meeting in order to save time.', 'We met online in order to save time.', 'We had the meeting online in order to save time.'] },
    ],
    myself: {
      task: 'in order to 〜 か so as not to 〜 で、自分が気をつけていることを1文で言ってみましょう。',
      samples: ['I take notes in order to remember new words.', 'I set two alarms so as not to oversleep.'],
      checks: ['「〜しないように」は not を to の前に置いた'],
    },
  },
  {
    id: 'c08',
    title: '「何を〜しても」「いつ〜しても」（whatever・whenever・however など）',
    stage: 'CEFR B1：会話でよく使う形',
    sources: [{ doc: GP, where: '項目 188 whatever / whoever / wherever / however など　CEFR-J レベル B1.1〜B2.1' }],
    points: [
      { text: 'whatever は「何を〜しても」「〜するものは何でも」。', en: ['Whatever happens, keep calm.', 'Whatever you like.'] },
      { text: 'whenever は「〜するときはいつでも」、wherever は「どこへ（で）〜しても」。', en: ["Whenever you come, I'm ready."] },
      { text: 'whoever は「〜する人は誰でも」。' },
      { text: 'however＋形容詞・副詞は「どんなに〜でも」。', en: ["However hard I try, I can't do it."] },
      { text: '答えとして一言で Whatever. と言うと「どうでもいい」と突き放す感じになるので、仕事では使いません。' },
    ],
    examples: [
      { tatoeba: 25150, en: 'Whatever happens, keep calm.' },
      { tatoeba: 64501, en: 'Whatever you like.' },
      { tatoeba: 273527, en: 'Whatever you pick is fine.' },
      { tatoeba: 283592, en: 'Whatever he says is true.' },
      { tatoeba: 18056, en: "Whenever you come, I'm ready." },
      { tatoeba: 22584, en: 'Whenever they meet, they quarrel.' },
      { tatoeba: 38187, en: 'Wherever you say.' },
    ],
    mistakes: [],
    exercises: [
      { type: 'fill', ja: '何が起きても、落ち着いていなさい。', text: '___ happens, keep calm.', choices: ['Whatever', 'However', 'Whenever'], answers: ['Whatever'] },
      { type: 'fill', ja: 'いつ来てくれても、準備はできています。', text: "___ you come, I'm ready.", choices: ['Whenever', 'Whatever', 'Whoever'], answers: ['Whenever'] },
      { type: 'fill', ja: 'どんなに頑張っても、できない。', text: "___ hard I try, I can't do it.", choices: ['However', 'Whatever', 'Wherever'], answers: ['However'] },
      { type: 'order', ja: '選んでいただいたものなら何でも結構です。', tokens: ['Whatever', 'you', 'pick', 'is', 'fine'], answers: ['Whatever you pick is fine.'] },
      { type: 'order', ja: '彼らは会うといつもけんかする。', tokens: ['Whenever', 'they', 'meet', 'they', 'quarrel'], answers: ['Whenever they meet, they quarrel.', 'They quarrel whenever they meet.'] },
      { type: 'rewrite', ja: 'Whatever で始めて書き直す。', from: "It doesn't matter what happens. I will finish it.", answers: ['Whatever happens, I will finish it.', "Whatever happens, I'll finish it."] },
      { type: 'rewrite', ja: 'whenever を使って1文にする。', from: 'Call me at any time you need help.', answers: ['Call me whenever you need help.', 'Whenever you need help, call me.'] },
      { type: 'oral', ja: '困ったときはいつでも聞いてください。', answers: ['Ask me whenever you have a problem.', 'Please ask me whenever you need help.', 'Feel free to ask me whenever you need help.'] },
      { type: 'oral', ja: '何が起きても、締め切りは守ります。', answers: ['Whatever happens, I will meet the deadline.', "Whatever happens, I'll meet the deadline."] },
      { type: 'oral', ja: 'どんなに忙しくても、毎日英語を勉強しています。', answers: ['However busy I am, I study English every day.'] },
    ],
    myself: {
      task: 'whenever か however で、自分の習慣を1文で言ってみましょう。',
      samples: ['Whenever I have free time, I listen to English podcasts.', 'However tired I am, I read a little before bed.'],
      checks: ['however の後ろに形容詞・副詞を置いた（However busy I am）'],
    },
  },
  {
    id: 'c09',
    title: '「〜したほうがいい」「むしろ〜したい」（had better・would rather・might as well）',
    stage: 'CEFR B1：言い方を増やす',
    sources: [{ doc: GP, where: '項目 126 had better（B1.2）・143 would rather（B1.2）・133 might as well（B1.2）' }],
    points: [
      { text: 'had better＋動詞の原形は「〜したほうがいい（しないとまずいことになる）」。強い言い方です。短い形は ’d better。', en: ["You'd better go.", "You'd better not go."] },
      { text: '否定は had better not 〜（not は better の後ろ）。' },
      { text: 'would rather＋動詞の原形は「（どちらかといえば）むしろ〜したい」。than で比べるものを続けられます。', en: ["I'd rather stay home.", "I'd rather not."] },
      { text: 'might as well＋動詞の原形は「〜してもいいかもしれない（ほかにすることもないし）」。', en: ['I might as well leave today.'] },
      { text: '目上の人や取引先への助言には、had better より You might want to 〜 や I’d suggest 〜 のほうが丁寧です。' },
    ],
    examples: [
      { tatoeba: 518555, en: "You'd better go." },
      { tatoeba: 16161, en: "You'd better not go." },
      { tatoeba: 39366, en: "We'd better hurry then." },
      { tatoeba: 4499897, en: "I'd rather stay home." },
      { tatoeba: 54511, en: "I'd rather not." },
      { tatoeba: 38011, en: 'I would rather not go.' },
      { tatoeba: 243041, en: 'I might as well leave today.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'You had better to go.', right: 'You had better go.', note: 'had better の後ろは to を付けずに動詞の原形。', basis: { doc: GP, item: '126', find: 'better V.' }, dict: { lemma: 'go', pos: 'verb', form: 'go', tags: ['infinitive'] } },
      { kind: 'error', wrong: 'I would rather to stay home.', right: 'I would rather stay home.', note: 'would rather の後ろも to を付けずに動詞の原形。', basis: { doc: GP, item: '143', find: 'rather V.' }, dict: { lemma: 'stay', pos: 'verb', form: 'stay', tags: ['infinitive'] } },
      { kind: 'informal', wrong: 'You better go.', right: "You'd better go.", note: '会話では had を省いて You better 〜 と言うことがとても多い。書くときや正式な場面では You’d better 〜。', work: '仕事では使わない。had better 自体も強く聞こえるので、目上の人や取引先には You might want to 〜 が無難。', dict: { lemma: 'better', pos: 'verb', label: 'colloquial', gloss: 'Had better.' }, spoken: { wrong: 'you better', wrongCount: 172532, right: "you'd better", rightCount: 78370 } },
    ],
    exercises: [
      { type: 'fill', ja: 'あなたは行ったほうがいい。', text: "You'd ___ go.", choices: ['better', 'rather', 'well'], answers: ['better'] },
      { type: 'fill', ja: 'どちらかといえば家にいたい。', text: "I'd ___ stay home.", choices: ['rather', 'better', 'like'], answers: ['rather'] },
      { type: 'fill', ja: '行かないほうがいい。', text: "You'd better ___ go.", choices: ['not', "don't", 'no'], answers: ['not'] },
      { type: 'order', ja: 'では急いだほうがいいですね。', tokens: ["We'd", 'better', 'hurry', 'then'], answers: ["We'd better hurry then."] },
      { type: 'order', ja: 'どちらかといえば行きたくない。', tokens: ['I', 'would', 'rather', 'not', 'go'], answers: ['I would rather not go.'] },
      { type: 'rewrite', ja: 'had better を使って書き直す（You’d で始める）。', from: 'You should see a doctor.', answers: ["You'd better see a doctor.", 'You had better see a doctor.'] },
      { type: 'rewrite', ja: 'would rather を使って書き直す（I’d で始める）。', from: 'I prefer to work from home.', answers: ["I'd rather work from home.", 'I would rather work from home.'] },
      { type: 'oral', ja: '今出発したほうがいいですよ。（強く）', answers: ["You'd better leave now.", "You'd better start now.", 'You had better leave now.'] },
      { type: 'oral', ja: 'どちらかといえば電話よりメールがいいです。', answers: ["I'd rather send an email than call.", "I'd rather email than call.", 'I would rather send an email than call.'] },
      { type: 'oral', ja: '待っていても仕方ないので、先に始めてもいいかもしれない。', answers: ['We might as well start now.', 'We might as well start without them.'] },
    ],
    myself: {
      task: 'I’d rather 〜 で、どちらかといえばしたいことを1文で言ってみましょう。',
      samples: ["I'd rather work in the morning than at night.", "I'd rather not work overtime today."],
      checks: ['had better・would rather の後ろは to を付けずに原形にした'],
    },
  },
  {
    id: 'c10',
    title: '関係代名詞 whose（父親が医者である友人）',
    stage: 'CEFR B1：言い方を増やす',
    sources: [{ doc: GP, where: '項目 180 関係代名詞 所有格（whose）　CEFR-J レベル B1.2' }],
    points: [
      { text: '名詞＋whose＋名詞で「（その人・物の）〜が…である名詞」。whose の後ろには必ず名詞が来ます。', en: ['I have a friend whose father is a teacher.'] },
      { text: '人にも物にも使えます。' },
      { text: '発音が同じ who’s（＝who is）と書き間違えないようにします。' },
    ],
    examples: [
      { tatoeba: 250003, en: 'I have a friend whose father is a teacher.' },
      { tatoeba: 249873, en: 'I have a friend whose wife is a pianist.' },
      { tatoeba: 253298, en: 'I know a girl whose father is a lawyer.' },
      { tatoeba: 62975, en: 'Kumi is the girl whose father likes dogs.' },
      { tatoeba: 320893, en: 'The girl whose mother is ill is absent today.' },
      { tatoeba: 1779284, en: 'Are there people whose mother tongue is Esperanto?' },
    ],
    mistakes: [
      { kind: 'error', wrong: "I have a friend who's father is a doctor.", right: 'I have a friend whose father is a doctor.', note: '「〜の」を表すのは whose。who’s は who is の短い形。', basis: { doc: GP, item: '180', find: 'GENITIVE RELATIVE PRONOUN' }, dict: { lemma: 'whose', pos: 'pron', gloss: 'belonging to whom' } },
    ],
    exercises: [
      { type: 'fill', ja: '私には父親が先生をしている友達がいる。', text: 'I have a friend ___ father is a teacher.', choices: ['whose', "who's", 'who'], answers: ['whose'] },
      { type: 'fill', ja: '母親が病気のその少女は、今日は欠席している。', text: 'The girl ___ mother is ill is absent today.', choices: ['whose', 'which', 'who'], answers: ['whose'] },
      { type: 'order', ja: '私は父親が弁護士の女の子を知っている。', tokens: ['I', 'know', 'a', 'girl', 'whose', 'father', 'is', 'a', 'lawyer'], answers: ['I know a girl whose father is a lawyer.'] },
      { type: 'order', ja: '奥さんがピアニストの友人がいる。', tokens: ['I', 'have', 'a', 'friend', 'whose', 'wife', 'is', 'a', 'pianist'], answers: ['I have a friend whose wife is a pianist.'] },
      { type: 'rewrite', ja: 'whose を使って1文にする。', from: 'I met a man. His son works at our company.', answers: ['I met a man whose son works at our company.'] },
      { type: 'rewrite', ja: 'whose を使って1文にする。', from: 'This is the company. Its products are popular.', answers: ['This is the company whose products are popular.'] },
      { type: 'oral', ja: '社長が元エンジニアの会社で働いています。', answers: ['I work for a company whose president used to be an engineer.', 'I work for a company whose president was an engineer.'] },
      { type: 'oral', ja: '名前を思い出せない人に会った。', answers: ["I met someone whose name I can't remember.", "I met a person whose name I can't remember."] },
      { type: 'oral', ja: '父親が医者の友達がいます。', answers: ['I have a friend whose father is a doctor.'] },
    ],
    myself: {
      task: 'whose を使って、知り合いのことを1文で言ってみましょう。',
      samples: ['I have a colleague whose English is excellent.', 'I know a man whose daughter lives in Canada.'],
      checks: ['whose の後ろに名詞を置いた', 'who’s と書き間違えなかった'],
    },
  },
  {
    id: 'c11',
    title: '強調の do（I do agree.・本当に〜する）',
    stage: 'CEFR B1：言い方を増やす',
    sources: [{ doc: GP, where: '項目 53 do / does＋動詞の原形・54 did＋動詞の原形　CEFR-J レベル B1.2' }],
    points: [
      { text: 'ふつうの文の動詞の前に do・does・did を置くと、「本当に〜する」「確かに〜した」と強める言い方になります。', en: ['I do hope so.', 'I do like ice cream.'] },
      { text: 'do・does・did の後ろの動詞は原形です。主語が he・she なら does、過去なら did。', en: ['She does know it.'] },
      { text: '話すときは do を強く言います。「〜ではない」と思われていそうなときに、それを打ち消すのに使います。' },
      { text: '仕事では I do apologize.（本当に申し訳ありません）、We do appreciate 〜（〜に心から感謝しています）のように使います。' },
    ],
    examples: [
      { tatoeba: 273665, en: 'I do hope so.' },
      { tatoeba: 322172, en: 'I do think so.' },
      { tatoeba: 255617, en: 'I do like ice cream.' },
      { tatoeba: 70560, en: 'We do need your advice.' },
      { tatoeba: 312992, en: 'She does know it.' },
      { tatoeba: 54396, en: "I do hope you'll succeed." },
    ],
    mistakes: [
      { kind: 'error', wrong: 'He does works hard.', right: 'He does work hard.', note: 'does の後ろの動詞は原形。-s は does の方に付いている。', basis: { doc: GP, item: '53', find: 'do(es) V.' }, dict: { lemma: 'work', pos: 'verb', form: 'work', tags: ['infinitive'] } },
    ],
    exercises: [
      { type: 'fill', ja: '本当にそう思います。', text: 'I ___ think so.', choices: ['do', 'am', 'does'], answers: ['do'] },
      { type: 'fill', ja: '彼女は確かにそのことを知っているんです。', text: 'She does ___ it.', choices: ['know', 'knows', 'knew'], answers: ['know'] },
      { type: 'order', ja: 'あなたの助言がぜひとも必要です。', tokens: ['We', 'do', 'need', 'your', 'advice'], answers: ['We do need your advice.'] },
      { type: 'order', ja: 'ご成功を心からお祈りしています。', tokens: ['I', 'do', 'hope', "you'll", 'succeed'], answers: ["I do hope you'll succeed."] },
      { type: 'rewrite', ja: 'do を使って強める。', from: 'I want to go.', answers: ['I do want to go.'] },
      { type: 'rewrite', ja: 'did を使って強める（「確かに送りました」）。', from: 'I sent the email.', answers: ['I did send the email.'] },
      { type: 'oral', ja: '本当に申し訳ありません。', answers: ['I do apologize.'] },
      { type: 'oral', ja: 'ご協力に心から感謝しています。', answers: ['We do appreciate your help.', 'We do appreciate your cooperation.', 'I do appreciate your help.'] },
      { type: 'oral', ja: '確かに昨日電話しましたよ。', answers: ['I did call you yesterday.', 'I did call yesterday.'] },
    ],
    myself: {
      task: '強調の do を使って、本当にそう思っていることを1文で言ってみましょう。',
      samples: ['I do want to improve my English.', 'I do appreciate your support.'],
      checks: ['do・does・did の後ろは動詞の原形にした'],
    },
  },
  {
    id: 'c12',
    title: '未来完了（will have done：〜までに…しているだろう）',
    stage: 'CEFR B1：言い方を増やす',
    sources: [{ doc: GP, where: '項目 71 未来完了形（will have＋過去分詞）　CEFR-J レベル B1.2〜B2.1' }],
    points: [
      { text: 'will have＋過去分詞で、未来のある時までに「〜し終えているだろう」を表します。', en: ['I will have finished the work by noon.'] },
      { text: '「いつまでに」は by 〜（〜までに）や before 〜 で示すことが多いです。' },
      { text: '現在完了（修行場36〜38）の「今」を、未来のある時にずらした形です。' },
      { text: '仕事の予定や見通しを伝えるときに便利です（By Friday, we will have completed 〜）。' },
    ],
    examples: [
      { tatoeba: 47623, en: 'I will have finished the work by noon.' },
      { tatoeba: 23777, en: 'I will have finished my homework by Tuesday.' },
      { tatoeba: 252630, en: "I will have finished the work by eight o'clock." },
      { tatoeba: 304097, en: 'He will have done his homework by tomorrow.' },
      { tatoeba: 17712, en: 'I will have left here before you return.' },
      { tatoeba: 50686, en: 'The album will have been completed by next July.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'I will have finish the work by noon.', right: 'I will have finished the work by noon.', note: 'will have の後ろは過去分詞。', basis: { doc: GP, item: '71', find: 'have V.N' }, dict: { lemma: 'finish', pos: 'verb', form: 'finished', tags: ['participle', 'past'] } },
    ],
    exercises: [
      { type: 'fill', ja: '昼までにはその仕事を終えているでしょう。', text: 'I will have ___ the work by noon.', choices: ['finished', 'finish', 'finishing'], answers: ['finished'] },
      { type: 'fill', ja: '彼は明日までには宿題を終えているだろう。', text: 'He will ___ done his homework by tomorrow.', choices: ['have', 'has', 'had'], answers: ['have'] },
      { type: 'order', ja: '火曜日までには宿題を終えているでしょう。', tokens: ['I', 'will', 'have', 'finished', 'my', 'homework', 'by', 'Tuesday'], answers: ['I will have finished my homework by Tuesday.', 'By Tuesday, I will have finished my homework.'] },
      { type: 'order', ja: 'あなたが戻る前に、私はここを出ているでしょう。', tokens: ['I', 'will', 'have', 'left', 'here', 'before', 'you', 'return'], answers: ['I will have left here before you return.', 'Before you return, I will have left here.'] },
      { type: 'rewrite', ja: 'will have を使って「〜までに終えているだろう」にする。', from: 'I will finish the report by Friday.', answers: ['I will have finished the report by Friday.', "I'll have finished the report by Friday."] },
      { type: 'rewrite', ja: 'will have を使って「〜までに着いているだろう」にする。', from: 'They will arrive there before you start.', answers: ['They will have arrived there before you start.'] },
      { type: 'oral', ja: '金曜日までには資料を送っているでしょう。', answers: ['I will have sent the documents by Friday.', "I'll have sent the documents by Friday.", 'I will have sent the materials by Friday.'] },
      { type: 'oral', ja: '来年の今ごろには、ここで5年働いたことになる。', answers: ['By this time next year, I will have worked here for five years.', "By this time next year, I'll have worked here for five years.", 'I will have worked here for five years by this time next year.'] },
      { type: 'oral', ja: '会議が始まるまでには準備を終えているでしょう。', answers: ['I will have finished preparing before the meeting starts.', "I'll have finished preparing before the meeting starts.", 'I will have finished preparing by the time the meeting starts.'] },
    ],
    myself: {
      task: '未来完了で、ある時までに終えている予定のことを1文で言ってみましょう。',
      samples: ['By the end of this year, I will have read ten English books.', 'I will have finished this project by March.'],
      checks: ['will have の後ろは過去分詞にした', '「いつまでに」を by などで示した'],
    },
  },
  {
    id: 'c13',
    title: '進行形・完了形の受け身（is being done・has been done）',
    stage: 'CEFR B1：言い方を増やす',
    sources: [{ doc: GP, where: '項目 74 受動態（現在進行形）is being＋過去分詞（B1.2〜B2.1）・75 受動態（現在完了形）have been＋過去分詞（B2.1）' }],
    points: [
      { text: 'is / are being＋過去分詞は「（今）〜されているところだ」。', en: ['My car is being repaired.'] },
      { text: 'has / have been＋過去分詞は「〜されてしまった・もう〜された」。', en: ["Today's meeting has been canceled."] },
      { text: '仕事の連絡でとてもよく使います（The system is being updated. / The order has been shipped.）。' },
      { text: '受け身の be の部分を進行形（being）や完了形（have been）にした形です（修行場35・56と同じ考え方）。' },
    ],
    examples: [
      { tatoeba: 251055, en: 'My car is being repaired.' },
      { tatoeba: 18979, en: 'The bridge is being repaired.' },
      { tatoeba: 49387, en: 'The house is being built now.' },
      { tatoeba: 263553, en: 'The fitting room is being used now.' },
      { tatoeba: 243061, en: "Today's meeting has been canceled." },
      { tatoeba: 49330, en: 'The house has been sold.' },
      { tatoeba: 1739711, en: 'My wallet has been stolen.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'The system is being update.', right: 'The system is being updated.', note: 'being の後ろは過去分詞。', basis: { doc: GP, item: '74', find: 'being V.N' }, dict: { lemma: 'update', pos: 'verb', form: 'updated', tags: ['participle', 'past'] } },
      { kind: 'error', wrong: 'The plan has been approve.', right: 'The plan has been approved.', note: 'has been の後ろは過去分詞。', basis: { doc: GP, item: '75', find: 'been V.N' }, dict: { lemma: 'approve', pos: 'verb', form: 'approved', tags: ['participle', 'past'] } },
      { kind: 'meaning', wrong: 'The room is cleaned.', intended: '部屋は今、掃除されているところだ', right: 'The room is being cleaned.', note: 'is cleaned は「（ふだん）掃除される」「掃除してある」。今まさに掃除中なら is being cleaned。', work: 'どちらも正しい英語なので仕事で使える。「今〜中」と伝えたいときは being を入れる。' },
    ],
    exercises: [
      { type: 'fill', ja: '私の車は修理中です。', text: 'My car is being ___.', choices: ['repaired', 'repair', 'repairing'], answers: ['repaired'] },
      { type: 'fill', ja: '今日の会議は中止になりました。', text: "Today's meeting has ___ canceled.", choices: ['been', 'being', 'be'], answers: ['been'] },
      { type: 'fill', ja: 'その家は今建築中だ。', text: 'The house is ___ built now.', choices: ['being', 'been', 'be'], answers: ['being'] },
      { type: 'order', ja: '財布が盗まれた。', tokens: ['My', 'wallet', 'has', 'been', 'stolen'], answers: ['My wallet has been stolen.'] },
      { type: 'order', ja: '試着室は今使用中だ。', tokens: ['The', 'fitting', 'room', 'is', 'being', 'used', 'now'], answers: ['The fitting room is being used now.'] },
      { type: 'rewrite', ja: '受け身にする（The bridge で始める）。', from: 'They are repairing the bridge.', answers: ['The bridge is being repaired.'] },
      { type: 'rewrite', ja: '受け身にする（The house で始める）。', from: 'Someone has sold the house.', answers: ['The house has been sold.'] },
      { type: 'oral', ja: 'システムは今、更新中です。', answers: ['The system is being updated.', 'The system is being updated now.'] },
      { type: 'oral', ja: 'ご注文の品は発送されました。', answers: ['Your order has been shipped.', 'Your order has been sent.'] },
      { type: 'oral', ja: 'その問題はもう解決されました。', answers: ['The problem has been solved.', 'The problem has already been solved.', 'The issue has been resolved.'] },
    ],
    myself: {
      task: 'is being 〜 か has been 〜 で、職場や身の回りの状況を1文で言ってみましょう。',
      samples: ['A new office is being built near my house.', 'Our project has been approved.'],
      checks: ['being・been の後ろは過去分詞にした'],
    },
  },
  {
    id: 'c14',
    title: '提案・要求の that 節（I suggest that he go.）',
    stage: 'CEFR B1：言い方を増やす',
    sources: [{ doc: GP, where: '項目 217 demand / insist / propose / recommend / suggest など＋that 節（動詞の原形）　CEFR-J レベル B1.2〜B2.2' }],
    points: [
      { text: 'suggest・recommend・demand・insist・propose の後ろの that 節では、動詞を原形にします（主語が he・she でも -s を付けない）。', en: ['I suggested that she go alone.'] },
      { text: 'be動詞も原形の be になります。', en: ['I demanded that they be allowed to leave.'] },
      { text: 'that は省くこともあります。', en: ['I suggested she go there alone.'] },
      { text: 'イギリス英語では that 節に should を入れる言い方（I suggest that he should go.）もよく使います。' },
      { text: '仕事の提案や推薦で使います（I recommend that we start early.）。' },
    ],
    examples: [
      { tatoeba: 259558, en: 'I suggested that we go fishing.' },
      { tatoeba: 260997, en: 'I suggested that she go alone.' },
      { tatoeba: 283045, en: 'I suggested that he go there at once.' },
      { tatoeba: 28021, en: 'The doctor insisted that he stay in bed.' },
      { tatoeba: 297344, en: 'He demanded that we leave at once.' },
      { tatoeba: 975499, en: 'He proposed that we take a small break.' },
      { tatoeba: 260650, en: 'I demanded that they be allowed to leave.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'I suggest him to go there.', right: 'I suggest that he go there.', note: 'suggest は「人＋to 〜」の形をとらない。that＋主語＋動詞の原形にする。', basis: { doc: GP, item: '217', find: '(that)? 名詞句・代名詞 V.P?' }, dict: { lemma: 'go', pos: 'verb', form: 'go', tags: ['present', 'subjunctive'] } },
    ],
    exercises: [
      { type: 'fill', ja: '彼女が一人で行くよう提案した。', text: 'I suggested that she ___ alone.', choices: ['go', 'goes', 'to go'], answers: ['go'] },
      { type: 'fill', ja: '医者は彼が寝ているようにと強く言った。', text: 'The doctor insisted that he ___ in bed.', choices: ['stay', 'stays', 'to stay'], answers: ['stay'] },
      { type: 'order', ja: '彼は小休止しようと提案した。', tokens: ['He', 'proposed', 'that', 'we', 'take', 'a', 'small', 'break'], answers: ['He proposed that we take a small break.'] },
      { type: 'order', ja: '父はキャンプに行こうと提案した。', tokens: ['My', 'father', 'suggested', 'that', 'we', 'go', 'camping'], answers: ['My father suggested that we go camping.'] },
      { type: 'rewrite', ja: 'I suggest that で始めて書き直す。', from: "Let's start the meeting early.", answers: ['I suggest that we start the meeting early.'] },
      { type: 'rewrite', ja: 'I recommend that で始めて書き直す。', from: 'He should see a doctor.', answers: ['I recommend that he see a doctor.'] },
      { type: 'oral', ja: '先にデータを確認することを提案します。', answers: ['I suggest that we check the data first.', 'I suggest we check the data first.'] },
      { type: 'oral', ja: '彼女がその会議に出ることを勧めます。', answers: ['I recommend that she attend the meeting.', 'I recommend that she go to the meeting.'] },
      { type: 'oral', ja: '部長は報告書を明日までに出すよう求めた。', answers: ['The manager demanded that the report be submitted by tomorrow.', 'The manager demanded that we submit the report by tomorrow.'] },
    ],
    myself: {
      task: 'I suggest that we 〜 で、仕事や勉強の提案を1文で言ってみましょう。',
      samples: ['I suggest that we meet once a week.', 'I recommend that you read the manual first.'],
      checks: ['that の後ろの動詞は原形にした（主語が he・she でも -s なし）'],
    },
  },
  {
    id: 'c15',
    title: '「まさに〜しようとしている」「〜する予定だ」（be about to・be to）',
    stage: 'CEFR B2：仕事で差がつく形',
    sources: [{ doc: GP, where: '項目 100 be about to（B2.1）・99 be to 不定詞（B1.2）' }],
    points: [
      { text: 'be about to＋動詞の原形は「まさに〜しようとしている（すぐに〜する）」。', en: ['She is about to leave.', 'Class is about to start.'] },
      { text: 'be to＋動詞の原形は「〜することになっている（予定）」。かたい言い方で、ニュースや公式の予定でよく使います。', en: ['We are to meet at noon.'] },
      { text: 'be to は「〜すべきだ」（指示・規則）の意味にもなります。', en: ['Rules are to be observed.'] },
    ],
    examples: [
      { tatoeba: 314958, en: 'She is about to leave.' },
      { tatoeba: 10911464, en: 'Class is about to begin.' },
      { tatoeba: 304850, en: 'He was about to speak.' },
      { tatoeba: 22864, en: 'We are to meet at noon.' },
      { tatoeba: 304111, en: 'He is to start tomorrow.' },
      { tatoeba: 20223, en: 'Rules are to be observed.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'She is about to leaving.', right: 'She is about to leave.', note: 'be about to の後ろは動詞の原形。', basis: { doc: GP, item: '100', find: 'about to V.' }, dict: { lemma: 'leave', pos: 'verb', form: 'leave', tags: ['infinitive'] } },
    ],
    exercises: [
      { type: 'fill', ja: '授業がもうすぐ始まる。', text: 'Class is about ___ begin.', choices: ['to', 'for', 'of'], answers: ['to'] },
      { type: 'fill', ja: '彼はまさに話そうとしていた。', text: 'He was about to ___.', choices: ['speak', 'speaking', 'spoke'], answers: ['speak'] },
      { type: 'order', ja: '私たちは正午に会うことになっている。', tokens: ['We', 'are', 'to', 'meet', 'at', 'noon'], answers: ['We are to meet at noon.'] },
      { type: 'order', ja: '彼女はちょうど出かけるところだ。', tokens: ['She', 'is', 'about', 'to', 'leave'], answers: ['She is about to leave.'] },
      { type: 'rewrite', ja: 'be about to を使って「今にも〜しそう」にする。', from: 'The meeting will start very soon.', answers: ['The meeting is about to start.'] },
      { type: 'rewrite', ja: 'be to を使って「〜することになっている」にする。', from: 'The president plans to visit Japan next week.', answers: ['The president is to visit Japan next week.'] },
      { type: 'oral', ja: 'ちょうどお電話しようとしていたところです。', answers: ['I was about to call you.', 'I was just about to call you.'] },
      { type: 'oral', ja: '会議がもうすぐ始まります。', answers: ['The meeting is about to start.', 'The meeting is about to begin.'] },
      { type: 'oral', ja: '新しい社長は来月就任することになっている。', answers: ['The new president is to take office next month.', 'The new president is to start next month.'] },
    ],
    myself: {
      task: 'I was about to 〜 で、「ちょうど〜しようとしていた」ことを1文で言ってみましょう。',
      samples: ['I was about to leave when my boss called me.', 'I was about to email you.'],
      checks: ['about to・be to の後ろは動詞の原形にした'],
    },
  },
  {
    id: 'c16',
    title: '「〜と言われた」「〜をもらった」（I was told 〜・I was given 〜）',
    stage: 'CEFR B2：仕事で差がつく形',
    sources: [{ doc: GP, where: '項目 85 間接目的語を主語にした受け身（is given / sent / shown / taught / told＋直接目的語）・86 直接目的語を主語にした受け身（… to＋間接目的語）　CEFR-J レベル B2.1' }],
    points: [
      { text: 'give・tell・show・send・teach は目的語を2つとる動詞（修行場19）。「人」を主語にした受け身にできます。', en: ['I was given a new jacket.'] },
      { text: 'I was told 〜 は「〜と言われた・聞いた」。I was told to 〜 は「〜するように言われた」。', en: ["That's what I was told.", 'She was told to accompany me.'] },
      { text: '「物」を主語にするときは、人の前に to を置きます（The letter was sent to me.）。' },
      { text: '誰が言ったか・くれたかを言わずにすむので、仕事の連絡でよく使います。' },
    ],
    examples: [
      { tatoeba: 269187, en: 'I was given a new jacket.' },
      { tatoeba: 299356, en: 'He was given an important mission.' },
      { tatoeba: 3199957, en: "That's what I was told." },
      { tatoeba: 314279, en: 'She was told to accompany me.' },
      { tatoeba: 253458, en: 'I was asked to wait here.' },
      { tatoeba: 252314, en: 'I was taught to respect my elders.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'I was teached English by him.', right: 'I was taught English by him.', note: 'teach の過去分詞は taught。', basis: { doc: GP, item: '85', find: 'given|passed|sent|shown|taught|told' }, dict: { lemma: 'teach', pos: 'verb', form: 'taught', tags: ['participle', 'past'] } },
    ],
    exercises: [
      { type: 'fill', ja: '新しい上着をもらった。', text: 'I was ___ a new jacket.', choices: ['given', 'gave', 'give'], answers: ['given'] },
      { type: 'fill', ja: 'ここで待つように頼まれた。', text: 'I was asked ___ wait here.', choices: ['to', 'for', 'that'], answers: ['to'] },
      { type: 'order', ja: '私はそう聞きました。', tokens: ["That's", 'what', 'I', 'was', 'told'], answers: ["That's what I was told."] },
      { type: 'order', ja: '彼は重要な任務を任された。', tokens: ['He', 'was', 'given', 'an', 'important', 'mission'], answers: ['He was given an important mission.'] },
      { type: 'rewrite', ja: 'I で始めて受け身にする。', from: 'My boss told me to finish it today.', answers: ['I was told to finish it today.', 'I was told by my boss to finish it today.'] },
      { type: 'rewrite', ja: 'I で始めて受け身にする。', from: 'They showed me the new office.', answers: ['I was shown the new office.'] },
      { type: 'oral', ja: '会議は中止だと聞きました。', answers: ['I was told that the meeting was canceled.', 'I was told the meeting was canceled.', 'I was told that the meeting had been canceled.'] },
      { type: 'oral', ja: 'そのデータを送るよう頼まれました。', answers: ['I was asked to send the data.'] },
      { type: 'oral', ja: '新しいプロジェクトを任されました。', answers: ['I was given a new project.'] },
    ],
    myself: {
      task: 'I was told 〜 か I was given 〜 で、最近言われたこと・もらったものを1文で言ってみましょう。',
      samples: ['I was told to prepare a presentation for next week.', 'I was given a chance to work abroad.'],
      checks: ['was の後ろは過去分詞（told・given・taught など）にした'],
    },
  },
  {
    id: 'c17',
    title: '強調構文（It is … that 〜：〜のは…だ）',
    stage: 'CEFR B2：仕事で差がつく形',
    sources: [{ doc: GP, where: '項目 204 強調構文（前置詞句・副詞を強調）　CEFR-J レベル B2.1' }],
    points: [
      { text: 'It is（was）＋強めたい語句＋that 〜 で、「〜のは…だ」とその語句を目立たせます。', en: ['It was yesterday that I met her.'] },
      { text: '時・場所・人・物など、いろいろな語句を強められます。', en: ['It was here that I saw her.'] },
      { text: '強めたい語句を It is と that の間から外すと、ふつうの文に戻ります（I met her yesterday.）。' },
      { text: '仕事では、誤解を正すときに便利です（It was the client that changed the schedule, not us.）。' },
    ],
    examples: [
      { tatoeba: 247033, en: 'It was yesterday that I met her.' },
      { tatoeba: 247007, en: 'It was yesterday that I saw him.' },
      { tatoeba: 247047, en: 'It was here that I saw her.' },
      { tatoeba: 283701, en: 'It was yesterday that he died.' },
      { tatoeba: 283075, en: 'It was yesterday that he went there.' },
    ],
    mistakes: [],
    exercises: [
      { type: 'fill', ja: '私が彼女に会ったのは昨日だった。', text: 'It was yesterday ___ I met her.', choices: ['that', 'what', 'when'], answers: ['that'] },
      { type: 'fill', ja: '私が彼女を見たのはここだった。', text: '___ was here that I saw her.', choices: ['It', 'This', 'There'], answers: ['It'] },
      { type: 'order', ja: '彼がそこへ行ったのは昨日だった。', tokens: ['It', 'was', 'yesterday', 'that', 'he', 'went', 'there'], answers: ['It was yesterday that he went there.'] },
      { type: 'order', ja: '予定を変えたのはお客さんだった。', tokens: ['It', 'was', 'the', 'client', 'that', 'changed', 'the', 'schedule'], answers: ['It was the client that changed the schedule.'] },
      { type: 'rewrite', ja: 'It was … that で「彼に会ったのは駅だった」を強める。', from: 'I met him at the station.', answers: ['It was at the station that I met him.'] },
      { type: 'rewrite', ja: 'It was … that で「私が知りたかったのは値段だった」を強める。', from: 'I wanted to know the price.', answers: ['It was the price that I wanted to know.'] },
      { type: 'oral', ja: '問題を見つけたのはトムだった。', answers: ['It was Tom that found the problem.', 'It was Tom who found the problem.'] },
      { type: 'oral', ja: '私が英語を勉強し始めたのは去年だった。', answers: ['It was last year that I started studying English.', 'It was last year that I started to study English.'] },
      { type: 'oral', ja: '大事なのは結果ではなく、過程です。', answers: ['It is the process, not the result, that matters.', "It's the process, not the result, that matters.", 'It is not the result but the process that matters.'] },
    ],
    myself: {
      task: 'It was … that 〜 で、自分の経験の「いつ・どこ」を強めて1文で言ってみましょう。',
      samples: ['It was in London that I first spoke English with a native speaker.', 'It was my teacher that encouraged me to study abroad.'],
      checks: ['強めたい語句を It was と that の間に置いた'],
    },
  },
  {
    id: 'c18',
    title: '「〜すればするほど…」（the＋比較級, the＋比較級）',
    stage: 'CEFR B2：仕事で差がつく形',
    sources: [{ doc: GP, where: '項目 50 the＋比較級 (...), the＋比較級　CEFR-J レベル B2.1' }],
    points: [
      { text: 'The＋比較級＋主語＋動詞, the＋比較級＋主語＋動詞で「〜すればするほど、ますます…」。', en: ['The more I get, the more I want.'] },
      { text: '両方の比較級に the を付けます。' },
      { text: '短い決まり文句もあります：The sooner, the better.（早ければ早いほどよい）', en: ['The sooner, the better.', 'The more, the better.'] },
    ],
    examples: [
      { tatoeba: 2308, en: 'The sooner, the better.' },
      { tatoeba: 274947, en: 'The more, the better.' },
      { tatoeba: 263851, en: 'The more I get, the more I want.' },
      { tatoeba: 266271, en: 'The more you earn, the more you spend.' },
      { tatoeba: 249151, en: 'The older we grow, the less we dream.' },
      { tatoeba: 11045595, en: 'The more data we have, the better.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'The more you practice, more you improve.', right: 'The more you practice, the more you improve.', note: '後ろの比較級にも the を付ける。', basis: { doc: GP, item: '50', find: ', the (JJR|RBR)' }, dict: { lemma: 'much', pos: 'det', form: 'more', tags: ['comparative'] } },
    ],
    exercises: [
      { type: 'fill', ja: '早ければ早いほどよい。', text: 'The sooner, ___ better.', choices: ['the', 'more', 'a'], answers: ['the'] },
      { type: 'fill', ja: '稼げば稼ぐほど使う。', text: 'The more you earn, the ___ you spend.', choices: ['more', 'much', 'most'], answers: ['more'] },
      { type: 'order', ja: '持てば持つほど欲しくなる。', tokens: ['The', 'more', 'I', 'get', 'the', 'more', 'I', 'want'], answers: ['The more I get, the more I want.'] },
      { type: 'order', ja: 'データは多ければ多いほどいい。', tokens: ['The', 'more', 'data', 'we', 'have', 'the', 'better'], answers: ['The more data we have, the better.'] },
      { type: 'rewrite', ja: 'The＋比較級, the＋比較級で1文にする。', from: 'If you practice more, you will improve more.', answers: ['The more you practice, the more you will improve.', 'The more you practice, the more you improve.'] },
      { type: 'rewrite', ja: 'The＋比較級, the＋比較級で1文にする。', from: 'If we start earlier, we will finish earlier.', answers: ['The earlier we start, the earlier we will finish.', 'The earlier we start, the earlier we finish.', 'The sooner we start, the sooner we will finish.', 'The sooner we start, the sooner we finish.'] },
      { type: 'oral', ja: 'お返事は早ければ早いほど助かります。', answers: ['The sooner you reply, the better.', 'The sooner, the better.'] },
      { type: 'oral', ja: '英語を話せば話すほど、自信がつく。', answers: ['The more I speak English, the more confident I become.', 'The more you speak English, the more confident you become.', 'The more I speak English, the more confident I get.'] },
      { type: 'oral', ja: '準備すればするほど、うまくいく。', answers: ['The more you prepare, the better it goes.', 'The more we prepare, the better it goes.', 'The more you prepare, the better the result.'] },
    ],
    myself: {
      task: 'The＋比較級, the＋比較級で、自分の経験から言えることを1文で言ってみましょう。',
      samples: ['The more I read in English, the faster I can read.', 'The earlier I get up, the more I can do.'],
      checks: ['両方の比較級に the を付けた'],
    },
  },
  {
    id: 'c19',
    title: '「〜したようだ」「〜されたい」（to have done・to be done）',
    stage: 'CEFR B2：仕事で差がつく形',
    sources: [{ doc: GP, where: '項目 90 to have＋過去分詞・91 to be＋過去分詞　CEFR-J レベル B2.1' }],
    points: [
      { text: 'seem to have＋過去分詞は「（以前に）〜したようだ・〜だったようだ」。seem to 〜（修行場49）より前の時のことを表します。', en: ['He seems to have been ill.'] },
      { text: 'to be＋過去分詞は「〜されること」。want・like・need などの後ろで使います。', en: ["I don't want to be seen with him.", 'Tom needs to be told the truth.'] },
      { text: '仕事では What would you like to be called?（何とお呼びすればいいですか）のように使います。', en: ['What would you like to be called?'] },
    ],
    examples: [
      { tatoeba: 303159, en: 'He seemed to have been ill.' },
      { tatoeba: 295494, en: 'He seems to have been rich.' },
      { tatoeba: 316669, en: 'She seems to have been ill.' },
      { tatoeba: 37567, en: 'What would you like to be called?' },
      { tatoeba: 6736298, en: 'Tom needs to be told the truth.' },
      { tatoeba: 550272, en: "I don't want to be seen with him." },
    ],
    mistakes: [
      { kind: 'error', wrong: 'He seems to have know it.', right: 'He seems to have known it.', note: 'to have の後ろは過去分詞。', basis: { doc: GP, item: '90', find: 'to have V.N' }, dict: { lemma: 'know', pos: 'verb', form: 'known', tags: ['participle', 'past'] } },
      { kind: 'error', wrong: 'What would you like to be call?', right: 'What would you like to be called?', note: 'to be の後ろは過去分詞（「呼ばれる」）。', basis: { doc: GP, item: '91', find: 'to be V.N' }, dict: { lemma: 'call', pos: 'verb', form: 'called', tags: ['participle', 'past'] } },
    ],
    exercises: [
      { type: 'fill', ja: '彼は病気だったようだ。', text: 'He seems to have ___ ill.', choices: ['been', 'be', 'was'], answers: ['been'] },
      { type: 'fill', ja: '何とお呼びすればいいですか。', text: 'What would you like to be ___?', choices: ['called', 'call', 'calling'], answers: ['called'] },
      { type: 'order', ja: '彼女は病気だったと思われる。', tokens: ['She', 'seems', 'to', 'have', 'been', 'ill'], answers: ['She seems to have been ill.'] },
      { type: 'order', ja: 'トムには本当のことを伝える必要がある。', tokens: ['Tom', 'needs', 'to', 'be', 'told', 'the', 'truth'], answers: ['Tom needs to be told the truth.'] },
      { type: 'rewrite', ja: 'He seems to have で始めて書き直す。', from: 'It seems that he left early.', answers: ['He seems to have left early.'] },
      { type: 'rewrite', ja: 'to be＋過去分詞を使って書き直す。', from: "I don't want people to see me with him.", answers: ["I don't want to be seen with him."] },
      { type: 'oral', ja: '彼は会議のことを忘れていたようだ。', answers: ['He seems to have forgotten about the meeting.', 'He seems to have forgotten the meeting.'] },
      { type: 'oral', ja: 'この書類は今日中に署名される必要がある。', answers: ['This document needs to be signed today.'] },
      { type: 'oral', ja: '誰でも認められたいものだ。', answers: ['Everyone wants to be recognized.', 'Everyone wants to be appreciated.', 'Everybody wants to be recognized.'] },
    ],
    myself: {
      task: 'need to be＋過去分詞で、仕事で「〜される必要がある」ことを1文で言ってみましょう。',
      samples: ['This report needs to be checked by my manager.', 'The meeting room needs to be booked in advance.'],
      checks: ['to have・to be の後ろは過去分詞にした'],
    },
  },
  {
    id: 'c20',
    title: '「万一〜なら」（If you should 〜・Should you 〜）',
    stage: 'CEFR B2：仕事で差がつく形',
    sources: [{ doc: GP, where: '項目 224 if 節の中の should（if it should rain tomorrow など）　CEFR-J レベル B2.1' }],
    points: [
      { text: 'If＋主語＋should＋動詞の原形は「万一〜なら」。起こる可能性が低いと考えていることを表します。', en: ['If you should change your mind, let me know.'] },
      { text: 'If を省いて Should＋主語＋動詞の原形で始めることもできます。かたい言い方で、ビジネスメールの決まり文句です。', en: ['Should you change your mind, let me know.'] },
      { text: '後ろの文は、命令文（let me know など）や will などのふつうの形にします。' },
      { text: 'メールの結びの Should you have any questions, please feel free to contact me.（ご不明な点がございましたら、お気軽にご連絡ください）はよく使います。' },
    ],
    examples: [
      { tatoeba: 322513, en: 'If you should change your mind, let me know.' },
      { tatoeba: 30905, en: 'Should you change your mind, let me know.' },
      { tatoeba: 30607, en: 'If you should need any help, just let me know.' },
      { tatoeba: 322589, en: 'If she should come late, give her this message.' },
      { tatoeba: 30615, en: 'If I should fail, what would my parents say?' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'If you should needed any help, let me know.', right: 'If you should need any help, let me know.', note: 'should の後ろは動詞の原形。', basis: { doc: GP, item: '224', find: 'should V.' }, dict: { lemma: 'need', pos: 'verb', form: 'need', tags: ['infinitive'] } },
    ],
    exercises: [
      { type: 'fill', ja: '万一気が変わったら、知らせてください。', text: 'If you ___ change your mind, let me know.', choices: ['should', 'would', 'shall'], answers: ['should'] },
      { type: 'fill', ja: '万一気が変わったら、知らせてください。（If を使わずに）', text: '___ you change your mind, let me know.', choices: ['Should', 'Would', 'Do'], answers: ['Should'] },
      { type: 'order', ja: 'もし手伝いが必要なら、知らせてください。', tokens: ['If', 'you', 'should', 'need', 'any', 'help', 'just', 'let', 'me', 'know'], answers: ['If you should need any help, just let me know.'] },
      { type: 'order', ja: '万一彼女が遅れて来たら、この伝言を渡してください。', tokens: ['If', 'she', 'should', 'come', 'late', 'give', 'her', 'this', 'message'], answers: ['If she should come late, give her this message.'] },
      { type: 'rewrite', ja: 'Should で始めて書き直す。', from: 'If you have any questions, please contact me.', answers: ['Should you have any questions, please contact me.', 'Should you have any questions, please feel free to contact me.'] },
      { type: 'rewrite', ja: 'If 〜 should を使って「万一〜なら」にする。', from: 'If it rains tomorrow, we will cancel the event.', answers: ['If it should rain tomorrow, we will cancel the event.'] },
      { type: 'oral', ja: 'ご不明な点がございましたら、お気軽にご連絡ください。', answers: ['Should you have any questions, please feel free to contact me.', 'Should you have any questions, please contact me.', 'If you should have any questions, please feel free to contact me.'] },
      { type: 'oral', ja: '万一遅れる場合は、お電話ください。', answers: ['Should you be late, please call me.', 'If you should be late, please call me.', 'Should you be late, please give me a call.'] },
      { type: 'oral', ja: '万一その件で問題があれば、お知らせください。', answers: ['Should there be any problems, please let me know.', 'If there should be any problems, please let me know.', 'Should there be any problem, please let me know.'] },
    ],
    myself: {
      task: 'Should you 〜, please … で、ビジネスメールの結びの1文を作ってみましょう。',
      samples: ['Should you need more information, please let me know.', 'Should you have any concerns, please feel free to contact me.'],
      checks: ['Should の後ろは「主語＋動詞の原形」にした'],
    },
  },
  {
    id: 'c21',
    title: '「〜がなければ」（if it were not for・without）',
    stage: 'CEFR B2：かたい書き言葉',
    sources: [{ doc: GP, where: '項目 228 if it were not for …・230 if it hadn’t been for …　CEFR-J レベル B2.2' }],
    points: [
      { text: 'if it were not for 〜 は「（今）〜がなければ」。後ろは would＋原形（仮定法過去。修行場44）。', en: ['What do you think would happen if it were not for books?'] },
      { text: 'if it had not been for 〜 は「（あの時）〜がなかったら」。後ろは would have＋過去分詞（仮定法過去完了。修行場61）。' },
      { text: '話すときは without 〜 のほうがよく使われます。without は今のことにも過去のことにも使えます。', en: ["I couldn't have done it without your help."] },
      { text: '感謝を伝えるときに便利です（Without your support, this project would not have succeeded.）。' },
    ],
    examples: [
      { tatoeba: 30761, en: 'What do you think would happen if it were not for books?' },
      { tatoeba: 9987553, en: "Would you still be studying Japanese if it weren't for anime?" },
      { tatoeba: 4772510, en: "I couldn't have done it without your help." },
      { tatoeba: 10290195, en: "I don't think I could've done it without your help." },
      { tatoeba: 3241557, en: "I don't think I can do this without your help." },
    ],
    mistakes: [
      { kind: 'meaning', wrong: 'If it were not for your help, I would fail.', intended: '（あの時）あなたの助けがなかったら、失敗していた', right: 'If it had not been for your help, I would have failed.', note: 'if it were not for は「今〜がなければ」。過去のことは if it had not been for 〜, would have＋過去分詞。', work: 'どちらも正しい英語。かたい言い方なので、話すときは Without your help, I would have failed. が自然。' },
    ],
    exercises: [
      { type: 'fill', ja: '本がなければ、どうなると思いますか。', text: 'What do you think would happen if it ___ not for books?', choices: ['were', 'is', 'had'], answers: ['were'] },
      { type: 'fill', ja: 'あなたの助けがなければ、それはできなかったでしょう。', text: "I couldn't have done it ___ your help.", choices: ['without', 'except', 'unless'], answers: ['without'] },
      { type: 'order', ja: 'あなたの助けがなかったら、失敗していただろう。', tokens: ['If', 'it', 'had', 'not', 'been', 'for', 'your', 'help', 'I', 'would', 'have', 'failed'], answers: ['If it had not been for your help, I would have failed.', 'I would have failed if it had not been for your help.'] },
      { type: 'order', ja: '水がなければ、何も生きられない。', tokens: ['If', 'it', 'were', 'not', 'for', 'water', 'nothing', 'could', 'live'], answers: ['If it were not for water, nothing could live.', 'Nothing could live if it were not for water.'] },
      { type: 'rewrite', ja: 'without を使って書き直す。', from: 'If it had not been for your support, I would have given up.', answers: ['Without your support, I would have given up.', 'I would have given up without your support.'] },
      { type: 'rewrite', ja: 'If it were not for で始めて書き直す。', from: 'Without the internet, our work would be difficult.', answers: ['If it were not for the internet, our work would be difficult.'] },
      { type: 'oral', ja: '皆さんの協力がなければ、このプロジェクトは成功しなかったでしょう。', answers: ['Without your cooperation, this project would not have succeeded.', "Without your cooperation, this project wouldn't have succeeded.", 'Without your help, this project would not have succeeded.'] },
      { type: 'oral', ja: 'あなたがいなかったら、できなかったと思う。', answers: ["I don't think I could have done it without you.", "I couldn't have done it without you."] },
      { type: 'oral', ja: 'スマホがなければ、生活はもっと不便だろう。', answers: ['Without smartphones, life would be more inconvenient.', 'If it were not for smartphones, life would be more inconvenient.', 'Without smartphones, our lives would be more inconvenient.'] },
    ],
    myself: {
      task: 'Without 〜, I would (not) have … で、助けてくれた人やものへの感謝を1文で言ってみましょう。',
      samples: ['Without my teacher, I would not have passed the exam.', "Without my family's support, I couldn't have continued studying."],
      checks: ['今のことは would＋原形、過去のことは would have＋過去分詞にした'],
    },
  },
  {
    id: 'c22',
    title: '「たぶん〜だろう」「〜するのももっともだ」（may well・might well）',
    stage: 'CEFR B2：かたい書き言葉',
    sources: [{ doc: GP, where: '項目 131 may well（B2.2）・134 might well（B2.1）' }],
    points: [
      { text: 'may well＋動詞の原形は「たぶん〜だろう」。may だけより、そうなる見込みが高いと考えていることを表します。', en: ['It may well be true.', 'It may well rain before tonight.'] },
      { text: '「〜するのももっともだ」の意味にもなります。どちらの意味かは前後の内容で判断します。', en: ['He may well be proud of his daughter.'] },
      { text: 'might well も同じように使えます（少し控えめ）。' },
      { text: '仕事では、見通しを控えめに、でも根拠を持って伝えるときに使います（Sales may well increase next year.）。' },
    ],
    examples: [
      { tatoeba: 42251, en: 'It may well be true.' },
      { tatoeba: 40580, en: 'He may well be right.' },
      { tatoeba: 50104, en: 'The news may well be true.' },
      { tatoeba: 282824, en: 'It may well rain before tonight.' },
      { tatoeba: 56903, en: 'This book may well be useful to you.' },
      { tatoeba: 283799, en: 'He may well be proud of his daughter.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'It may well to be true.', right: 'It may well be true.', note: 'may well の後ろは to を付けずに動詞の原形。', basis: { doc: GP, item: '131', find: 'well V.' }, dict: { lemma: 'be', pos: 'verb', form: 'be', tags: ['infinitive'] } },
    ],
    exercises: [
      { type: 'fill', ja: 'それはたぶん本当だろう。', text: 'It may ___ be true.', choices: ['well', 'good', 'better'], answers: ['well'] },
      { type: 'fill', ja: '夜になる前に雨になりそうだ。', text: 'It may well ___ before tonight.', choices: ['rain', 'to rain', 'rains'], answers: ['rain'] },
      { type: 'order', ja: 'たぶん彼の言うことは正しいだろう。', tokens: ['He', 'may', 'well', 'be', 'right'], answers: ['He may well be right.'] },
      { type: 'order', ja: 'この本はたぶん君の役に立つだろう。', tokens: ['This', 'book', 'may', 'well', 'be', 'useful', 'to', 'you'], answers: ['This book may well be useful to you.'] },
      { type: 'rewrite', ja: 'may well を使って書き直す。', from: 'The rumor is probably true.', answers: ['The rumor may well be true.'] },
      { type: 'rewrite', ja: 'may well を使って「〜するのももっともだ」にする。', from: 'It is natural that he is angry.', answers: ['He may well be angry.'] },
      { type: 'oral', ja: '来年は売り上げがたぶん伸びるでしょう。', answers: ['Sales may well increase next year.', 'Sales may well go up next year.'] },
      { type: 'oral', ja: '彼の言う通りかもしれない（たぶんそうだ）。', answers: ['He may well be right.', 'He might well be right.'] },
      { type: 'oral', ja: 'その会議はたぶん長引くでしょう。', answers: ['The meeting may well run long.', 'The meeting may well take a long time.', 'The meeting may well go on for a long time.'] },
    ],
    myself: {
      task: 'may well で、仕事や世の中の見通しを1文で言ってみましょう。',
      samples: ['Remote work may well become even more common.', 'Prices may well go up next year.'],
      checks: ['may well の後ろは to を付けずに原形にした'],
    },
  },
  {
    id: 'c23',
    title: '否定の語で始める倒置（Never have I 〜・Rarely do I 〜）',
    stage: 'CEFR B2：かたい書き言葉',
    sources: [{ doc: GP, where: '項目 234 倒置（Never / No sooner / Hardly / Little / Scarcely / Seldom …）　CEFR-J レベル B1.1〜B2.2' }],
    points: [
      { text: 'never・rarely・seldom・little などの否定の語を文の始めに置くと、その後ろは疑問文と同じ語順になります（倒置）。', en: ['Never have I heard such beautiful music.'] },
      { text: '一般動詞の文では do・does・did を使います。', en: ['Rarely do I listen to the radio.', 'Never did I dream of meeting you here.'] },
      { text: '強い感情や驚きを表す、かたい言い方です。ふつうの会話では I have never 〜 のような語順を使います。' },
      { text: 'スピーチや文章で印象を強めたいときに使います（Never have we seen such strong results.）。' },
    ],
    examples: [
      { tatoeba: 241870, en: 'Never have I heard such beautiful music.' },
      { tatoeba: 71221, en: 'Never have I dreamed of marrying you.' },
      { tatoeba: 280972, en: 'Never will I see her again.' },
      { tatoeba: 49827, en: 'Never did I dream of such a thing.' },
      { tatoeba: 31792, en: 'Rarely does he go out on Sunday.' },
      { tatoeba: 255726, en: 'Rarely do I listen to the radio.' },
    ],
    mistakes: [],
    exercises: [
      { type: 'fill', ja: '今までにそんな美しい音楽を聞いたことがない。', text: 'Never ___ I heard such beautiful music.', choices: ['have', 'I', 'did'], answers: ['have'] },
      { type: 'fill', ja: '私はめったにラジオを聞かない。', text: 'Rarely ___ I listen to the radio.', choices: ['do', 'am', 'have'], answers: ['do'] },
      { type: 'order', ja: '彼女には二度と会わないだろう。', tokens: ['Never', 'will', 'I', 'see', 'her', 'again'], answers: ['Never will I see her again.'] },
      { type: 'order', ja: '彼はめったに日曜日に外出しない。', tokens: ['Rarely', 'does', 'he', 'go', 'out', 'on', 'Sunday'], answers: ['Rarely does he go out on Sunday.'] },
      { type: 'rewrite', ja: 'Never で始めて倒置にする。', from: 'I have never seen such a big city.', answers: ['Never have I seen such a big city.'] },
      { type: 'rewrite', ja: 'Rarely で始めて倒置にする。', from: 'He rarely makes mistakes.', answers: ['Rarely does he make mistakes.'] },
      { type: 'oral', ja: 'こんなに良い結果は見たことがありません。（強く）', answers: ['Never have I seen such good results.', 'Never have we seen such good results.', 'Never have I seen such great results.'] },
      { type: 'oral', ja: 'ここで会うとは夢にも思わなかった。（強く）', answers: ['Never did I dream of meeting you here.', 'Never did I think I would meet you here.'] },
      { type: 'oral', ja: '彼はめったに遅刻しない。（強く）', answers: ['Rarely is he late.', 'Rarely does he come late.', 'Seldom is he late.'] },
    ],
    myself: {
      task: 'Never have I 〜 で、強く印象に残った経験を1文で書いてみましょう（スピーチや文章の練習）。',
      samples: ['Never have I worked with such a great team.', 'Never have I been so nervous as on my first day at work.'],
      checks: ['否定の語の後ろを疑問文と同じ語順にした（Never have I …）'],
    },
  },
]
