// 文法（フェーズ11）の中身：修行場65〜69（CEFR B1：会話でよく使う形）。書き方は items-01-05.mjs の先頭を参照。
// 高校までの64項目にない文法を、CEFR-J Grammar Profile（教員版のレベル）の順に加える。学習指導要領の範囲外なので、
// ✕（解説と辞書の両方で確かめる）は使わず、△「意味が違う」だけを載せる（✕ の扱いは利用者に確認中）。
// sources の page は学習指導要領解説の頁のときだけ付ける（CEFR-J は項目番号とレベルを where に書く）。
const GP = 'CEFR-J Grammar Profile 2025（東京外国語大学 投野由紀夫研究室）'

export default [
  {
    id: 'c01',
    title: '付加疑問（〜ですよね？：…, isn’t it?・…, don’t you?）',
    stage: 'CEFR B1：会話でよく使う形',
    sources: [{ doc: GP, where: '項目 193 付加疑問（肯定文に続くもの）・193-1（否定文に続くもの）　CEFR-J レベル B1.1' }],
    points: [
      { text: '文の終わりに短い疑問を付けて「〜ですよね？」と確かめたり、同意を求めたりします。', en: ["It's cheap, isn't it?"] },
      { text: '肯定の文には否定の付加疑問、否定の文には肯定の付加疑問を付けます。', en: ["You understand, don't you?", "You aren't busy, are you?"] },
      { text: '付加疑問の動詞は、前の文に合わせます。be動詞なら be動詞、一般動詞なら do・does・did、助動詞ならその助動詞。主語は代名詞にします。', en: ['You lost, didn\'t you?'] },
      { text: '答え方は、内容が肯定なら Yes、否定なら No（修行場4と同じ）。「好きじゃないよね？」に「好きじゃない」と答えるなら No です。' },
      { text: '命令文の後ろの , will you? は「〜してくれる？」という頼み方になります。', en: ['Shut the door, will you?'] },
    ],
    examples: [
      { tatoeba: 645084, en: "That's cheap, isn't it?" },
      { tatoeba: 51844, en: "Beautiful day, isn't it?" },
      { tatoeba: 433503, en: "You understand, don't you?" },
      { tatoeba: 1014803, en: "You lost, didn't you?" },
      { tatoeba: 68947, en: "You aren't busy, are you?" },
      { tatoeba: 69897, en: "You don't smoke, do you?" },
      { tatoeba: 39031, en: 'Shut the door, will you?' },
    ],
    mistakes: [
      { kind: 'meaning', wrong: '"You don\'t smoke, do you?" "Yes."', intended: '「タバコは吸わないんですよね？」「はい、吸いません」', right: '"You don\'t smoke, do you?" "No, I don\'t."', note: 'Yes と答えると「いいえ、吸います」の意味になる。吸わないなら No。' },
    ],
    exercises: [
      { type: 'fill', ja: 'それは安いですよね。', text: "That's cheap, ___ it?", choices: ["isn't", "doesn't", 'is'], answers: ["isn't"] },
      { type: 'fill', ja: '分かりますよね。', text: "You understand, ___ you?", choices: ["don't", "aren't", 'do'], answers: ["don't"] },
      { type: 'fill', ja: 'お忙しくないですよね。', text: "You aren't busy, ___ you?", choices: ['are', "aren't", 'do'], answers: ['are'] },
      { type: 'order', ja: 'あなたは負けたんですよね。', tokens: ['You', 'lost', "didn't", 'you'], answers: ["You lost, didn't you?"] },
      { type: 'order', ja: 'ドアを閉めてくれる？', tokens: ['Shut', 'the', 'door', 'will', 'you'], answers: ['Shut the door, will you?'] },
      { type: 'rewrite', ja: '付加疑問を付けて「〜ですよね？」にする。', from: 'He is your boss.', answers: ["He is your boss, isn't he?", "He's your boss, isn't he?"] },
      { type: 'rewrite', ja: '付加疑問を付けて「〜ですよね？」にする。', from: "She can't come.", answers: ["She can't come, can she?"] },
      { type: 'oral', ja: '会議は3時からですよね。', answers: ["The meeting starts at three, doesn't it?", "The meeting is at three, isn't it?"] },
      { type: 'oral', ja: 'いい天気ですね。', answers: ["It's a beautiful day, isn't it?", "It's a nice day, isn't it?", "Beautiful day, isn't it?", "Nice weather, isn't it?"] },
      { type: 'oral', ja: 'あなたは昨日来なかったですよね。', answers: ["You didn't come yesterday, did you?"] },
      { type: 'oral', ja: '彼はまだ報告書を送っていないですよね。', answers: ["He hasn't sent the report yet, has he?"] },
    ],
    myself: {
      task: '付加疑問を使って、相手に確かめたいことを1文で言ってみましょう。',
      samples: ["You're coming to the meeting, aren't you?", "We don't need to finish it today, do we?"],
      checks: ['肯定の文には否定の、否定の文には肯定の付加疑問を付けた', '付加疑問の動詞を前の文に合わせた（be動詞・do・助動詞）'],
    },
  },
  {
    id: 'c02',
    title: '「私もです」（So do I.・Neither do I.）',
    stage: 'CEFR B1：会話でよく使う形',
    sources: [{ doc: GP, where: '項目 232 倒置（so＋be/have/do/助動詞＋人称代名詞）・233（neither/nor＋…）　CEFR-J レベル B1.1〜B2.2' }],
    points: [
      { text: '相手の肯定の文に「私もです」は So＋動詞＋I。', en: ['"I agree with him." "So do I."'] },
      { text: '相手の否定の文に「私も（〜ない）です」は Neither＋動詞＋I。', en: ['"I don\'t like carrots." "Neither do I."'] },
      { text: '動詞は相手の文に合わせます。be動詞なら am・was、一般動詞なら do・does・did、現在完了なら have、助動詞ならその助動詞。', en: ['"I am a teacher." "So am I."', '"I\'ve seen that play." "So have I."'] },
      { text: 'くだけた会話では Me too.（肯定に）・Me neither.（否定に）とも言います。否定の文に Me too. と返すと、話がかみ合わなくなります。' },
    ],
    examples: [
      { tatoeba: 73658, en: '"I agree with him." "So do I."' },
      { tatoeba: 1520, en: '"She likes music." "So do I."' },
      { tatoeba: 256930, en: '"I am a teacher." "So am I."' },
      { tatoeba: 73667, en: '"I\'ve seen that play." "So have I."' },
      { tatoeba: 73681, en: '"I don\'t like carrots." "Neither do I."' },
      { tatoeba: 261407, en: '"I am not tired." "Neither am I."' },
      { tatoeba: 11358651, en: '"I don\'t understand this." "Neither do I."' },
    ],
    mistakes: [
      { kind: 'meaning', wrong: '"I don\'t like coffee." "Me too."', intended: '「コーヒーは好きじゃない」「私も（好きじゃない）」', right: '"I don\'t like coffee." "Neither do I."', note: 'Me too. は肯定の文への返事。否定の文に「私も〜ない」と返すときは Neither do I.（くだけて Me neither.）。' },
    ],
    exercises: [
      { type: 'fill', ja: '「彼に賛成です」「私もです」', text: '"I agree with him." "So ___ I."', choices: ['do', 'am', 'have'], answers: ['do'] },
      { type: 'fill', ja: '「私は疲れていません」「私もです」', text: '"I am not tired." "___ am I."', choices: ['Neither', 'So', 'Too'], answers: ['Neither'] },
      { type: 'fill', ja: '「その劇を見たことがあります」「私もあります」', text: '"I\'ve seen that play." "So ___ I."', choices: ['have', 'do', 'am'], answers: ['have'] },
      { type: 'order', ja: '「これが分かりません」への返事：「私もです」', tokens: ['Neither', 'do', 'I'], answers: ['Neither do I.'] },
      { type: 'order', ja: '「私は教師です」への返事：「私もです」', tokens: ['So', 'am', 'I'], answers: ['So am I.'] },
      { type: 'rewrite', ja: '「私もです」を So か Neither で返す。', from: 'I can swim.', answers: ['So can I.'] },
      { type: 'rewrite', ja: '「私もです」を So か Neither で返す。', from: "I didn't go to the party.", answers: ['Neither did I.', 'Nor did I.'] },
      { type: 'oral', ja: '「その案はいいと思います」「私もです」の「私もです」', answers: ['So do I.', 'Me too.'] },
      { type: 'oral', ja: '「まだ終わっていません」「私もです」の「私もです」', answers: ['Neither have I.', 'Me neither.', 'Nor have I.'] },
      { type: 'oral', ja: '「昨日は忙しかった」「私もです」の「私もです」', answers: ['So was I.', 'Me too.'] },
    ],
    myself: {
      task: '同僚の発言「I want to take a vacation.」か「I don’t like long meetings.」に、So か Neither で返してみましょう。',
      samples: ['So do I.', 'Neither do I.'],
      checks: ['肯定の文には So、否定の文には Neither を使った', '動詞を相手の文に合わせた'],
    },
  },
  {
    id: 'c03',
    title: '「以前は〜だった」（used to 〜）',
    stage: 'CEFR B1：会話でよく使う形',
    sources: [{ doc: GP, where: '項目 140 助動詞：used to　CEFR-J レベル B1.1' }],
    points: [
      { text: 'used to＋動詞の原形で「以前は〜していた（今はしていない）」「以前は〜だった」。', en: ['I used to work here.', 'I used to be a teacher.'] },
      { text: '今と比べて「昔はそうだった」ということを表します。過去形（I worked here.）は、今どうかには触れません。' },
      { text: '否定は didn’t use to 〜、疑問は Did you use to 〜?（did の後ろは use）。', en: ["I didn't use to smoke.", 'Did you use to live here?'] },
      { text: 'be used to 〜ing（〜に慣れている）とは別の言い方です。be動詞があるかどうかで区別します。' },
    ],
    examples: [
      { tatoeba: 5958281, en: 'I used to work here.' },
      { tatoeba: 2546806, en: 'I used to be a teacher.' },
      { tatoeba: 11188098, en: 'I used to live in this house.' },
      { tatoeba: 10970940, en: 'I used to go skiing a lot.' },
      { tatoeba: 28339, en: "I didn't use to smoke." },
      { tatoeba: 61826, en: 'Did you use to live here?' },
      { tatoeba: 2825471, en: "He didn't use to be like that." },
    ],
    mistakes: [
      { kind: 'meaning', wrong: "I'm used to getting up early.", intended: '以前は早起きだった（今はちがう）', right: 'I used to get up early.', note: 'be used to 〜ing は「〜に慣れている」。「以前は〜していた」は used to＋動詞の原形（be動詞なし）。' },
    ],
    exercises: [
      { type: 'fill', ja: '以前はここで働いていました。', text: 'I ___ to work here.', choices: ['used', 'use', 'was used'], answers: ['used'] },
      { type: 'fill', ja: '以前はタバコを吸わなかった。', text: "I didn't ___ to smoke.", choices: ['use', 'used', 'using'], answers: ['use'] },
      { type: 'order', ja: '以前は教師でした。', tokens: ['I', 'used', 'to', 'be', 'a', 'teacher'], answers: ['I used to be a teacher.'] },
      { type: 'order', ja: '以前ここに住んでいたのですか。', tokens: ['Did', 'you', 'use', 'to', 'live', 'here'], answers: ['Did you use to live here?'] },
      { type: 'rewrite', ja: 'used to を使って1文にする。', from: "I played tennis a lot. I don't play now.", answers: ['I used to play tennis a lot.'] },
      { type: 'rewrite', ja: 'used to を使って1文にする。', from: "He was shy before. He isn't shy now.", answers: ['He used to be shy.'] },
      { type: 'oral', ja: '以前は大阪に住んでいました。', answers: ['I used to live in Osaka.'] },
      { type: 'oral', ja: '以前は英語が苦手でした。', answers: ['I used to be bad at English.', "I used to be poor at English.", "I used to be weak in English."] },
      { type: 'oral', ja: 'この店は以前、もっと混んでいた。', answers: ['This shop used to be more crowded.', 'This store used to be more crowded.', 'This shop used to be busier.', 'This store used to be busier.'] },
    ],
    myself: {
      task: 'used to で、昔の自分と今の自分の違いを1文で言ってみましょう。',
      samples: ['I used to hate speaking English.', "I used to play soccer, but now I don't have time."],
      checks: ['used to の後ろは動詞の原形にした', 'be動詞を付けなかった（be used to 〜ing と区別した）'],
    },
  },
  {
    id: 'c04',
    title: '「…すぎて〜できない」「とても…なので〜」（too … to・so … that・enough）',
    stage: 'CEFR B1：会話でよく使う形',
    sources: [
      { doc: GP, where: '項目 44 too＋形容詞・副詞＋to 不定詞（B1.1）・45 so＋形容詞・副詞＋(that) 節（B1.1）・46 such (a/an)＋形容詞＋名詞（B1.2）・43 形容詞・副詞＋enough（B1.2）' },
    ],
    points: [
      { text: 'too＋形容詞＋to 〜 は「…すぎて〜できない」。', en: ["I'm too tired to walk."] },
      { text: 'so＋形容詞＋that 〜 は「とても…なので〜」。that の後ろは「主語＋動詞」。', en: ["It was so cold that I couldn't sleep."] },
      { text: '名詞が入るときは such a＋形容詞＋名詞＋that 〜。', en: ['It was such a hot day that we went swimming.'] },
      { text: '形容詞＋enough to 〜 は「〜できるほど十分…」。enough は形容詞の後ろに置きます。', en: ["It's warm enough to swim."] },
      { text: 'too には「…すぎる（よくない）」という意味があります。ただ「とても」と言いたいときは very を使います。' },
    ],
    examples: [
      { tatoeba: 252981, en: "I'm too tired to walk." },
      { tatoeba: 508781, en: "I'm too busy to go." },
      { tatoeba: 6553420, en: "It's too dark to see." },
      { tatoeba: 37816, en: "It was so cold that I couldn't sleep." },
      { tatoeba: 26461, en: 'The movie was so sad that everybody cried.' },
      { tatoeba: 37795, en: 'It was such a hot day that we went swimming.' },
      { tatoeba: 26401, en: "It's warm enough to swim." },
    ],
    mistakes: [
      { kind: 'meaning', wrong: 'This bag is too heavy.', intended: 'このかばんはとても重い（けれど持てる）', right: 'This bag is very heavy.', note: 'too heavy は「重すぎる（持てない・よくない）」。ただ「とても重い」なら very。' },
    ],
    exercises: [
      { type: 'fill', ja: '疲れすぎて歩けない。', text: "I'm ___ tired to walk.", choices: ['too', 'so', 'very'], answers: ['too'] },
      { type: 'fill', ja: 'とても寒かったので眠れなかった。', text: "It was ___ cold that I couldn't sleep.", choices: ['so', 'too', 'such'], answers: ['so'] },
      { type: 'fill', ja: '泳げるほど暖かい。', text: "It's warm ___ to swim.", choices: ['enough', 'too', 'so'], answers: ['enough'] },
      { type: 'order', ja: '忙しすぎて行けない。', tokens: ["I'm", 'too', 'busy', 'to', 'go'], answers: ["I'm too busy to go."] },
      { type: 'order', ja: 'とても暑い日だったので、泳ぎに行った。', tokens: ['It', 'was', 'such', 'a', 'hot', 'day', 'that', 'we', 'went', 'swimming'], answers: ['It was such a hot day that we went swimming.'] },
      { type: 'rewrite', ja: 'too … to を使って1文にする。', from: "It's very dark. I can't see.", answers: ["It's too dark to see.", 'It is too dark to see.', "It's too dark for me to see."] },
      { type: 'rewrite', ja: 'so … that を使って1文にする。', from: 'The movie was very sad. Everybody cried.', answers: ['The movie was so sad that everybody cried.'] },
      { type: 'oral', ja: '忙しすぎてお昼を食べられなかった。', answers: ['I was too busy to eat lunch.', 'I was too busy to have lunch.'] },
      { type: 'oral', ja: 'とても疲れていたので、すぐに寝た。', answers: ['I was so tired that I went to bed soon.', 'I was so tired that I went to bed early.', 'I was so tired that I went to sleep right away.'] },
      { type: 'oral', ja: 'この部屋は会議ができるほど広い。', answers: ['This room is big enough for a meeting.', 'This room is large enough for a meeting.', 'This room is big enough to have a meeting in.'] },
    ],
    myself: {
      task: 'too … to か so … that で、最近の自分のことを1文で言ってみましょう。',
      samples: ['I was too sleepy to study last night.', 'The meeting was so long that I got tired.'],
      checks: ['「…すぎて〜できない」は too … to にした', 'so … that の後ろは「主語＋動詞」にした'],
    },
  },
  {
    id: 'c05',
    title: '比較の強調と変化（much better・more and more・less）',
    stage: 'CEFR B1：会話でよく使う形',
    sources: [{ doc: GP, where: '項目 51 比較級の強調（much/far/even/a lot＋比較級）・49 比較級 and 比較級・42 less＋形容詞・副詞　CEFR-J レベル B1.1' }],
    points: [
      { text: '比較級を強めて「ずっと〜」は much・a lot・far＋比較級。very は使いません。', en: ['I feel much better today.'] },
      { text: 'even＋比較級は「さらに〜」。', en: ['She is even more beautiful.'] },
      { text: '比較級 and 比較級で「ますます〜」。more を使う語は more and more＋形容詞。', en: ["It's getting colder and colder.", 'He became more and more famous.'] },
      { text: 'less＋形容詞は「より〜でない」。店で「もっと安いもの」を頼むときにも使えます。', en: ['Do you have anything less expensive?'] },
    ],
    examples: [
      { tatoeba: 242702, en: 'I feel much better today.' },
      { tatoeba: 273618, en: 'You look much better.' },
      { tatoeba: 1442227, en: "She's a lot better today." },
      { tatoeba: 310885, en: 'She is even more beautiful.' },
      { tatoeba: 40299, en: "It's getting colder and colder." },
      { tatoeba: 292815, en: 'He became more and more famous.' },
      { tatoeba: 30478, en: 'Do you have anything less expensive?' },
    ],
    mistakes: [],
    exercises: [
      { type: 'fill', ja: '今日はずっと気分がいい。', text: 'I feel ___ better today.', choices: ['much', 'very', 'more'], answers: ['much'] },
      { type: 'fill', ja: 'ますます寒くなってきている。', text: "It's getting colder and ___.", choices: ['colder', 'cold', 'coldest'], answers: ['colder'] },
      { type: 'fill', ja: 'もっと安いものはありますか。', text: 'Do you have anything ___ expensive?', choices: ['less', 'least', 'fewer'], answers: ['less'] },
      { type: 'order', ja: '彼はますます有名になった。', tokens: ['He', 'became', 'more', 'and', 'more', 'famous'], answers: ['He became more and more famous.'] },
      { type: 'order', ja: '彼女はさらに美しい。', tokens: ['She', 'is', 'even', 'more', 'beautiful'], answers: ['She is even more beautiful.'] },
      { type: 'rewrite', ja: 'much を加えて「ずっと〜」にする。', from: 'This plan is better.', answers: ['This plan is much better.'] },
      { type: 'rewrite', ja: '比較級 and 比較級で「ますます〜」にする。', from: 'English is getting important.', answers: ['English is getting more and more important.'] },
      { type: 'oral', ja: '新しいやり方のほうがずっと速い。', answers: ['The new way is much faster.', 'The new method is much faster.', 'The new way is a lot faster.'] },
      { type: 'oral', ja: '仕事がますます忙しくなっている。', answers: ['Work is getting busier and busier.', 'My work is getting busier and busier.', "I'm getting busier and busier at work."] },
      { type: 'oral', ja: 'この問題は思ったより、ずっと簡単だった。', answers: ['This problem was much easier than I thought.', 'This problem was a lot easier than I thought.', 'This problem was much easier than I expected.'] },
    ],
    myself: {
      task: 'much＋比較級か「比較級 and 比較級」で、自分の変化を1文で言ってみましょう。',
      samples: ['My English is getting better and better.', 'I feel much more confident now.'],
      checks: ['比較級を強めるとき very ではなく much・a lot を使った'],
    },
  },
]
