// 文法（フェーズ9）の中身：修行場1〜5（小学校の復習）。解説・問題は自作（学習指導要領解説と照らし合わせ、文章は写さない）。
// 書き方（scripts/grammar/build.mjs が確かめて public/data/grammar.json を作る）：
// - sources：学習指導要領解説の該当箇所（印刷された頁）
// - points：解説。check: true は確信が持てない説明（要確認。初期設定では表示しない）
// - examples：tatoeba は Tatoeba の文の番号と英文（番号と英文が一致するか確かめる）。self は自作（LanguageTool に通す）
// - mistakes：error は文法として誤り（✕。LanguageTool が誤りと判定し、かつ dict の形が Wiktionary にあることを確かめる）、
//             meaning は文法的には正しいが言いたいことと意味が違う（△）
// - exercises：fill（穴埋め。choices から選ぶ）、order（並べ替え。answers は認める語順をすべて）、
//              rewrite（言い換え。answers は認める答えをすべて）、oral（口頭で即答。answers は手本）。各項目の最後は oral
// - myself：その文法を使って自分のことを1文言う課題
const 小 = '小学校学習指導要領（平成29年告示）解説 外国語活動・外国語編'
const 中 = '中学校学習指導要領（平成29年告示）解説 外国語編'

export default [
  {
    id: 'g01',
    title: 'be動詞（am・are・is）',
    stage: '小学校の復習',
    sources: [
      { doc: 小, where: '第2部第2章第2節 2(1)エ（ｲ）b［主語＋be動詞＋補語］', page: '96〜97' },
      { doc: 小, where: '第2部第2章第2節 2(1)エ（ｱ）b 肯定，否定の平叙文', page: '93' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｲ）a［主語＋動詞＋補語］（小学校の例文）', page: '40' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）d 前置詞（出身 I’m from Japan.）、e〈現在形〉', page: '46' },
    ],
    points: [
      { text: '「AはBです」「Aは〜な状態です」は、主語のあとに be動詞を置き、その後ろに名詞や形容詞を続けます。', en: ['I am a teacher.', 'I am busy.'] },
      { text: '主語で形が決まります。I は am、you と複数（we、they、2人以上・2つ以上のもの）は are、それ以外の1人・1つ（he、she、it、Tom、my father など）は is。' },
      { text: '話すときは短い形をよく使います：I’m、you’re、he’s、she’s、it’s、we’re、they’re。' },
      { text: 'be動詞の後ろに場所を表す語句を続けると「〜にいる・ある」。出身は from を使います。', en: ['I’m in Tokyo.', 'I’m from Japan.'] },
      { text: '職業など数えられる名詞が1人・1つのときは a（母音の音で始まる語の前は an）を付けます。', en: ['I’m a nurse.', 'I’m an engineer.'] },
      { text: '「住んでいる」「好きだ」のような動作や気持ちは、be動詞ではなく一般動詞で表します（修行場2）。' },
    ],
    examples: [
      { tatoeba: 256929, en: "I'm a teacher." },
      { tatoeba: 397588, en: "I'm an engineer." },
      { tatoeba: 253217, en: "I'm from Australia." },
      { tatoeba: 241566, en: "I'm busy now." },
      { tatoeba: 371410, en: 'He is sick.' },
      { tatoeba: 247930, en: 'We are hungry.' },
      { tatoeba: 26044, en: 'The station is nearby.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'She are a teacher.', right: 'She is a teacher.', note: 'she（1人）には is を使う。', dict: { lemma: 'be', pos: 'verb', form: 'is', tags: ['third-person', 'singular', 'present'] } },
      { kind: 'error', wrong: 'We is hungry.', right: 'We are hungry.', note: 'we（複数）には are を使う。', dict: { lemma: 'be', pos: 'verb', form: 'are', tags: ['plural', 'present'] } },
      { kind: 'meaning', wrong: "I'm in Tokyo.", intended: '東京に住んでいます', right: 'I live in Tokyo.', note: 'I’m in Tokyo. は「今、東京にいます」。住んでいることは一般動詞 live で言う。' },
    ],
    exercises: [
      { type: 'fill', ja: '私は学生です。', text: 'I ___ a student.', choices: ['am', 'are', 'is'], answers: ['am'] },
      { type: 'fill', ja: '姉は看護師です。', text: 'My sister ___ a nurse.', choices: ['am', 'are', 'is'], answers: ['is'] },
      { type: 'fill', ja: 'トムと私は今日忙しい。', text: 'Tom and I ___ busy today.', choices: ['am', 'are', 'is'], answers: ['are'] },
      { type: 'order', ja: '私の父は医者です。', tokens: ['My', 'father', 'is', 'a', 'doctor'], answers: ['My father is a doctor.'] },
      { type: 'order', ja: '彼らは今とても忙しい。', tokens: ['They', 'are', 'very', 'busy', 'now'], answers: ['They are very busy now.', 'They are now very busy.', 'Now they are very busy.'] },
      { type: 'rewrite', ja: '主語を He に変えて書き直す（語順はそのまま）。', from: 'I am busy.', answers: ['He is busy.', "He's busy."] },
      { type: 'rewrite', ja: '主語を We に変えて書き直す（語順はそのまま）。', from: "I'm from Japan.", answers: ['We are from Japan.', "We're from Japan."] },
      { type: 'oral', ja: '私は会社員です。', answers: ["I'm an office worker.", "I'm a company employee."] },
      { type: 'oral', ja: '私は今、忙しいです。', answers: ["I'm busy now."] },
      { type: 'oral', ja: '彼女はエンジニアです。', answers: ["She's an engineer."] },
      { type: 'oral', ja: '私たちは今、大阪にいます。', answers: ["We're in Osaka now."] },
    ],
    myself: {
      task: 'be動詞を使って、自分の仕事・立場か、今の状態を1文で言ってみましょう。',
      samples: ["I'm a university student.", "I'm a little tired today."],
      checks: ['主語に合う be動詞（am・are・is）を選んだ', '数えられる名詞1つには a / an を付けた'],
    },
  },
  {
    id: 'g02',
    title: '一般動詞（like・live・play など）',
    stage: '小学校の復習',
    sources: [
      { doc: 小, where: '第2部第2章第2節 2(1)エ（ｲ）a［主語＋動詞］、c［主語＋動詞＋目的語］', page: '96〜97' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｲ）［主語＋動詞］、b［主語＋動詞＋目的語］（小学校の例文）', page: '40〜41' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）e〈現在形〉', page: '46' },
    ],
    points: [
      { text: '「〜する」「〜が好きだ」「〜に住んでいる」などは一般動詞で表します。語順は 主語＋動詞（＋目的語）。', en: ['I like music.', 'I live in Tokyo.'] },
      { text: '日本語と語順が違います。「私は テニスを する」は I play tennis.（動詞のすぐ後ろに「〜を」が来る）。' },
      { text: '現在形は、ふだんの習慣や、いつもそうであることを表します。', en: ['I get up at six.', 'We live in Osaka.'] },
      { text: 'always（いつも）、usually（たいてい）、often（よく）、sometimes（時々）は、ふつう一般動詞の前に置きます。', en: ['I usually walk.'] },
      { text: 'every day、on Sundays のような時を表す語句は、文の終わりに置くことが多いです。' },
      { text: '好きなものの種類を言うときは、数えられる名詞は複数形にします。', en: ['I like dogs.'] },
    ],
    examples: [
      { tatoeba: 259803, en: 'I live in Japan.' },
      { tatoeba: 262302, en: 'I get up at 6:30.' },
      { tatoeba: 253293, en: 'I like tea.' },
      { tatoeba: 247741, en: 'We like music.' },
      { tatoeba: 41158, en: 'I usually walk.' },
      { tatoeba: 34349, en: 'I usually play tennis.' },
      { tatoeba: 15993, en: 'You work hard.' },
    ],
    mistakes: [
      { kind: 'meaning', wrong: 'I like dog.', intended: '犬が好きです', right: 'I like dogs.', note: '好きな動物の種類は複数形で言う。dog を数えない形で使うと「犬の肉」の意味に取られることがある。' },
      { kind: 'meaning', wrong: "I'm playing the piano.", intended: '（趣味で）ピアノを弾きます', right: 'I play the piano.', note: 'I’m playing は「今弾いているところ」（現在進行形。修行場11）。習慣は現在形で言う。' },
    ],
    exercises: [
      { type: 'fill', ja: '私は大阪に住んでいます。', text: 'I ___ in Osaka.', choices: ['live', 'am', 'lives'], answers: ['live'] },
      { type: 'fill', ja: '私たちは学校で英語を勉強します。', text: 'We ___ English at school.', choices: ['study', 'studies', 'are'], answers: ['study'] },
      { type: 'order', ja: '私は毎朝コーヒーを飲みます。', tokens: ['I', 'drink', 'coffee', 'every', 'morning'], answers: ['I drink coffee every morning.', 'Every morning I drink coffee.'] },
      { type: 'order', ja: '私はたいてい7時に起きます。', tokens: ['I', 'usually', 'get', 'up', 'at', 'seven'], answers: ['I usually get up at seven.', 'Usually I get up at seven.', 'I get up at seven usually.'] },
      { type: 'rewrite', ja: 'always（いつも）を入れて書き直す。', from: 'I eat breakfast.', answers: ['I always eat breakfast.'] },
      { type: 'rewrite', ja: 'every Sunday（毎週日曜日に）を加えて書き直す。', from: 'I play tennis.', answers: ['I play tennis every Sunday.', 'Every Sunday I play tennis.'] },
      { type: 'oral', ja: '私は東京に住んでいます。', answers: ['I live in Tokyo.'] },
      { type: 'oral', ja: '私は毎日英語を勉強します。', answers: ['I study English every day.'] },
      { type: 'oral', ja: '私はよく電車で通勤します。', answers: ['I often go to work by train.', 'I often commute by train.'] },
      { type: 'oral', ja: '私はコーヒーが好きです。', answers: ['I like coffee.'] },
    ],
    myself: {
      task: '一般動詞を使って、自分がふだんしていることを1文で言ってみましょう。',
      samples: ['I usually get up at six.', 'I work in sales.'],
      checks: ['動詞を主語のすぐ後ろに置いた', 'always などは動詞の前に置いた'],
    },
  },
  {
    id: 'g03',
    title: '三人称単数（He plays.）',
    stage: '小学校の復習',
    sources: [
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）e 動詞の時制及び相など〈現在形〉', page: '46' },
      { doc: 中, where: '同 e〈過去形〉の説明（主語が三人称単数であっても -s にしない）', page: '47〜48' },
      { doc: 小, where: '第2部第2章第2節 2(1)エ（ｱ）d 疑問文（does で始まる疑問文は小学校では扱わない）', page: '95' },
    ],
    points: [
      { text: '主語が he、she、it や、1人・1つのもの（Tom、my father、the shop など）で、現在の文のとき、一般動詞に -s か -es を付けます。', en: ['He plays soccer.'] },
      { text: 'I と you には付けません。複数（we、they、Tom and Mary など）にも付けません。' },
      { text: '付け方：ふつうは -s（plays、likes）。s、sh、ch、x、o で終わる語は -es（watches、goes）。「子音字＋y」で終わる語は y を i に変えて -es（studies）。' },
      { text: 'have は has、do は does になります。' },
      { text: '過去の文（played など）では -s を付けません。' },
    ],
    examples: [
      { tatoeba: 290024, en: 'He plays soccer.' },
      { tatoeba: 294043, en: 'He speaks English.' },
      { tatoeba: 312405, en: 'She works hard.' },
      { tatoeba: 288241, en: 'He studies Chinese.' },
      { tatoeba: 313002, en: 'She goes to school.' },
      { tatoeba: 278546, en: 'My brother watches television.' },
      { tatoeba: 37185, en: 'Tom likes swimming.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'He play tennis.', right: 'He plays tennis.', note: 'he の現在の文では -s を付ける。', dict: { lemma: 'play', pos: 'verb', form: 'plays', tags: ['third-person', 'singular', 'present'] } },
      { kind: 'error', wrong: 'She have a car.', right: 'She has a car.', note: 'have は has になる。', dict: { lemma: 'have', pos: 'verb', form: 'has', tags: ['third-person', 'singular', 'present'] } },
      { kind: 'error', wrong: 'He studys English.', right: 'He studies English.', note: '「子音字＋y」は y を i に変えて -es。', dict: { lemma: 'study', pos: 'verb', form: 'studies', tags: ['third-person', 'singular', 'present'] } },
      { kind: 'error', wrong: 'He watchs TV every night.', right: 'He watches TV every night.', note: 'ch で終わる語は -es。', dict: { lemma: 'watch', pos: 'verb', form: 'watches', tags: ['third-person', 'singular', 'present'] } },
    ],
    exercises: [
      { type: 'fill', ja: '父は電車で通勤しています。', text: 'My father ___ to work by train.', choices: ['go', 'goes', 'gos'], answers: ['goes'] },
      { type: 'fill', ja: '彼女には子どもが2人います。', text: 'She ___ two children.', choices: ['have', 'has', 'haves'], answers: ['has'] },
      { type: 'fill', ja: 'トムとケンは日曜日にサッカーをします。', text: 'Tom and Ken ___ soccer on Sundays.', choices: ['play', 'plays'], answers: ['play'] },
      { type: 'order', ja: '父は毎朝新聞を読みます。', tokens: ['My', 'father', 'reads', 'the', 'newspaper', 'every', 'morning'], answers: ['My father reads the newspaper every morning.', 'Every morning my father reads the newspaper.'] },
      { type: 'rewrite', ja: '主語を My brother に変えて書き直す（語順はそのまま）。', from: 'I watch TV every night.', answers: ['My brother watches TV every night.'] },
      { type: 'rewrite', ja: '主語を She に変えて書き直す（語順はそのまま）。', from: 'I study English.', answers: ['She studies English.'] },
      { type: 'oral', ja: '彼は英語を話します。', answers: ['He speaks English.'] },
      { type: 'oral', ja: '私の上司は毎朝コーヒーを飲みます。', answers: ['My boss drinks coffee every morning.'] },
      { type: 'oral', ja: '彼女は大阪に住んでいます。', answers: ['She lives in Osaka.'] },
      { type: 'oral', ja: 'その店は9時に開きます。', answers: ['The shop opens at nine.', 'The store opens at nine.'] },
    ],
    myself: {
      task: '家族・同僚・友人の1人について、-s を付けた動詞で1文言ってみましょう。',
      samples: ['My father works at a bank.', 'My sister lives in Osaka.'],
      checks: ['動詞に -s / -es を付けた（have は has）', '主語が複数のときは付けていない'],
    },
  },
  {
    id: 'g04',
    title: '否定文と疑問文（not・Do / Does）',
    stage: '小学校の復習',
    sources: [
      { doc: 小, where: '第2部第2章第2節 2(1)エ（ｱ）b 肯定，否定の平叙文', page: '93' },
      { doc: 小, where: '第2部第2章第2節 2(1)エ（ｱ）d 疑問文（yes-no 疑問文）', page: '94〜95' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｱ）b 疑問文（小学校の例文と平叙文）', page: '37〜39' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）e（否定文や疑問文の場合を含む）', page: '46' },
    ],
    points: [
      { text: 'be動詞の否定文は、be動詞の後ろに not を置きます。短い形：isn’t、aren’t、I’m not。', en: ["I'm not busy.", "She isn't married."] },
      { text: 'be動詞の疑問文は、be動詞を主語の前に出します。答えも be動詞を使います。', en: ['Are you busy?', 'Yes, I am.', "No, I'm not."] },
      { text: '一般動詞の否定文は、動詞の前に don’t（主語が he、she など1人・1つなら doesn’t）。動詞は原形（-s を付けない形）のまま。', en: ["I don't like coffee.", "He doesn't like fish."] },
      { text: '一般動詞の疑問文は、文の初めに Do（主語が1人・1つなら Does）を置き、動詞は原形。答えも do / does を使います。', en: ['Do you like fish?', 'Yes, I do.', "No, he doesn't."] },
      { text: '疑問文は、文の終わりを上げて言うのがふつうです。' },
      { text: 'Yes / No は、答えの内容が肯定か否定かで決めます。否定の形で聞かれても同じで、日本語の「はい・いいえ」と逆になることがあります。', en: ["Don't you like coffee?", "No, I don't."] },
    ],
    examples: [
      { tatoeba: 261730, en: "I'm not busy." },
      { tatoeba: 313424, en: "She isn't married." },
      { tatoeba: 33536, en: "I don't like coffee." },
      { tatoeba: 37243, en: "Tom doesn't like cheese." },
      { tatoeba: 16164, en: 'Are you happy?' },
      { tatoeba: 19349, en: 'Do you like fish?' },
      { tatoeba: 1886024, en: 'Does Tom know?' },
      { tatoeba: 40662, en: "I don't smoke." },
    ],
    mistakes: [
      { kind: 'error', wrong: "He don't like fish.", right: "He doesn't like fish.", note: 'he には doesn’t を使う。', dict: { lemma: 'do', pos: 'verb', form: 'does', tags: ['third-person', 'singular', 'present'] } },
      { kind: 'error', wrong: 'Does she likes tea?', right: 'Does she like tea?', note: 'Does の文では動詞は原形（likes は -s の付いた形）。', dict: { lemma: 'like', pos: 'verb', form: 'likes', tags: ['third-person', 'singular', 'present'] } },
      { kind: 'error', wrong: 'Is you a student?', right: 'Are you a student?', note: 'you には are を使う。', dict: { lemma: 'be', pos: 'verb', form: 'are', tags: ['second-person', 'present'] } },
      { kind: 'meaning', wrong: '"Don\'t you like coffee?" "Yes."', intended: '（いいえ、）好きではありません', right: '"Don\'t you like coffee?" "No, I don\'t."', note: 'Yes と答えると「好きです」の意味になる。好きでないなら No。' },
    ],
    exercises: [
      { type: 'fill', ja: 'あなたは今、忙しいですか。', text: '___ you busy now?', choices: ['Are', 'Do', 'Is'], answers: ['Are'] },
      { type: 'fill', ja: 'あなたのお兄さんはゴルフをしますか。', text: '___ your brother play golf?', choices: ['Do', 'Does', 'Is'], answers: ['Does'] },
      { type: 'fill', ja: '私は肉を食べません。', text: 'I ___ eat meat.', choices: ["don't", "doesn't", 'am not'], answers: ["don't"] },
      { type: 'order', ja: '彼はコーヒーを飲みません。', tokens: ['He', "doesn't", 'drink', 'coffee'], answers: ["He doesn't drink coffee."] },
      { type: 'order', ja: 'あなたは東京に住んでいますか。', tokens: ['Do', 'you', 'live', 'in', 'Tokyo'], answers: ['Do you live in Tokyo?'] },
      { type: 'rewrite', ja: '疑問文に書き直す。', from: 'She likes sushi.', answers: ['Does she like sushi?'] },
      { type: 'rewrite', ja: '否定文に書き直す。', from: 'I am hungry.', answers: ["I'm not hungry.", 'I am not hungry.'] },
      { type: 'rewrite', ja: '否定文に書き直す。', from: 'They play baseball.', answers: ["They don't play baseball.", 'They do not play baseball.'] },
      { type: 'oral', ja: 'お酒は飲みますか。', answers: ['Do you drink?'] },
      { type: 'oral', ja: '（↑に答えて）いいえ、飲みません。', answers: ["No, I don't."] },
      { type: 'oral', ja: '彼はここに住んでいません。', answers: ["He doesn't live here."] },
      { type: 'oral', ja: 'あなたは学生ですか。', answers: ['Are you a student?'] },
    ],
    myself: {
      task: '否定文を使って、自分がしないこと・好きではないことを1文で言ってみましょう。',
      samples: ["I don't drink coffee.", "I'm not a morning person."],
      checks: ['be動詞の文は be動詞＋not、一般動詞の文は don’t / doesn’t＋原形にした'],
    },
  },
  {
    id: 'g05',
    title: '疑問詞（what・where・when・who・why・how）',
    stage: '小学校の復習',
    sources: [
      { doc: 小, where: '第2部第2章第2節 2(1)エ（ｱ）d 疑問文（疑問詞 who，what，when，where，why，how で始まるもの）', page: '94〜95' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｱ）b 疑問文（wh- 疑問文。小学校の例文）', page: '37〜39' },
    ],
    points: [
      { text: '疑問詞は文の初めに置き、後ろは疑問文の語順にします：what（何）、who（誰）、where（どこ）、when（いつ）、why（なぜ）、how（どう・どのように）。' },
      { text: 'be動詞の文：疑問詞＋be動詞＋主語。', en: ['Where is the station?', 'Who is she?'] },
      { text: '一般動詞の文：疑問詞＋do / does＋主語＋動詞の原形。', en: ['Where do you live?', 'Where does he live?'] },
      { text: '名詞や形容詞と組み合わせて使えます：what time（何時）、how many（いくつ）、how old（何歳）。', en: ['What time does school begin?', 'How old is Tom?'] },
      { text: 'Yes / No ではなく、聞かれたことを答えます。短く答えてもかまいません。', en: ['Where do you live?', 'I live in Osaka.', 'In Osaka.'] },
      { text: '疑問詞の疑問文は、文の終わりを下げて言うのがふつうです。' },
      { text: 'which（どちら）と whose（誰の）は中学校の項目で扱います。' },
    ],
    examples: [
      { tatoeba: 370708, en: 'Where do you live?' },
      { tatoeba: 38153, en: 'Where do you work?' },
      { tatoeba: 16997, en: 'When is your birthday?' },
      { tatoeba: 21531, en: 'What time does school begin?' },
      { tatoeba: 292024, en: 'Where does he live?' },
      { tatoeba: 315731, en: 'Who is she?' },
      { tatoeba: 2261908, en: 'How old is Tom?' },
      { tatoeba: 1368, en: 'Why do you ask?' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'Where does he lives?', right: 'Where does he live?', note: 'does の後ろの動詞は原形。', dict: { lemma: 'live', pos: 'verb', form: 'lives', tags: ['third-person', 'singular', 'present'] } },
      { kind: 'error', wrong: 'Where is you from?', right: 'Where are you from?', note: 'you には are を使う。', dict: { lemma: 'be', pos: 'verb', form: 'are', tags: ['second-person', 'present'] } },
      { kind: 'meaning', wrong: 'What are you doing?', intended: 'お仕事は何ですか', right: 'What do you do?', note: 'What are you doing? は「今、何をしているの？」。仕事は現在形の What do you do? で聞く。' },
    ],
    exercises: [
      { type: 'fill', ja: 'どこに住んでいますか。—京都です。', text: '___ do you live? — I live in Kyoto.', choices: ['Where', 'What', 'When'], answers: ['Where'] },
      { type: 'fill', ja: '誕生日はいつですか。—5月5日です。', text: '___ is your birthday? — It is May 5th.', choices: ['When', 'Where', 'Who'], answers: ['When'] },
      { type: 'fill', ja: '会議は何時に始まりますか。', text: 'What time ___ the meeting start?', choices: ['does', 'do', 'is'], answers: ['does'] },
      { type: 'order', ja: 'どこで働いていますか。', tokens: ['Where', 'do', 'you', 'work'], answers: ['Where do you work?'] },
      { type: 'order', ja: '会議は何時に始まりますか。', tokens: ['What', 'time', 'does', 'the', 'meeting', 'start'], answers: ['What time does the meeting start?'] },
      { type: 'rewrite', ja: 'in Osaka（場所）をたずねる疑問文にする。', from: 'He lives in Osaka.', answers: ['Where does he live?'] },
      { type: 'rewrite', ja: 'at ten（時刻）をたずねる疑問文にする。', from: 'The shop opens at ten.', answers: ['What time does the shop open?', 'When does the shop open?'] },
      { type: 'oral', ja: 'ご出身はどちらですか。', answers: ['Where are you from?', 'Where do you come from?'] },
      { type: 'oral', ja: 'お仕事は何をされていますか。', answers: ['What do you do?'] },
      { type: 'oral', ja: '会議はいつですか。', answers: ['When is the meeting?'] },
      { type: 'oral', ja: 'なぜそう思うのですか。', answers: ['Why do you think so?'] },
    ],
    myself: {
      task: '初対面の人に聞かれそうな質問（Where do you work? など）を1つ選び、自分のことで1文答えてみましょう。',
      samples: ['Where do you work? — I work in Shibuya.', 'What do you do? — I am a university student.'],
      checks: ['質問は 疑問詞＋do / does / be動詞＋主語 の語順にした', 'Yes / No ではなく、聞かれたことを答えた'],
    },
  },
]
