// 文法（フェーズ9）の中身：修行場36〜45（中学校：現在完了・名詞をくわしく・気持ちを伝える）。書き方は items-01-05.mjs の先頭を参照。
const 中 = '中学校学習指導要領（平成29年告示）解説 外国語編'

export default [
  {
    id: 'g36',
    title: '現在完了（継続：ずっと〜している）',
    stage: '中学校：現在完了',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｳ）e 動詞の時制及び相など〈現在完了形〉（He has lived in London for two years.）', page: '47' }],
    points: [
      { text: 'have / has＋過去分詞で、過去から今まで続いている状態を表します（「ずっと〜している」）。', en: ["I've lived here for 30 years.", "I've been busy since yesterday."] },
      { text: 'for＋期間（for five years：5年間）、since＋始まった時（since 2012：2012年から）。' },
      { text: '「どのくらい〜しているか」は How long have you 〜?', en: ['How long have you been here?'] },
      { text: '主語が he・she など1人・1つなら has。短い形：I’ve、you’ve、he’s、she’s、it’s。' },
      { text: 'know・live・be などの状態を表す動詞でよく使います。動作が続いていることは現在完了進行形（修行場39）でも言えます。' },
    ],
    examples: [
      { tatoeba: 4999294, en: "I've lived here for 30 years." },
      { tatoeba: 11179195, en: "I've lived in this town since 1960." },
      { tatoeba: 259826, en: "I've studied Japanese for five years." },
      { tatoeba: 7715146, en: "I've been busy since yesterday." },
      { tatoeba: 2359142, en: "I've been here since Monday." },
      { tatoeba: 61716, en: 'How long have you been here?' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'I have lived here since ten years.', right: 'I have lived here for ten years.', note: '期間には for を使う。since は始まった時。', basis: { doc: 中, page: '47', find: "He has lived in London for two years." }, dict: { lemma: 'for', pos: 'prep', gloss: 'Over (a period of time).' } },
      { kind: 'meaning', wrong: 'I lived here for ten years.', intended: '（今も）ここに10年住んでいます', right: 'I have lived here for ten years.', note: '過去形の lived だと「10年住んでいた（今は住んでいない）」の意味になる。' },
    ],
    exercises: [
      { type: 'fill', ja: '2019年からここで働いています。', text: 'I have worked here ___ 2019.', choices: ['since', 'for', 'from'], answers: ['since'] },
      { type: 'fill', ja: '彼女は東京に5年住んでいます。', text: 'She ___ lived in Tokyo for five years.', choices: ['has', 'have', 'is'], answers: ['has'] },
      { type: 'order', ja: 'どのくらいここに住んでいますか。', tokens: ['How', 'long', 'have', 'you', 'lived', 'here'], answers: ['How long have you lived here?'] },
      { type: 'order', ja: '私は3年間英語を勉強しています。', tokens: ['I', 'have', 'studied', 'English', 'for', 'three', 'years'], answers: ['I have studied English for three years.', 'For three years I have studied English.'] },
      { type: 'rewrite', ja: 'for ten years を加え、現在完了で「10年前から知っている」にする。', from: 'I know Tom.', answers: ['I have known Tom for ten years.', "I've known Tom for ten years."] },
      { type: 'rewrite', ja: 'since last week を加え、現在完了の文にする。', from: 'He is busy.', answers: ['He has been busy since last week.', "He's been busy since last week."] },
      { type: 'oral', ja: 'この会社で5年働いています。', answers: ["I've worked for this company for five years.", 'I have worked at this company for five years.'] },
      { type: 'oral', ja: 'どのくらい日本にいるのですか。', answers: ['How long have you been in Japan?'] },
      { type: 'oral', ja: '彼とは子どものころからの知り合いです。', answers: ["I've known him since I was a child.", "I've known him since childhood."] },
    ],
    myself: {
      task: '今の家・仕事・趣味を、どのくらい続けているかを現在完了で1文言ってみましょう。',
      samples: ['I have lived in Tokyo for three years.', "I've worked at my company since 2022."],
      checks: ['have / has＋過去分詞 にした', '期間は for、始まりは since にした'],
    },
  },
  {
    id: 'g37',
    title: '現在完了（経験：〜したことがある）',
    stage: '中学校：現在完了',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｳ）e〈現在完了形〉（We have been to New York three times.）', page: '47' }],
    points: [
      { text: 'have / has＋過去分詞で「〜したことがある」（経験）。回数は once・twice・three times。', en: ["I've visited Kyoto twice.", "I've climbed Mt. Fuji."] },
      { text: '「〜に行ったことがある」は have been to 〜。', en: ["I've been to Paris twice."] },
      { text: '疑問文は Have you ever 〜?（今までに〜したことがありますか）。否定は never（一度も〜ない）。', en: ['Have you ever visited Kyoto?', "I've never met her."] },
      { text: '過去分詞：不規則なものに注意（see → seen、eat → eaten、meet → met など）。' },
    ],
    examples: [
      { tatoeba: 252532, en: "I've been to Paris twice." },
      { tatoeba: 2006609, en: "I've visited Kyoto twice." },
      { tatoeba: 261489, en: "I've climbed Mt. Fuji." },
      { tatoeba: 394821, en: "I've never met her." },
      { tatoeba: 69428, en: 'Have you ever visited Kyoto?' },
      { tatoeba: 69241, en: 'Have you ever eaten turkey?' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'I have saw that movie.', right: 'I have seen that movie.', note: 'have の後ろは過去分詞（saw は過去形）。', basis: { doc: 中, page: '47', find: "I have played this game more than twenty times." }, dict: { lemma: 'see', pos: 'verb', form: 'seen', tags: ['participle', 'past'] } },
      { kind: 'error', wrong: 'Have you ever eat sushi?', right: 'Have you ever eaten sushi?', note: 'have の後ろは過去分詞。', basis: { doc: 中, page: '47', find: "I have played this game more than twenty times." }, dict: { lemma: 'eat', pos: 'verb', form: 'eaten', tags: ['participle', 'past'] } },
      { kind: 'meaning', wrong: 'I have gone to Kyoto.', intended: '京都に行ったことがあります', right: 'I have been to Kyoto.', note: 'have gone to は「行ってしまった（今ここにいない）」の意味でよく使われる。経験は have been to がふつう。' },
    ],
    exercises: [
      { type: 'fill', ja: '沖縄に行ったことはありますか。', text: 'Have you ever ___ to Okinawa?', choices: ['been', 'gone', 'went'], answers: ['been'] },
      { type: 'fill', ja: '彼には一度も会ったことがありません。', text: 'I have ___ met him.', choices: ['never', 'ever', 'yet'], answers: ['never'] },
      { type: 'order', ja: '私はその映画を3回見たことがあります。', tokens: ['I', 'have', 'seen', 'the', 'movie', 'three', 'times'], answers: ['I have seen the movie three times.'] },
      { type: 'order', ja: 'これまでに海外で働いたことはありますか。', tokens: ['Have', 'you', 'ever', 'worked', 'abroad'], answers: ['Have you ever worked abroad?'] },
      { type: 'rewrite', ja: 'twice を加え、現在完了で「2回訪れたことがある」にする。', from: 'I visited Kyoto.', answers: ['I have visited Kyoto twice.', "I've visited Kyoto twice."] },
      { type: 'rewrite', ja: 'never を使い、現在完了で「一度も会ったことがない」にする。', from: 'I met her.', answers: ['I have never met her.', "I've never met her."] },
      { type: 'oral', ja: 'アメリカに行ったことはありますか。', answers: ['Have you ever been to the United States?', 'Have you ever been to America?'] },
      { type: 'oral', ja: '一度も海外に行ったことがありません。', answers: ["I've never been abroad.", 'I have never been overseas.'] },
      { type: 'oral', ja: 'その会社とは何度か仕事をしたことがあります。', answers: ["I've worked with that company several times.", "I've worked with that company a few times."] },
    ],
    myself: {
      task: '行ったことのある場所か、したことのある経験を、現在完了で1文言ってみましょう。',
      samples: ["I've been to Singapore twice.", "I've never given a presentation in English."],
      checks: ['have / has＋過去分詞 にした（行ったことは have been to）'],
    },
  },
  {
    id: 'g38',
    title: '現在完了（完了：〜したところ・もう〜した）',
    stage: '中学校：現在完了',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｳ）e〈現在完了形〉（I have just cleaned my room.）', page: '47' }],
    points: [
      { text: 'have / has＋過去分詞で「（ちょうど・もう）〜したところだ」（完了）。今の状態に結びついています。', en: ["He's just arrived.", "I've already eaten breakfast."] },
      { text: 'just（ちょうど）、already（もう）は have と過去分詞の間に置きます。' },
      { text: '疑問文と否定文では yet を文の終わりに置きます。疑問文の yet は「もう」、否定文の yet は「まだ」。', en: ['Have you eaten lunch yet?', "I haven't decided yet."] },
      { text: 'yesterday や last week のように、はっきり過去の時を表す語とは現在完了を使わず、過去形にします。' },
    ],
    examples: [
      { tatoeba: 1051716, en: "He's just arrived." },
      { tatoeba: 40126, en: "I've just finished lunch." },
      { tatoeba: 255766, en: "I've already eaten breakfast." },
      { tatoeba: 293066, en: "He's already left." },
      { tatoeba: 31190, en: 'Have you eaten lunch yet?' },
      { tatoeba: 32719, en: "I haven't decided yet." },
    ],
    mistakes: [
      { kind: 'error', wrong: 'He has went home.', right: 'He has gone home.', note: 'have / has の後ろは過去分詞（went は過去形）。', basis: { doc: 中, page: '47', find: "He has lived in London for two years." }, dict: { lemma: 'go', pos: 'verb', form: 'gone', tags: ['participle', 'past'] } },
      { kind: 'meaning', wrong: 'I lost my key.', intended: '鍵をなくしてしまった（今も見つからなくて困っている）', right: "I've lost my key.", note: '過去形の lost だけでは、今も見つかっていないのかは分からない。今の状態まで伝えるなら現在完了。' },
    ],
    exercises: [
      { type: 'fill', ja: 'ちょうど報告書を書き終えたところです。', text: 'I have ___ finished the report.', choices: ['just', 'yet', 'ever'], answers: ['just'] },
      { type: 'fill', ja: 'もうメールを送りましたか。', text: 'Have you sent the email ___?', choices: ['yet', 'already', 'just'], answers: ['yet'] },
      { type: 'order', ja: '彼はもう帰宅しました。', tokens: ['He', 'has', 'already', 'gone', 'home'], answers: ['He has already gone home.'] },
      { type: 'order', ja: 'まだ決めていません。', tokens: ['I', "haven't", 'decided', 'yet'], answers: ["I haven't decided yet."] },
      { type: 'rewrite', ja: 'just を入れて現在完了にする。', from: 'I finished my work.', answers: ['I have just finished my work.', "I've just finished my work."] },
      { type: 'rewrite', ja: 'yet を使った現在完了の疑問文にする。', from: 'Did you eat lunch?', answers: ['Have you eaten lunch yet?'] },
      { type: 'oral', ja: 'ちょうど資料を送ったところです。', answers: ["I've just sent the document.", 'I have just sent the file.'] },
      { type: 'oral', ja: 'もう会議は始まりましたか。', answers: ['Has the meeting started yet?', 'Has the meeting already started?'] },
      { type: 'oral', ja: 'まだ返事をもらっていません。', answers: ["I haven't received a reply yet.", "I haven't gotten a reply yet."] },
    ],
    myself: {
      task: '今日もう終えたこと（まだ終えていないこと）を、現在完了で1文言ってみましょう。',
      samples: ["I've already finished my morning tasks.", "I haven't checked my email yet."],
      checks: ['just・already は have と過去分詞の間、yet は文の終わりにした'],
    },
  },
  {
    id: 'g39',
    title: '現在完了進行形（ずっと〜し続けている）',
    stage: '中学校：現在完了',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｳ）e〈現在完了進行形〉（It has been raining since this morning.）', page: '47' }],
    points: [
      { text: 'have / has been＋-ing で、過去に始まった動作が今まで続いていることを表します（「ずっと〜し続けている」）。', en: ["It's been raining since morning.", 'He has been driving for hours.'] },
      { text: 'for（期間）や since（始まり）とよく使います。「どのくらい〜し続けているか」は How long have you been 〜ing?' },
      { text: 'work・wait・study・rain など動作を表す動詞で使います。know・like など状態を表す動詞は、ふつう現在完了（修行場36）で言います。' },
    ],
    examples: [
      { tatoeba: 277736, en: "It's been raining since morning." },
      { tatoeba: 281825, en: 'It has been raining since Sunday.' },
      { tatoeba: 294349, en: 'He has been driving for hours.' },
      { tatoeba: 8403038, en: "I've been working since 2:30." },
      { tatoeba: 2359322, en: "I've been waiting for this." },
    ],
    mistakes: [],
    exercises: [
      { type: 'fill', ja: '今朝からずっと雨が降っています。', text: 'It has been ___ since this morning.', choices: ['raining', 'rain', 'rained'], answers: ['raining'] },
      { type: 'fill', ja: 'どのくらいバスを待っているのですか。', text: 'How long have you been ___ for the bus?', choices: ['waiting', 'wait', 'waited'], answers: ['waiting'] },
      { type: 'order', ja: '私は2時間ずっとこの問題に取り組んでいます。', tokens: ['I', 'have', 'been', 'working', 'on', 'this', 'problem', 'for', 'two', 'hours'], answers: ['I have been working on this problem for two hours.', 'For two hours I have been working on this problem.'] },
      { type: 'rewrite', ja: 'for two hours を使って現在完了進行形にする。', from: 'He is studying. He started two hours ago.', answers: ['He has been studying for two hours.', "He's been studying for two hours."] },
      { type: 'rewrite', ja: 'since yesterday を使って現在完了進行形にする。', from: 'It is raining. It started yesterday.', answers: ['It has been raining since yesterday.', "It's been raining since yesterday."] },
      { type: 'oral', ja: '1時間ずっと待っています。', answers: ["I've been waiting for an hour."] },
      { type: 'oral', ja: '朝からずっと会議に出ています。', answers: ["I've been attending meetings since this morning."] },
      { type: 'oral', ja: 'どのくらい英語を勉強しているのですか。', answers: ['How long have you been studying English?'] },
    ],
    myself: {
      task: 'How long have you been 〜ing? に答える形で、自分が続けていることを1文言ってみましょう。',
      samples: ["I've been studying English for two years.", "I've been working on this project since April."],
      checks: ['have / has been＋-ing にした'],
    },
  },
  {
    id: 'g40',
    title: '分詞で名詞をくわしくする（a sleeping dog・a letter written in English）',
    stage: '中学校：名詞をくわしく',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｳ）i 現在分詞や過去分詞の形容詞としての用法', page: '50' }],
    points: [
      { text: '現在分詞（-ing）は「〜している」、過去分詞は「〜された」の意味で、名詞をくわしくします。', en: ['I saw a sleeping dog.', 'He found a broken camera.'] },
      { text: '分詞1語なら名詞の前、ほかの語句を伴うときは名詞の後ろに置きます。', en: ['Who is the girl standing over there?', 'I received a letter written in English.'] },
      { text: '名詞の後ろに置く形は日本語と語順が逆です（向こうに立っている女の子 → the girl standing over there）。' },
      { text: 'boring（退屈させる）と bored（退屈した）、interesting（おもしろい）と interested（興味がある）のように、-ing と過去分詞で意味がちがいます。' },
    ],
    examples: [
      { tatoeba: 261877, en: 'I saw a sleeping dog.' },
      { tatoeba: 294652, en: 'He found a broken camera.' },
      { tatoeba: 307236, en: 'They found the stolen money.' },
      { tatoeba: 240627, en: 'Who is the girl standing over there?' },
      { tatoeba: 257366, en: 'I know the man sitting over there.' },
      { tatoeba: 256198, en: 'I received a letter written in English.' },
      { tatoeba: 55448, en: 'This is a picture painted by him.' },
    ],
    mistakes: [
      { kind: 'meaning', wrong: 'I was boring at the meeting.', intended: '会議で退屈しました', right: 'I was bored at the meeting.', note: 'I was boring は「私は（人を）退屈させる人だった」の意味になる。' },
    ],
    exercises: [
      { type: 'fill', ja: '佐藤さんと話している男性は誰ですか。', text: 'Who is the man ___ to Ms. Sato?', choices: ['talking', 'talked', 'talk'], answers: ['talking'] },
      { type: 'fill', ja: 'これはドイツで作られた車です。', text: 'This is a car ___ in Germany.', choices: ['made', 'making', 'make'], answers: ['made'] },
      { type: 'order', ja: '向こうに立っている女性は私の上司です。', tokens: ['The', 'woman', 'standing', 'over', 'there', 'is', 'my', 'boss'], answers: ['The woman standing over there is my boss.'] },
      { type: 'order', ja: '英語で書かれたメールを受け取りました。', tokens: ['I', 'received', 'an', 'email', 'written', 'in', 'English'], answers: ['I received an email written in English.'] },
      { type: 'rewrite', ja: '分詞1語を名詞の前に置いて1文にする。', from: 'Look at the dog. It is sleeping.', answers: ['Look at the sleeping dog.'] },
      { type: 'rewrite', ja: '過去分詞を名詞の後ろに置いて1文にする。', from: 'I have a camera. It was made in Japan.', answers: ['I have a camera made in Japan.'] },
      { type: 'oral', ja: '窓のそばに座っている人は誰ですか。', answers: ['Who is the person sitting by the window?', 'Who is the man sitting by the window?'] },
      { type: 'oral', ja: 'これは昨年発売された製品です。', answers: ['This is a product released last year.'] },
      { type: 'oral', ja: '壊れたプリンターを直しました。', answers: ['I fixed the broken printer.', 'I repaired the broken printer.'] },
    ],
    myself: {
      task: '職場や学校の人を、分詞を使って1文で紹介してみましょう。',
      samples: ['The man sitting next to me is very kind.', 'I use a laptop made in Taiwan.'],
      checks: ['語句を伴う分詞は名詞の後ろに置いた'],
    },
  },
  {
    id: 'g41',
    title: '関係代名詞（主格：who・which・that）',
    stage: '中学校：名詞をくわしく',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｳ）a（b）関係代名詞のうち，主格の that，which，who の制限的用法', page: '44〜45' }],
    points: [
      { text: '名詞の後ろに who / which / that＋動詞〜 を置いて、「〜する（名詞）」とくわしくします。', en: ["That's the man who lives next door.", "That's the bus that goes to the station."] },
      { text: '人には who、物や動物には which、どちらにも that を使えます。' },
      { text: 'who・which・that の後ろの動詞は、前の名詞に合わせます（a friend who lives …、friends who live …）。' },
      { text: '日本語と語順が逆になります（隣に住んでいる男性 → the man who lives next door）。' },
    ],
    examples: [
      { tatoeba: 56191, en: 'This is the boy who helped me.' },
      { tatoeba: 67028, en: "That's the man who lives next door." },
      { tatoeba: 10147282, en: 'I know the man who lives downstairs.' },
      { tatoeba: 34142, en: 'I want a person who can speak French.' },
      { tatoeba: 11015473, en: "That's the bus that goes to the station." },
      { tatoeba: 322912, en: 'Nagoya is a city which is famous for its castle.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'I have a friend who live in Osaka.', right: 'I have a friend who lives in Osaka.', note: 'who の後ろの動詞は、前の名詞（a friend＝1人）に合わせる。現在の文なので lives。', basis: { doc: 中, page: '45', find: "The animal which runs the fastest is the cheetah." }, dict: { lemma: 'live', pos: 'verb', form: 'lives', tags: ['third-person', 'singular', 'present'] } },
    ],
    exercises: [
      { type: 'fill', ja: '私には銀行で働いている友人がいます。', text: 'I have a friend ___ works at a bank.', choices: ['who', 'which', 'he'], answers: ['who'] },
      { type: 'fill', ja: 'これは京都へ行く電車です。', text: 'This is the train ___ goes to Kyoto.', choices: ['that', 'who', 'where'], answers: ['that'] },
      { type: 'order', ja: '私にはフランス語を話せる同僚がいます。', tokens: ['I', 'have', 'a', 'colleague', 'who', 'can', 'speak', 'French'], answers: ['I have a colleague who can speak French.'] },
      { type: 'order', ja: '駅へ行くバスはどれですか。', tokens: ['Which', 'is', 'the', 'bus', 'that', 'goes', 'to', 'the', 'station'], answers: ['Which is the bus that goes to the station?'] },
      { type: 'rewrite', ja: 'who を使って1文にする。', from: 'I know a man. He lives in London.', answers: ['I know a man who lives in London.', 'I know a man that lives in London.'] },
      { type: 'rewrite', ja: 'which か that を使って1文にする。', from: 'This is a book. It is popular in Japan.', answers: ['This is a book which is popular in Japan.', 'This is a book that is popular in Japan.'] },
      { type: 'oral', ja: '英語を話せる人を探しています。', answers: ["We're looking for someone who can speak English.", "I'm looking for a person who can speak English."] },
      { type: 'oral', ja: '彼はこのソフトを作ったエンジニアです。', answers: ['He is the engineer who made this software.', "He's the engineer who developed this software."] },
      { type: 'oral', ja: 'これは空港へ行く電車ですか。', answers: ['Is this the train that goes to the airport?'] },
    ],
    myself: {
      task: '知り合いの1人を、who を使って1文で紹介してみましょう。',
      samples: ['I have a friend who works in New York.', 'My boss is a person who always listens to us.'],
      checks: ['who の後ろの動詞を、前の名詞に合わせた'],
    },
  },
  {
    id: 'g42',
    title: '関係代名詞（目的格：that・which）と接触節（the book I bought）',
    stage: '中学校：名詞をくわしく',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｳ）a（b）関係代名詞のうち，目的格の that，which の制限的用法（接触節は関係代名詞と併せて指導することも考えられる）', page: '44〜45' }],
    points: [
      { text: '名詞の後ろに that / which＋主語＋動詞 を置いて、「（主語が）〜する（名詞）」とくわしくします。', en: ['This is the book that I bought yesterday.', 'This is the camera which I bought yesterday.'] },
      { text: 'この that・which は省くことができます（接触節）。話すときは省くことが多いです。', en: ['This is the camera I bought yesterday.', "That's the man I saw yesterday."] },
      { text: 'まとまりの中では、前の名詞をくり返しません（the book I bought。I bought it とはしない）。' },
      { text: '人をくわしくするときは that を使うか、省いた形にします（the man I met）。' },
    ],
    examples: [
      { tatoeba: 6864743, en: 'This is the book that I bought yesterday.' },
      { tatoeba: 55695, en: 'This is the camera which I bought yesterday.' },
      { tatoeba: 1397834, en: 'This is the camera I bought yesterday.' },
      { tatoeba: 55654, en: 'This is a picture I took last week.' },
      { tatoeba: 9324809, en: "That's the man I saw yesterday." },
      { tatoeba: 6341699, en: 'Was the movie you saw yesterday interesting?' },
    ],
    mistakes: [],
    exercises: [
      { type: 'fill', ja: 'これは私がパリで買ったかばんです。', text: 'This is the bag ___ I bought in Paris.', choices: ['that', 'who', 'what'], answers: ['that'] },
      { type: 'order', ja: 'これは私が先週撮った写真です。', tokens: ['This', 'is', 'a', 'picture', 'I', 'took', 'last', 'week'], answers: ['This is a picture I took last week.'] },
      { type: 'order', ja: '昨日会った男性は私の顧客です。', tokens: ['The', 'man', 'I', 'met', 'yesterday', 'is', 'my', 'client'], answers: ['The man I met yesterday is my client.'] },
      { type: 'rewrite', ja: '1文にする（that・which は使っても省いてもよい）。', from: 'This is the report. I wrote it yesterday.', answers: ['This is the report that I wrote yesterday.', 'This is the report which I wrote yesterday.', 'This is the report I wrote yesterday.'] },
      { type: 'rewrite', ja: '1文にする（that・which は使っても省いてもよい）。', from: 'The movie was interesting. I saw it last night.', answers: ['The movie I saw last night was interesting.', 'The movie that I saw last night was interesting.', 'The movie which I saw last night was interesting.'] },
      { type: 'oral', ja: 'これは私が作った資料です。', answers: ['This is the document I made.', 'These are the materials I prepared.'] },
      { type: 'oral', ja: 'あなたが昨日話していた本はこれですか。', answers: ['Is this the book you were talking about yesterday?'] },
      { type: 'oral', ja: '彼が勧めてくれたレストランに行きました。', answers: ['I went to the restaurant he recommended.'] },
    ],
    myself: {
      task: '最近買ったもの・読んだものを、接触節（the 〜 I bought など）を使って1文言ってみましょう。',
      samples: ['The laptop I bought last month is very fast.', 'The book I read last week was about leadership.'],
      checks: ['まとまりの中で、前の名詞をくり返していない'],
    },
  },
  {
    id: 'g43',
    title: '数や量を表す語（some・any・a few・a little・every など）',
    stage: '中学校：名詞をくわしく',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｳ）a（a）人称や指示，疑問，数量を表すもの（数量を表すもの：some，few，much など）', page: '44' }],
    points: [
      { text: 'some は「いくつか・いくらか」でふつうの文に、any は疑問文と否定文に使います。', en: ['I want some money.', 'Do you have any vacancies?'] },
      { text: '人に勧めたり頼んだりする疑問文では some を使います（Would you like some coffee?）。' },
      { text: '数えられる名詞には many・a few・few、数えない名詞には much・a little・little。' },
      { text: 'a few・a little は「少しある」、few・little は「ほとんどない」。', en: ['We had little water.'] },
      { text: 'every・each の後ろは単数形の名詞（every student）。all・both の後ろは複数形。', en: ['Both are alive.', 'All are happy.'] },
    ],
    examples: [
      { tatoeba: 33542, en: 'I want some money.' },
      { tatoeba: 1302458, en: 'I have some time.' },
      { tatoeba: 18354, en: 'Do you have any vacancies?' },
      { tatoeba: 247350, en: 'We had little water.' },
      { tatoeba: 24518, en: 'Some were late.' },
      { tatoeba: 72810, en: 'Both are alive.' },
    ],
    mistakes: [
      { kind: 'meaning', wrong: 'I have little time.', intended: '少しは時間があります', right: 'I have a little time.', note: 'little だけだと「時間がほとんどない」の意味になる。' },
    ],
    exercises: [
      { type: 'fill', ja: '何か質問はありますか。', text: 'Do you have ___ questions?', choices: ['any', 'much', 'a little'], answers: ['any'] },
      { type: 'fill', ja: 'ロンドンに友人が何人かいます。', text: 'I have ___ friends in London.', choices: ['a few', 'a little', 'much'], answers: ['a few'] },
      { type: 'fill', ja: '牛乳はあまり残っていません。', text: "There isn't ___ milk left.", choices: ['much', 'many', 'few'], answers: ['much'] },
      { type: 'order', ja: '何人かの社員が遅れてきました。', tokens: ['Some', 'employees', 'came', 'late'], answers: ['Some employees came late.'] },
      { type: 'order', ja: '時間は少しあります。', tokens: ['I', 'have', 'a', 'little', 'time'], answers: ['I have a little time.'] },
      { type: 'rewrite', ja: 'any を使った否定文にする。', from: 'I have some money.', answers: ["I don't have any money.", 'I do not have any money.'] },
      { type: 'rewrite', ja: 'every を使って書き直す。', from: 'All the students have a computer.', answers: ['Every student has a computer.'] },
      { type: 'oral', ja: '何か質問はありますか。', answers: ['Do you have any questions?', 'Are there any questions?'] },
      { type: 'oral', ja: 'もう少し時間をいただけますか。', answers: ['Could you give me a little more time?', 'Can I have a little more time?'] },
      { type: 'oral', ja: '両方とも良い案です。', answers: ['Both are good ideas.', 'Both of them are good ideas.'] },
    ],
    myself: {
      task: 'some・a few・a little を使って、自分の持ち物か知り合いについて1文言ってみましょう。',
      samples: ['I have a few friends in Canada.', 'I have some free time on weekends.'],
      checks: ['数えられる名詞は a few、数えない名詞は a little にした'],
    },
  },
  {
    id: 'g44',
    title: '仮定法の基本（If I were you 〜・I wish 〜）',
    stage: '中学校：気持ちを伝える',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｳ）k 仮定法のうち基本的なもの', page: '51' }],
    points: [
      { text: '今の事実とちがうことを想像して「もし〜なら、…だろうに」は If＋主語＋過去形, 主語＋would / could＋動詞の原形。', en: ['If I had money, I could buy it.', 'If I had time, I would study French.'] },
      { text: 'be動詞は主語にかかわらず were を使うのが基本です（話し言葉では was も使われます）。If I were you は「私があなたなら」。', en: ['If I were you, I would trust her.'] },
      { text: '「〜ならいいのに」は I wish＋主語＋過去形（were・could・had など）。', en: ['I wish I were rich.', 'I wish I could swim.'] },
      { text: '実際に起こりうることの条件は、ふつうの if の文（If it rains, 〜。修行場23）で言います。' },
    ],
    examples: [
      { tatoeba: 30827, en: 'If I were you, I would trust her.' },
      { tatoeba: 30621, en: "If I were you, I wouldn't do it." },
      { tatoeba: 30898, en: 'If I had money, I could buy it.' },
      { tatoeba: 30918, en: 'If I had time, I would study French.' },
      { tatoeba: 18531, en: 'I wish I were rich.' },
      { tatoeba: 26397, en: 'I wish I could swim.' },
      { tatoeba: 2549717, en: 'I wish I knew.' },
    ],
    mistakes: [
      { kind: 'meaning', wrong: 'If I have time, I will help you.', intended: '（実際は時間がないけれど）時間があれば手伝えるのに', right: 'If I had time, I would help you.', note: '現在形の if の文は「時間ができたら手伝う」（実際に起こりうること）の意味になる。' },
    ],
    exercises: [
      { type: 'fill', ja: '私があなたなら、彼に聞きます。', text: 'If I ___ you, I would ask him.', choices: ['were', 'am', 'be'], answers: ['were'] },
      { type: 'fill', ja: '中国語が話せたらいいのに。', text: 'I wish I ___ speak Chinese.', choices: ['could', 'can', 'will'], answers: ['could'] },
      { type: 'order', ja: 'もし時間があれば、フランス語を勉強するのに。', tokens: ['If', 'I', 'had', 'time', 'I', 'would', 'study', 'French'], answers: ['If I had time, I would study French.', 'I would study French if I had time.'] },
      { type: 'order', ja: 'もっと英語が上手に話せればいいのに。', tokens: ['I', 'wish', 'I', 'could', 'speak', 'English', 'better'], answers: ['I wish I could speak English better.'] },
      { type: 'rewrite', ja: 'If I had で始めて「車があれば車で通勤できるのに」にする。', from: "I don't have a car, so I can't drive to work.", answers: ['If I had a car, I could drive to work.'] },
      { type: 'rewrite', ja: 'I wish で始めて書き直す。', from: "I'm sorry I'm not rich.", answers: ['I wish I were rich.', 'I wish I was rich.'] },
      { type: 'oral', ja: '私があなたなら、その申し出を受けます。', answers: ['If I were you, I would accept the offer.', "If I were you, I'd take the offer."] },
      { type: 'oral', ja: 'もっと時間があればいいのに。', answers: ['I wish I had more time.'] },
      { type: 'oral', ja: 'お金があれば、それを買えるのに。', answers: ['If I had the money, I could buy it.', 'If I had money, I could buy it.'] },
    ],
    myself: {
      task: 'I wish 〜 で、今の自分の願いを1文言ってみましょう。',
      samples: ['I wish I could speak English fluently.', 'I wish I had more time for my hobbies.'],
      checks: ['I wish の後ろは過去形（were・could・had など）にした'],
    },
  },
  {
    id: 'g45',
    title: '感嘆文（How …! / What a …!）',
    stage: '中学校：気持ちを伝える',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｱ）c 感嘆文のうち基本的なもの（How interesting! / What a big tree!）', page: '39' }],
    points: [
      { text: 'How＋形容詞・副詞（＋主語＋動詞）! で「なんて〜なんだろう」。', en: ['How kind you are!', 'How beautiful it is!'] },
      { text: 'What a / an＋形容詞＋名詞（＋主語＋動詞）! で「なんて〜な…なんだろう」。', en: ['What a beautiful rainbow!', 'What a big supermarket!'] },
      { text: '名詞が複数や数えない名詞のときは a を付けません（What beautiful flowers!）。' },
      { text: '主語＋動詞は、話すときはよく省きます（How interesting!）。' },
    ],
    examples: [
      { tatoeba: 16443, en: 'How kind you are!' },
      { tatoeba: 36004, en: 'How beautiful it is!' },
      { tatoeba: 24877, en: 'What a beautiful rainbow!' },
      { tatoeba: 24880, en: 'What a big supermarket!' },
      { tatoeba: 36011, en: 'What a wonderful invention!' },
      { tatoeba: 36023, en: 'How beautifully she sings!' },
    ],
    mistakes: [],
    exercises: [
      { type: 'fill', ja: 'なんていい眺めなんだろう。', text: '___ a nice view!', choices: ['What', 'How', 'Which'], answers: ['What'] },
      { type: 'fill', ja: 'あなたはなんて親切なんでしょう。', text: '___ kind you are!', choices: ['How', 'What', 'Which'], answers: ['How'] },
      { type: 'order', ja: 'なんて大きな建物なんだろう。', tokens: ['What', 'a', 'big', 'building'], answers: ['What a big building!'] },
      { type: 'order', ja: '彼はなんて速く走るんだろう。', tokens: ['How', 'fast', 'he', 'runs'], answers: ['How fast he runs!'] },
      { type: 'rewrite', ja: 'What で始める感嘆文にする。', from: 'This is a very good idea.', answers: ['What a good idea this is!', 'What a good idea!'] },
      { type: 'rewrite', ja: 'How で始める感嘆文にする。', from: 'The view is very beautiful.', answers: ['How beautiful the view is!'] },
      { type: 'oral', ja: 'なんていい考えなんでしょう。', answers: ['What a good idea!', 'What a great idea!'] },
      { type: 'oral', ja: 'ご親切にありがとうございます（なんて親切なんでしょう）。', answers: ['How kind of you!', 'How kind you are!'] },
      { type: 'oral', ja: 'なんてすばらしい景色でしょう。', answers: ['What a beautiful view!', 'What a wonderful view!'] },
    ],
    myself: {
      task: '最近感動したこと・驚いたことを、感嘆文で1文言ってみましょう。',
      samples: ['What a great day it was!', 'How fast the year has gone!'],
      checks: ['What の後は a＋形容詞＋名詞、How の後は形容詞・副詞にした'],
    },
  },
]
