// 文法（フェーズ10）の中身：修行場51〜64（高校：関係詞・つなぎ方と助動詞・時と仮定・必要に応じて扱うもの）。書き方は items-01-05.mjs の先頭を参照。
// 項目は高等学校学習指導要領解説 外国語編 英語編の「英語コミュニケーションⅠ」2(1)エ 文構造及び文法事項（p.35〜39）に沿う。
const 高 = '高等学校学習指導要領（平成30年告示）解説 外国語編 英語編'
const 中 = '中学校学習指導要領（平成29年告示）解説 外国語編'

export default [
  {
    id: 'h06',
    title: '関係代名詞 what（〜すること・〜するもの）',
    stage: '高校：関係詞',
    sources: [{ doc: 高, where: '第2章第1節 英語コミュニケーションⅠ 2(1)エ（イ）b 関係代名詞の用法（先行詞をとらない関係代名詞 what）', page: '38' }],
    points: [
      { text: 'what は「〜すること」「〜するもの」（the thing that 〜）。前に名詞（先行詞）を置きません。', en: ['What he says is true.', 'This is what I wanted.'] },
      { text: '「what＋主語＋動詞」のまとまり全体が、文の主語や目的語になります。主語のときは、まとまり全体を1つのものとして is・was で受けます。', en: ['What you said surprised me.'] },
      { text: '疑問詞の what（何を〜か。修行場24）と形は同じです。I know what you mean. はどちらの意味でも読めます。' },
      { text: '仕事では What we need is 〜（必要なのは〜です）のように、大事なことを後ろに回して強調する言い方がよく使われます。', en: ['What we need is more time.'] },
    ],
    examples: [
      { tatoeba: 17871, en: 'What you said surprised me.' },
      { tatoeba: 286052, en: 'What he says is true.' },
      { tatoeba: 70697, en: 'What you said is not true.' },
      { tatoeba: 55642, en: 'This is what I wanted.' },
      { tatoeba: 56128, en: "That's just what I wanted." },
      { tatoeba: 70712, en: 'I understand what you mean.' },
      { tatoeba: 261757, en: 'I meant what I said.' },
    ],
    mistakes: [],
    exercises: [
      { type: 'fill', ja: '彼が言ったことは本当だ。', text: '___ he said is true.', choices: ['What', 'That', 'Which'], answers: ['What'] },
      { type: 'fill', ja: 'これがまさに私の欲しかったものです。', text: 'This is just ___ I wanted.', choices: ['what', 'which', 'who'], answers: ['what'] },
      { type: 'order', ja: 'あなたの言いたいことは分かります。', tokens: ['I', 'understand', 'what', 'you', 'mean'], answers: ['I understand what you mean.'] },
      { type: 'order', ja: '君が言ったことに驚いた。', tokens: ['What', 'you', 'said', 'surprised', 'me'], answers: ['What you said surprised me.'] },
      { type: 'rewrite', ja: 'the thing that を what 1語にして書き直す。', from: 'The thing that he said was not true.', answers: ['What he said was not true.'] },
      { type: 'rewrite', ja: 'the thing that を what 1語にして書き直す。', from: 'Time is the thing that I need.', answers: ['Time is what I need.'] },
      { type: 'oral', ja: '私が言いたいのはそういうことです。', answers: ["That's what I mean.", 'That is what I mean.', "That's what I want to say."] },
      { type: 'oral', ja: '必要なのはもっと時間です。', answers: ['What we need is more time.', 'What I need is more time.'] },
      { type: 'oral', ja: '彼の言うことは本当だ。', answers: ['What he says is true.'] },
      { type: 'oral', ja: '言ったことは本気です。', answers: ['I meant what I said.', 'I mean what I said.'] },
    ],
    myself: {
      task: 'What I need is 〜 か What I want to do is 〜 で、今の自分に必要なこと・したいことを1文で言ってみましょう。',
      samples: ['What I need is more practice.', 'What I want to do is speak English at work.'],
      checks: ['what の前に名詞を置かなかった', 'What 〜 が主語のとき、動詞は is にした'],
    },
  },
  {
    id: 'h07',
    title: '関係代名詞の非制限用法（, who・, which で付け足す）',
    stage: '高校：関係詞',
    sources: [{ doc: 高, where: '第2章第1節 英語コミュニケーションⅠ 2(1)エ（イ）b 関係代名詞の用法（非制限的用法）', page: '38' }],
    points: [
      { text: '関係代名詞の前にコンマを置くと、名詞にあとから説明を付け足す言い方になります（非制限用法）。', en: ['My uncle, who lives in Osaka, visited us yesterday.'] },
      { text: 'コンマのない文（修行場41・42）は「どの〜か」を絞り込みます。コンマのある文は、相手がもう分かっている人・物に情報を足します。' },
      { text: '人には who、物には which を使います。コンマの後ろに that は使いません。' },
      { text: ', which は前の文の内容全体を受けて「そして、そのことが〜」とも使えます。', en: ['I said nothing, which made him angry.'] },
      { text: '話すときは、コンマのところで少し間を置きます。' },
    ],
    examples: [
      { tatoeba: 251186, en: 'My uncle, who lives in Osaka, visited us yesterday.' },
      { tatoeba: 279735, en: 'My aunt, who lives in Tokyo, sent me a beautiful blouse.' },
      { tatoeba: 32923, en: 'Mike visited Mr Ogaki, who is our principal.' },
      { tatoeba: 246787, en: 'This desk, which I bought yesterday, is very big.' },
      { tatoeba: 256400, en: 'I said nothing, which made him angry.' },
      { tatoeba: 304319, en: 'He broke his promise, which was a big mistake.' },
      { tatoeba: 37026, en: 'Tom said he was ill, which was a lie.' },
    ],
    mistakes: [
      { kind: 'meaning', wrong: 'My sister who lives in Tokyo is a nurse.', intended: '（姉は1人で）その姉は東京に住んでいて、看護師です', right: 'My sister, who lives in Tokyo, is a nurse.', note: 'コンマがないと「（何人かいる姉のうち）東京に住んでいる姉」と絞り込む意味になり、姉が何人もいるように聞こえる。' },
    ],
    exercises: [
      { type: 'fill', ja: '東京に住んでいるおばが、ブラウスを送ってくれた。', text: 'My aunt, ___ lives in Tokyo, sent me a blouse.', choices: ['who', 'which', 'what'], answers: ['who'] },
      { type: 'fill', ja: '私は何も言わなかったが、それが彼を怒らせた。', text: 'I said nothing, ___ made him angry.', choices: ['which', 'who', 'what'], answers: ['which'] },
      { type: 'order', ja: '昨日買ったこの机は、とても大きい。（コンマは打たなくてよい）', tokens: ['This', 'desk', 'which', 'I', 'bought', 'yesterday', 'is', 'very', 'big'], answers: ['This desk, which I bought yesterday, is very big.'] },
      { type: 'order', ja: '彼は約束を破ったが、それは大きな誤りだった。（コンマは打たなくてよい）', tokens: ['He', 'broke', 'his', 'promise', 'which', 'was', 'a', 'big', 'mistake'], answers: ['He broke his promise, which was a big mistake.'] },
      { type: 'rewrite', ja: ', who を使って1文にする。', from: 'My uncle lives in Osaka. He visited us yesterday.', answers: ['My uncle, who lives in Osaka, visited us yesterday.'] },
      { type: 'rewrite', ja: ', which を使って1文にする。', from: 'Tom said he was ill. That was a lie.', answers: ['Tom said he was ill, which was a lie.'] },
      { type: 'oral', ja: '私の上司は、ロンドン出身なのですが、とても親切です。', answers: ['My boss, who is from London, is very kind.'] },
      { type: 'oral', ja: '彼は会議に遅れたが、それは珍しいことだった。', answers: ['He was late for the meeting, which was unusual.'] },
      { type: 'oral', ja: '新しいシステムを入れたが、それで時間が節約できた。', answers: ['We introduced a new system, which saved us time.', 'We introduced a new system, which saved time.'] },
    ],
    myself: {
      task: ', who か , which で、身近な人や物に説明を付け足して1文で言ってみましょう。',
      samples: ['My father, who is sixty, still plays tennis.', 'I use a laptop, which my company gave me.'],
      checks: ['付け足す説明の前後にコンマを置いた', 'コンマの後ろに that を使わなかった'],
    },
  },
  {
    id: 'h08',
    title: '関係副詞（where・when・why・how）',
    stage: '高校：関係詞',
    sources: [{ doc: 高, where: '第2章第1節 英語コミュニケーションⅠ 2(1)エ（イ）c 関係副詞の用法（関係副詞及びその先行詞は省略されることが多い）', page: '38' }],
    points: [
      { text: 'where・when・why は、場所・時・理由を表す名詞を後ろから説明します。', en: ['This is the house where I live.', 'I remember the day when we first met.'] },
      { text: 'where は「その場所で」、when は「その時に」、why は「その理由で」（the reason why）。' },
      { text: '関係副詞や、その前の名詞はよく省かれます。That’s why 〜（だから〜）、That’s where 〜（そこが〜なところ）はよく使う形です。', en: ["That's why I was late.", "That's where you're wrong."] },
      { text: 'how は「〜するやり方」。the way と how は一緒に使わず、どちらか一方にします。', en: ['This is how it happened.'] },
      { text: 'where の代わりに in which も使えます。かたい言い方です（修行場58）。', en: ['The town in which I live is rather small.'] },
    ],
    examples: [
      { tatoeba: 56203, en: 'This is the house where I live.' },
      { tatoeba: 61649, en: 'This is the town where I was born.' },
      { tatoeba: 61636, en: 'Is this the place where the accident happened?' },
      { tatoeba: 247253, en: 'I remember the day when we first met.' },
      { tatoeba: 62398, en: 'This is the reason why I came here.' },
      { tatoeba: 51230, en: "That's why I was late." },
      { tatoeba: 62324, en: 'This is how it happened.' },
    ],
    mistakes: [],
    exercises: [
      { type: 'fill', ja: 'ここが私の生まれた町です。', text: 'This is the town ___ I was born.', choices: ['where', 'which', 'when'], answers: ['where'] },
      { type: 'fill', ja: '私たちが初めて会った日を覚えています。', text: 'I remember the day ___ we first met.', choices: ['when', 'where', 'what'], answers: ['when'] },
      { type: 'fill', ja: 'そういうわけで遅れました。', text: "That's ___ I was late.", choices: ['why', 'how', 'where'], answers: ['why'] },
      { type: 'order', ja: 'ここが事故の起きた場所ですか。', tokens: ['Is', 'this', 'the', 'place', 'where', 'the', 'accident', 'happened'], answers: ['Is this the place where the accident happened?'] },
      { type: 'order', ja: 'こうしてそれは起きたのです。', tokens: ['This', 'is', 'how', 'it', 'happened'], answers: ['This is how it happened.'] },
      { type: 'rewrite', ja: 'where を使って1文にする。', from: 'This is the house. I live in it.', answers: ['This is the house where I live.'] },
      { type: 'rewrite', ja: '2文目を That’s why で始めて書き直す。', from: 'I was sick. So I stayed home.', answers: ["I was sick. That's why I stayed home.", 'I was sick. That is why I stayed home.'] },
      { type: 'oral', ja: 'そういうわけで、ここに来ました。', answers: ["That's why I came here.", 'That is why I came here.', 'This is why I came here.'] },
      { type: 'oral', ja: 'ここが私の働いている事務所です。', answers: ['This is the office where I work.'] },
      { type: 'oral', ja: '彼が辞めた理由を教えてください。', answers: ['Tell me the reason why he quit.', 'Please tell me the reason why he quit.', 'Tell me why he quit.', 'Please tell me why he quit.'] },
      { type: 'oral', ja: 'そこがあなたの間違っているところです。', answers: ["That's where you're wrong.", 'That is where you are wrong.', "That's where you're mistaken."] },
    ],
    myself: {
      task: 'where か That’s why で、自分のことを1文で言ってみましょう。',
      samples: ['This is the city where I was born.', "I want to work abroad. That's why I study English."],
      checks: ['場所のあとは where、理由は why にした'],
    },
  },
  {
    id: 'h09',
    title: '接続詞（although・while・unless・as soon as・so that）',
    stage: '高校：つなぎ方と助動詞',
    sources: [
      { doc: 高, where: '第2章第1節 英語コミュニケーションⅠ 2(1)エ（イ）d 接続詞の用法', page: '38' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）b 接続詞', page: '45' },
    ],
    points: [
      { text: 'although・though は「〜だけれども」。', en: ['Though it was raining, she went out.'] },
      { text: 'even though は「（実際に）〜なのに」、even if は「（たとえ）〜だとしても」。' },
      { text: 'while は「〜している間に」。', en: ['She called while I was out.'] },
      { text: 'unless は「〜しない限り」（if 〜 not に近い意味）。', en: ["You'll never know unless you try."] },
      { text: 'as soon as は「〜するとすぐに」。先のことでも、as soon as・unless の後ろは現在形にします（修行場23の if・when と同じ）。', en: ['I will call you as soon as I get home.'] },
      { text: 'so that 〜 can は「〜できるように」。', en: ['Speak more slowly so that we can understand you.'] },
      { text: 'although と but は一緒に使いません。どちらか一方にします。' },
    ],
    examples: [
      { tatoeba: 26936, en: 'Though it was raining, she went out.' },
      { tatoeba: 272543, en: 'Although it is snowing, I must go.' },
      { tatoeba: 1399, en: "Even though he apologized, I'm still furious." },
      { tatoeba: 250601, en: 'She called while I was out.' },
      { tatoeba: 30341, en: "You'll never know unless you try." },
      { tatoeba: 8983599, en: "You'll fail unless you study harder." },
      { tatoeba: 247311, en: 'Speak more slowly so that we can understand you.' },
    ],
    mistakes: [
      { kind: 'meaning', wrong: 'Even if it is raining, I must go.', intended: '（実際に）雨が降っているけれど、行かなければならない', right: 'Even though it is raining, I must go.', note: 'even if は「たとえ〜だとしても」で、実際に降っているかどうかは分からないときの言い方。実際に降っているなら even though。' },
    ],
    exercises: [
      { type: 'fill', ja: '雨が降っていたけれど、私たちはサッカーをした。', text: '___ it was raining, we played football.', choices: ['Though', 'Unless', 'So'], answers: ['Though'] },
      { type: 'fill', ja: 'もっと勉強しない限り、落第しますよ。', text: "You'll fail ___ you study harder.", choices: ['unless', 'if', 'though'], answers: ['unless'] },
      { type: 'fill', ja: '私の外出中に、彼女から電話があった。', text: 'She called ___ I was out.', choices: ['while', 'during', 'unless'], answers: ['while'] },
      { type: 'order', ja: '家に着いたらすぐに電話します。', tokens: ['I', 'will', 'call', 'you', 'as', 'soon', 'as', 'I', 'get', 'home'], answers: ['I will call you as soon as I get home.', 'As soon as I get home, I will call you.'] },
      { type: 'order', ja: 'バスに間に合うように急ごう。', tokens: ["Let's", 'hurry', 'so', 'that', 'we', 'can', 'catch', 'the', 'bus'], answers: ["Let's hurry so that we can catch the bus."] },
      { type: 'rewrite', ja: 'Although で始めて1文にする。', from: 'He is rich. But he is not happy.', answers: ['Although he is rich, he is not happy.', "Although he's rich, he's not happy.", "Although he is rich, he isn't happy."] },
      { type: 'rewrite', ja: 'unless を使って書き直す。', from: "If you don't try, you'll never know.", answers: ["You'll never know unless you try.", "Unless you try, you'll never know."] },
      { type: 'oral', ja: '疲れていたけれど、働き続けた。', answers: ['Although I was tired, I kept working.', 'Though I was tired, I kept working.', 'Although I was tired, I kept on working.'] },
      { type: 'oral', ja: '終わったらすぐにお知らせします。', answers: ["I'll let you know as soon as I finish.", "I'll tell you as soon as I finish.", "I'll let you know as soon as it's finished."] },
      { type: 'oral', ja: '皆に聞こえるように、大きな声で話してください。', answers: ['Please speak loudly so that everyone can hear you.', 'Please speak up so that everyone can hear you.', 'Speak loudly so that everyone can hear you.'] },
    ],
    myself: {
      task: 'although か unless を使って、仕事や勉強のことを1文で言ってみましょう。',
      samples: ['Although I was busy, I studied English for an hour.', "I can't improve unless I practice every day."],
      checks: ['although と but を一緒に使わなかった', 'as soon as・unless の後ろは、先のことでも現在形にした'],
    },
  },
  {
    id: 'h10',
    title: '助動詞の過去形（could・would・might）',
    stage: '高校：つなぎ方と助動詞',
    sources: [
      { doc: 高, where: '第2章第1節 英語コミュニケーションⅠ 2(1)エ（イ）e 助動詞の用法（助動詞の過去形）', page: '38' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）c 助動詞（Can you open the window?）', page: '45' },
    ],
    points: [
      { text: 'Could you 〜? / Would you 〜? は、Can you 〜? / Will you 〜? より丁寧な頼み方です。', en: ['Could you help me?', 'Would you close the window?'] },
      { text: 'might・could は「〜かもしれない」。may より控えめな言い方です。', en: ['I might be wrong.', 'You could be right.'] },
      { text: 'Would you like 〜? は「〜はいかがですか」、I would like to 〜 は「〜したいのですが」（丁寧）。' },
      { text: '助動詞の後ろの動詞は、過去形の助動詞でもいつも原形です。' },
    ],
    examples: [
      { tatoeba: 64405, en: 'Could you help me?' },
      { tatoeba: 2242, en: 'Could you please repeat that?' },
      { tatoeba: 274198, en: 'Would you close the window?' },
      { tatoeba: 256737, en: 'I might be wrong.' },
      { tatoeba: 2647758, en: 'You could be right.' },
      { tatoeba: 6196187, en: 'I might be late.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'Could you helped me?', right: 'Could you help me?', note: 'could の後ろの動詞は原形。過去の話でなくても、丁寧に頼むときは could を使う。', basis: { doc: 中, page: '51', find: 'I could get some information' }, dict: { lemma: 'help', pos: 'verb', form: 'help', tags: ['infinitive'] } },
    ],
    exercises: [
      { type: 'fill', ja: '手伝っていただけますか。', text: '___ you help me?', choices: ['Could', 'Did', 'Are'], answers: ['Could'] },
      { type: 'fill', ja: '私が間違っているかもしれない。', text: 'I ___ be wrong.', choices: ['might', 'must', 'did'], answers: ['might'] },
      { type: 'fill', ja: '窓を閉めていただけませんか。', text: '___ you close the window?', choices: ['Would', 'Are', 'Did'], answers: ['Would'] },
      { type: 'order', ja: 'もう一度言っていただけますか。', tokens: ['Could', 'you', 'please', 'repeat', 'that'], answers: ['Could you please repeat that?', 'Could you repeat that, please?'] },
      { type: 'order', ja: '遅れるかもしれません。', tokens: ['I', 'might', 'be', 'late'], answers: ['I might be late.'] },
      { type: 'rewrite', ja: 'Could you で始めて、丁寧な頼み方にする。', from: 'Send me the file.', answers: ['Could you send me the file?', 'Could you please send me the file?'] },
      { type: 'rewrite', ja: 'might を使って「〜かもしれない」にする。', from: 'Maybe he is busy.', answers: ['He might be busy.'] },
      { type: 'oral', ja: '資料を送っていただけますか。', answers: ['Could you send me the documents?', 'Could you please send me the documents?', 'Could you send me the materials?'] },
      { type: 'oral', ja: 'あなたの言う通りかもしれません。', answers: ['You might be right.', 'You could be right.', 'You may be right.'] },
      { type: 'oral', ja: 'コーヒーはいかがですか。', answers: ['Would you like some coffee?', 'Would you like a coffee?', 'Would you like coffee?'] },
      { type: 'oral', ja: '少しお時間をいただけますか。', answers: ['Could I have a minute?', 'Could I have a moment?', 'Could you give me a minute?'] },
    ],
    myself: {
      task: 'Could you 〜? で、仕事で人に頼みたいことを1文で言ってみましょう。',
      samples: ['Could you check this report by Friday?', 'Could you call me back later?'],
      checks: ['Could の後ろは動詞の原形にした'],
    },
  },
  {
    id: 'h11',
    title: '助動詞を含む受け身（can be done・must be done）',
    stage: '高校：つなぎ方と助動詞',
    sources: [
      { doc: 高, where: '第2章第1節 英語コミュニケーションⅠ 2(1)エ（イ）e 助動詞の用法（助動詞を含む受け身）', page: '38' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）j 受け身（A new gym will be built here.）', page: '51' },
    ],
    points: [
      { text: '助動詞＋be＋過去分詞で、「〜されうる」「〜されなければならない」などを表します。', en: ['These problems can be solved.', 'Something must be done.'] },
      { text: 'can be 〜「〜できる・〜されうる」、must be 〜「〜されなければならない」、should be 〜「〜されるべきだ」、will be 〜「〜されるだろう」。' },
      { text: '否定は can’t be 〜 などです。', en: ["It can't be repaired."] },
      { text: '仕事の文書やルールの説明でよく使います。', en: ['The report must be submitted by Friday.'] },
    ],
    examples: [
      { tatoeba: 3820710, en: 'These problems can be solved.' },
      { tatoeba: 3733225, en: 'Something must be done.' },
      { tatoeba: 10091493, en: "It can't be repaired." },
      { tatoeba: 271531, en: 'Stars can be seen at night.' },
      { tatoeba: 57113, en: 'This telescope must be used carefully.' },
      { tatoeba: 70762, en: 'Your prayer will be answered.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'This problem can be solve.', right: 'This problem can be solved.', note: '助動詞を含む受け身は、助動詞＋be＋過去分詞。', basis: { doc: 中, page: '51', find: 'A new gym will be built here.' }, dict: { lemma: 'solve', pos: 'verb', form: 'solved', tags: ['participle', 'past'] } },
    ],
    exercises: [
      { type: 'fill', ja: 'これらの問題は解決できる。', text: 'These problems can be ___.', choices: ['solved', 'solve', 'solving'], answers: ['solved'] },
      { type: 'fill', ja: '何か手を打たなければならない。', text: 'Something must ___ done.', choices: ['be', 'is', 'been'], answers: ['be'] },
      { type: 'fill', ja: 'それは修理できない。', text: "It can't be ___.", choices: ['repaired', 'repair', 'repairing'], answers: ['repaired'] },
      { type: 'order', ja: '報告書は金曜日までに提出しなければならない。', tokens: ['The', 'report', 'must', 'be', 'submitted', 'by', 'Friday'], answers: ['The report must be submitted by Friday.'] },
      { type: 'order', ja: '夜には星が見える。', tokens: ['Stars', 'can', 'be', 'seen', 'at', 'night'], answers: ['Stars can be seen at night.', 'At night stars can be seen.'] },
      { type: 'rewrite', ja: 'The meeting で始めて受け身にする。', from: 'We will hold the meeting next week.', answers: ['The meeting will be held next week.'] },
      { type: 'rewrite', ja: 'This machine で始めて受け身にする。', from: 'You must use this machine carefully.', answers: ['This machine must be used carefully.'] },
      { type: 'oral', ja: 'この問題はすぐに解決できます。', answers: ['This problem can be solved quickly.', 'This problem can be solved soon.', 'This problem can be solved right away.'] },
      { type: 'oral', ja: '会議は来週開かれます。', answers: ['The meeting will be held next week.'] },
      { type: 'oral', ja: 'その書類は今日中に送らなければならない。', answers: ['The documents must be sent today.', 'The document must be sent today.'] },
    ],
    myself: {
      task: '職場や学校のルールを、must be / should be＋過去分詞で1文で言ってみましょう。',
      samples: ['Expenses must be reported by the end of the month.', 'Phones should be turned off during meetings.'],
      checks: ['助動詞の後ろは be＋過去分詞にした'],
    },
  },
  {
    id: 'h12',
    title: '助動詞＋完了形（must have done・should have done）',
    stage: '高校：つなぎ方と助動詞',
    sources: [{ doc: 高, where: '第2章第1節 英語コミュニケーションⅠ 2(1)エ（イ）e 助動詞の用法（助動詞と完了形を用いた過去に関する推測の表現）', page: '38' }],
    points: [
      { text: '助動詞＋have＋過去分詞で、過去のことを推測したり、振り返ったりします。' },
      { text: 'must have 〜 は「〜したに違いない」。', en: ['He must have seen it.'] },
      { text: 'may have・might have 〜 は「〜したかもしれない」。', en: ['He may have seen it.'] },
      { text: 'should have 〜 は「〜すべきだった（のに、しなかった）」。後悔や、相手への軽い不満を表します。', en: ['I should have left earlier.'] },
      { text: 'can’t have 〜 は「〜したはずがない」。', en: ["He can't have said that."] },
      { text: '話すときは must’ve・should’ve のように短くなります。' },
    ],
    examples: [
      { tatoeba: 291492, en: 'He must have seen it.' },
      { tatoeba: 291491, en: 'He may have seen it.' },
      { tatoeba: 325194, en: 'I must have lost it.' },
      { tatoeba: 42092, en: 'That might have been true.' },
      { tatoeba: 30410, en: 'I should have left earlier.' },
      { tatoeba: 4352415, en: 'I should have said that.' },
      { tatoeba: 327534, en: 'I should not have said that.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'He must have see it.', right: 'He must have seen it.', note: 'must have の後ろは過去分詞。', basis: { doc: 高, page: '38', find: '助動詞と完了形を用いた過去に関する推測の表現' }, dict: { lemma: 'see', pos: 'verb', form: 'seen', tags: ['participle', 'past'] } },
      { kind: 'meaning', wrong: 'He must be sick.', intended: '（昨日）彼は病気だったに違いない', right: 'He must have been sick.', note: 'must be は「今〜に違いない」。過去のことの推測は must have＋過去分詞。' },
      { kind: 'meaning', wrong: 'I should study harder.', intended: 'もっと勉強すべきだった（のに、しなかった）', right: 'I should have studied harder.', note: 'should＋動詞の原形は「これから〜すべきだ」。過去の後悔は should have＋過去分詞。' },
    ],
    exercises: [
      { type: 'fill', ja: '彼はそれを見たに違いない。', text: 'He must have ___ it.', choices: ['seen', 'saw', 'see'], answers: ['seen'] },
      { type: 'fill', ja: 'もっと早く出発すべきだった。', text: 'I should ___ left earlier.', choices: ['have', 'had', 'has'], answers: ['have'] },
      { type: 'fill', ja: '彼は病気だったのかもしれない。', text: 'He may have ___ sick.', choices: ['been', 'be', 'was'], answers: ['been'] },
      { type: 'order', ja: '鍵をなくしてしまったに違いない。', tokens: ['I', 'must', 'have', 'lost', 'my', 'key'], answers: ['I must have lost my key.'] },
      { type: 'order', ja: 'そんなことを言うべきではなかった。', tokens: ['I', 'should', 'not', 'have', 'said', 'that'], answers: ['I should not have said that.'] },
      { type: 'rewrite', ja: 'must have を使って書き直す。', from: "I'm sure she went out.", answers: ['She must have gone out.'] },
      { type: 'rewrite', ja: 'should have を使って「〜すべきだった」にする。', from: "I didn't ask him. That was a mistake.", answers: ['I should have asked him.'] },
      { type: 'oral', ja: '彼は会議のことを忘れたに違いない。', answers: ['He must have forgotten about the meeting.', 'He must have forgotten the meeting.'] },
      { type: 'oral', ja: 'もっと早く言ってくれればよかったのに。', answers: ['You should have told me earlier.', 'You should have told me sooner.'] },
      { type: 'oral', ja: '私が間違えたのかもしれません。', answers: ['I may have made a mistake.', 'I might have made a mistake.'] },
    ],
    myself: {
      task: 'should have＋過去分詞で、最近の小さな後悔を1文で言ってみましょう。',
      samples: ['I should have prepared more for the meeting.', 'I should have gone to bed earlier last night.'],
      checks: ['should の後ろは have＋過去分詞にした'],
    },
  },
  {
    id: 'h13',
    title: '前置詞（前置詞＋-ing・the discovery of・in which）',
    stage: '高校：つなぎ方と助動詞',
    sources: [{ doc: 高, where: '第2章第1節 英語コミュニケーションⅠ 2(1)エ（イ）f 前置詞の用法（名詞化した動詞＋前置詞、前置詞＋動名詞や関係詞、動詞＋前置詞、前置詞を含む慣用表現）', page: '39' }],
    points: [
      { text: '前置詞の後ろに動詞を続けるときは -ing（動名詞）にします。', en: ['Knock before entering.', 'He hesitated before answering.'] },
      { text: 'look forward to 〜（〜を楽しみにする）の to も前置詞なので、後ろは名詞か -ing です。', en: ['I look forward to seeing you.'] },
      { text: '動詞から作った名詞＋of（the discovery of 〜：〜の発見）を使うと、内容を短くまとめられます。', en: ['Chance led to the discovery of the new island.'] },
      { text: '前置詞＋関係代名詞（in which など）は、where などと同じ働きをする、かたい言い方です。', en: ['The town in which I live is rather small.'] },
      { text: 'get over（乗り越える）、in addition（さらに）、at least（少なくとも）のような、前置詞を含む決まった言い方も覚えましょう。', en: ['I look forward to it.'] },
    ],
    examples: [
      { tatoeba: 2267499, en: 'Knock before entering.' },
      { tatoeba: 301972, en: 'He hesitated before answering.' },
      { tatoeba: 270056, en: 'We learn by teaching.' },
      { tatoeba: 1565471, en: 'I look forward to it.' },
      { tatoeba: 22834, en: 'We must get over many difficulties.' },
      { tatoeba: 34311, en: 'Chance led to the discovery of the new island.' },
      { tatoeba: 806629, en: 'The town in which I live is rather small.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'Thank you for come.', right: 'Thank you for coming.', note: 'for は前置詞なので、後ろの動詞は -ing にする。', basis: { doc: 高, page: '39', find: '前置詞＋動名詞や関係詞' }, dict: { lemma: 'come', pos: 'verb', form: 'coming', tags: ['participle', 'present'] } },
    ],
    exercises: [
      { type: 'fill', ja: '入る前にノックしてください。', text: 'Please knock before ___.', choices: ['entering', 'enter', 'to enter'], answers: ['entering'] },
      { type: 'fill', ja: 'お会いできるのを楽しみにしています。', text: 'I look forward to ___ you.', choices: ['seeing', 'see', 'saw'], answers: ['seeing'] },
      { type: 'fill', ja: '少なくとも10冊の本を持っている。', text: 'I have ___ least ten books.', choices: ['at', 'in', 'on'], answers: ['at'] },
      { type: 'order', ja: '来てくれてありがとう。', tokens: ['Thank', 'you', 'for', 'coming'], answers: ['Thank you for coming.'] },
      { type: 'order', ja: '私の住んでいる町は割と小さい。', tokens: ['The', 'town', 'in', 'which', 'I', 'live', 'is', 'rather', 'small'], answers: ['The town in which I live is rather small.'] },
      { type: 'rewrite', ja: 'without＋-ing を使って1文にする。', from: "He left. He didn't say goodbye.", answers: ['He left without saying goodbye.'] },
      { type: 'rewrite', ja: 'look forward to を使って「会えるのを楽しみにしている」にする。', from: "I can't wait to see you.", answers: ['I look forward to seeing you.', "I'm looking forward to seeing you."] },
      { type: 'oral', ja: 'お返事をお待ちしております。', answers: ['I look forward to hearing from you.', "I'm looking forward to hearing from you."] },
      { type: 'oral', ja: 'ご参加ありがとうございます。', answers: ['Thank you for joining us.', 'Thank you for coming.', 'Thank you for joining.'] },
      { type: 'oral', ja: '彼は何も言わずに出て行った。', answers: ['He left without saying anything.', 'He went out without saying anything.', 'He left without a word.'] },
    ],
    myself: {
      task: 'look forward to＋-ing で、楽しみにしていることを1文で言ってみましょう。',
      samples: ['I look forward to working with you.', "I'm looking forward to visiting London next year."],
      checks: ['前置詞の後ろの動詞は -ing にした'],
    },
  },
  {
    id: 'h14',
    title: '過去完了（had＋過去分詞）',
    stage: '高校：時と仮定',
    sources: [
      { doc: 高, where: '第2章第1節 英語コミュニケーションⅠ 2(1)エ（イ）g 動詞の時制及び相など（過去完了形）', page: '39' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）e〈現在完了形〉', page: '47' },
    ],
    points: [
      { text: 'had＋過去分詞で、過去のある時より前に起きていたこと（もう〜していた・〜したことがあった・ずっと〜していた）を表します。', en: ['The train had already left when I got to the station.'] },
      { text: '基準になる「過去のある時」は、when 〜 や by the time 〜（〜する時までに）で示すことが多いです。' },
      { text: '経験は「その時までに一度も〜したことがなかった」のように使います。', en: ['I had never seen her.'] },
      { text: '現在完了（修行場36〜38）の「今」を、過去のある時にずらした形と考えると分かりやすいです。' },
      { text: '話すときは I’d・he’d のように短くなります。I’d は I would の短い形と同じなので、後ろの動詞の形（過去分詞か原形か）で区別します。' },
    ],
    examples: [
      { tatoeba: 246609, en: 'The train had already left when I got to the station.' },
      { tatoeba: 51977, en: 'When we arrived at the stadium, the game had already started.' },
      { tatoeba: 244110, en: 'The bus had left by the time my wife finished dressing.' },
      { tatoeba: 308852, en: 'I had never seen her.' },
      { tatoeba: 321648, en: 'I had never seen so much money.' },
      { tatoeba: 246815, en: 'He arrived after I had left.' },
      { tatoeba: 313499, en: 'She had left the front door unlocked.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'When I got to the station, the train has already left.', right: 'When I got to the station, the train had already left.', note: '過去のある時（駅に着いた時）より前のことは、has ではなく had＋過去分詞。', basis: { doc: 高, page: '39', find: '過去完了形，過去完了進行形を加えて指導する' }, dict: { lemma: 'have', pos: 'verb', form: 'had', tags: ['past'] } },
    ],
    exercises: [
      { type: 'fill', ja: '駅に着いた時には、電車はもう出ていた。', text: 'When I got to the station, the train ___ already left.', choices: ['had', 'has', 'have'], answers: ['had'] },
      { type: 'fill', ja: 'その時まで、彼女に会ったことがなかった。', text: 'I ___ never seen her before then.', choices: ['had', 'have', 'was'], answers: ['had'] },
      { type: 'order', ja: '私たちが着いた時には、試合はもう始まっていた。', tokens: ['When', 'we', 'arrived', 'the', 'game', 'had', 'already', 'started'], answers: ['When we arrived, the game had already started.', 'The game had already started when we arrived.'] },
      { type: 'order', ja: '私が出かけたあとで、彼が着いた。', tokens: ['He', 'arrived', 'after', 'I', 'had', 'left'], answers: ['He arrived after I had left.', 'After I had left, he arrived.'] },
      { type: 'rewrite', ja: '過去完了と when を使って1文にする。', from: 'The meeting started. Then I arrived.', answers: ['The meeting had already started when I arrived.', 'When I arrived, the meeting had already started.', 'The meeting had started when I arrived.', 'When I arrived, the meeting had started.'] },
      { type: 'rewrite', ja: 'I noticed で始め、過去完了を使って1文にする。', from: 'I lost my wallet. I noticed it later.', answers: ['I noticed that I had lost my wallet.', 'I noticed I had lost my wallet.'] },
      { type: 'oral', ja: '私が電話した時には、彼はもう帰っていた。', answers: ['He had already left when I called.', 'When I called, he had already left.', 'He had already gone home when I called.', 'When I called, he had already gone home.'] },
      { type: 'oral', ja: 'それまで一度も海外に行ったことがなかった。', answers: ['I had never been abroad before.', 'I had never been abroad until then.', 'I had never been overseas before.'] },
      { type: 'oral', ja: '会議が始まる前に、資料を読み終えていた。', answers: ['I had finished reading the materials before the meeting started.', 'I had read the materials before the meeting started.', 'I had finished reading the documents before the meeting started.'] },
    ],
    myself: {
      task: '過去完了で、「〜した時には、もう…していた」という経験を1文で言ってみましょう。',
      samples: ['When I got to the office, the meeting had already started.', 'I had never used English at work until last year.'],
      checks: ['先に起きたことを had＋過去分詞にした'],
    },
  },
  {
    id: 'h15',
    title: '過去完了進行形（had been＋-ing）',
    stage: '高校：時と仮定',
    sources: [
      { doc: 高, where: '第2章第1節 英語コミュニケーションⅠ 2(1)エ（イ）g 動詞の時制及び相など（過去完了進行形）', page: '39' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）e〈現在完了進行形〉', page: '47' },
    ],
    points: [
      { text: 'had been＋-ing で、過去のある時までずっと続いていた動作を表します。', en: ['It had been snowing for a week.'] },
      { text: '「ずっと〜していたら、…した」のように、続いていた動作の途中で別のことが起きた場面でよく使います。', en: ['I had been waiting an hour when he appeared.'] },
      { text: '現在完了進行形（修行場39、have been＋-ing）の「今」を、過去のある時にずらした形です。' },
      { text: 'know・like などの状態を表す動詞は、ふつう進行形にしません。had＋過去分詞（修行場59）を使います。' },
    ],
    examples: [
      { tatoeba: 24548, en: 'He had been walking for hours.' },
      { tatoeba: 73127, en: 'It had been snowing for a week.' },
      { tatoeba: 246604, en: 'I had been waiting an hour when he appeared.' },
      { tatoeba: 254331, en: 'I had been writing letters all that morning.' },
      { tatoeba: 36443, en: 'He asked me what I had been doing.' },
      { tatoeba: 265579, en: 'The man driving the car had been drinking.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'I had been wait for an hour.', right: 'I had been waiting for an hour.', note: '過去完了進行形は had been＋-ing。', basis: { doc: 中, page: '47', find: 'Masashi and Yukio have been playing soccer for two hours.' }, dict: { lemma: 'wait', pos: 'verb', form: 'waiting', tags: ['participle', 'present'] } },
    ],
    exercises: [
      { type: 'fill', ja: '1週間ずっと雪が降り続いていた。', text: 'It had been ___ for a week.', choices: ['snowing', 'snow', 'snowed'], answers: ['snowing'] },
      { type: 'fill', ja: '彼が現れた時、私は1時間待っていた。', text: 'I had ___ waiting an hour when he appeared.', choices: ['been', 'be', 'being'], answers: ['been'] },
      { type: 'order', ja: '彼は何時間も歩き続けていた。', tokens: ['He', 'had', 'been', 'walking', 'for', 'hours'], answers: ['He had been walking for hours.'] },
      { type: 'order', ja: '彼は、私が何をしていたのかを尋ねた。', tokens: ['He', 'asked', 'me', 'what', 'I', 'had', 'been', 'doing'], answers: ['He asked me what I had been doing.'] },
      { type: 'rewrite', ja: '過去完了進行形と when を使って1文にする（3時から待ち始め、5時に彼が来た）。', from: 'I started waiting at three. He came at five.', answers: ['I had been waiting for two hours when he came.', 'When he came, I had been waiting for two hours.'] },
      { type: 'rewrite', ja: '「引っ越す前に10年間ここで働いていた」となるよう、had been を使って書き直す（before I moved は文の終わりに付ける）。', from: 'I have been working here for ten years.', answers: ['I had been working here for ten years before I moved.'] },
      { type: 'oral', ja: '彼女はその朝ずっと手紙を書いていた。', answers: ['She had been writing letters all morning.', 'She had been writing letters all that morning.'] },
      { type: 'oral', ja: '電話が鳴った時、私は2時間勉強していた。', answers: ['I had been studying for two hours when the phone rang.', 'When the phone rang, I had been studying for two hours.'] },
      { type: 'oral', ja: '私たちは何か月もその計画に取り組んでいた。', answers: ['We had been working on the project for months.', 'We had been working on the plan for months.'] },
    ],
    myself: {
      task: '過去完了進行形で、「…した時には、〜をずっと続けていた」ことを1文で言ってみましょう。',
      samples: ['I had been studying English for three years when I got this job.', 'We had been waiting for an hour when the train finally came.'],
      checks: ['had been＋-ing にした'],
    },
  },
  {
    id: 'h16',
    title: '仮定法過去完了（If I had known 〜, I would have 〜）',
    stage: '高校：時と仮定',
    sources: [
      { doc: 高, where: '第2章第1節 英語コミュニケーションⅠ 2(1)エ（イ）h 仮定法（中学校の基本的な仮定法を含め、必要なものを精選して指導する）', page: '39' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）k 仮定法のうち基本的なもの', page: '51' },
    ],
    points: [
      { text: '過去の事実と違うことを想像して「もし（あの時）〜していたら、…しただろう」は、If＋主語＋had＋過去分詞, 主語＋would / could / might＋have＋過去分詞。', en: ["If I had known that, I wouldn't have come."] },
      { text: 'would have は「〜しただろう」、could have は「〜できただろう」、might have は「〜したかもしれない」。' },
      { text: '今の事実と違うこと（修行場44）は If＋過去形, would＋原形。いつの事実と違うのかで形を選びます。' },
      { text: '過去の条件で今の結果を言うときは、後ろを would＋原形にします。', en: ["If I had taken that plane, I'd be dead now."] },
    ],
    examples: [
      { tatoeba: 8249766, en: "If I had known that, I wouldn't have come." },
      { tatoeba: 301441, en: 'If he had known about it, he would have come.' },
      { tatoeba: 30468, en: 'If you had studied harder, you would have passed the examination.' },
      { tatoeba: 30639, en: 'If I had known her address, I could have visited her.' },
      { tatoeba: 30790, en: 'If I had had enough money, I could have bought it.' },
      { tatoeba: 276977, en: 'If he had known, he might have come earlier.' },
      { tatoeba: 11184126, en: "If I had taken that plane, I'd be dead now." },
    ],
    mistakes: [
      { kind: 'meaning', wrong: 'If I knew his address, I would write to him.', intended: '（あの時）彼の住所を知っていたら、手紙を書いたのに', right: 'If I had known his address, I would have written to him.', note: 'If＋過去形は「今〜なら」。過去のことは If＋had＋過去分詞, would have＋過去分詞。' },
    ],
    exercises: [
      { type: 'fill', ja: 'それを知っていたら、来なかったのに。', text: "If I had ___ that, I wouldn't have come.", choices: ['known', 'knew', 'know'], answers: ['known'] },
      { type: 'fill', ja: 'もっと勉強していたら、合格していただろう。', text: 'If you had studied harder, you would ___ passed.', choices: ['have', 'had', 'has'], answers: ['have'] },
      { type: 'order', ja: 'お金が十分あったら、それを買えたのに。', tokens: ['If', 'I', 'had', 'had', 'enough', 'money', 'I', 'could', 'have', 'bought', 'it'], answers: ['If I had had enough money, I could have bought it.', 'I could have bought it if I had had enough money.'] },
      { type: 'order', ja: '彼は知っていたら、来ただろう。', tokens: ['If', 'he', 'had', 'known', 'he', 'would', 'have', 'come'], answers: ['If he had known, he would have come.', 'He would have come if he had known.'] },
      { type: 'rewrite', ja: 'If I had で始めて、仮定法の文にする。', from: "I didn't know her address, so I couldn't visit her.", answers: ['If I had known her address, I could have visited her.'] },
      { type: 'rewrite', ja: 'If で始めて、仮定法の文にする。', from: "It rained, so we didn't go out.", answers: ["If it hadn't rained, we would have gone out.", 'If it had not rained, we would have gone out.'] },
      { type: 'oral', ja: 'もっと早く知っていたら、手伝ったのに。', answers: ['If I had known earlier, I would have helped.', 'If I had known sooner, I would have helped.', "If I'd known earlier, I would have helped."] },
      { type: 'oral', ja: '電車に乗り遅れていなければ、間に合っていたのに。', answers: ["If I hadn't missed the train, I would have been on time.", 'If I had not missed the train, I would have been on time.'] },
      { type: 'oral', ja: 'もっと準備していたら、うまくいっていたかもしれない。', answers: ['If I had prepared more, it might have gone better.', 'If I had prepared more, it might have gone well.', 'If we had prepared more, it might have gone better.'] },
    ],
    myself: {
      task: '仮定法過去完了で、過去を振り返って1文で言ってみましょう。',
      samples: ['If I had started English earlier, I would have studied abroad.', "If I hadn't joined this company, I wouldn't have met my best friend."],
      checks: ['if の中は had＋過去分詞、後ろは would / could have＋過去分詞にした'],
    },
  },
  {
    id: 'h17',
    title: '仮定法（I wish I had 〜・as if 〜）',
    stage: '高校：時と仮定',
    sources: [
      { doc: 高, where: '第2章第1節 英語コミュニケーションⅠ 2(1)エ（イ）h 仮定法（中学校の例 I wish I knew my cat’s feelings.）', page: '39' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）k 仮定法のうち基本的なもの', page: '51' },
    ],
    points: [
      { text: 'I wish＋過去完了で「（あの時）〜していたらよかったのに」。', en: ['I wish I had bought a concert ticket.'] },
      { text: 'I wish＋過去形（修行場44）は今のことの願い、I wish＋過去完了は過去のことの後悔です。' },
      { text: '「〜してくれればよかったのに」は I wish you had＋過去分詞。', en: ['I wish you had told me the truth.'] },
      { text: 'as if＋過去形で「まるで〜であるかのように」。', en: ['He talks as if he knew everything.'] },
      { text: 'as if の中の be動詞は were が基本です（話し言葉では was も使われます）。', en: ['I feel as if I were dreaming.'] },
    ],
    examples: [
      { tatoeba: 308847, en: 'I wish I had seen her.' },
      { tatoeba: 54834, en: 'I wish I had bought a concert ticket.' },
      { tatoeba: 41837, en: 'I wish you had told me that.' },
      { tatoeba: 68830, en: 'I wish you had been there.' },
      { tatoeba: 284711, en: 'He talks as if he knew everything.' },
      { tatoeba: 255684, en: 'I feel as if I were dreaming.' },
      { tatoeba: 32319, en: 'She looks as if she were drunk.' },
    ],
    mistakes: [
      { kind: 'meaning', wrong: 'I wish I knew.', intended: '（あの時）知っていたらよかったのに', right: 'I wish I had known.', note: 'I wish I knew. は「今知っていればいいのに」。過去のことは I wish I had＋過去分詞。' },
    ],
    exercises: [
      { type: 'fill', ja: 'チケットを買っておけばよかった。', text: 'I wish I ___ bought a ticket.', choices: ['had', 'have', 'would'], answers: ['had'] },
      { type: 'fill', ja: '彼は何でも知っているかのように話す。', text: 'He talks as ___ he knew everything.', choices: ['if', 'well', 'so'], answers: ['if'] },
      { type: 'fill', ja: 'それを言ってくれればよかったのに。', text: 'I wish you had ___ me that.', choices: ['told', 'tell', 'telling'], answers: ['told'] },
      { type: 'order', ja: 'あの時、君と一緒にいたらよかったのに。', tokens: ['I', 'wish', 'I', 'had', 'been', 'with', 'you', 'then'], answers: ['I wish I had been with you then.'] },
      { type: 'order', ja: 'まるで夢を見ているような気がする。', tokens: ['I', 'feel', 'as', 'if', 'I', 'were', 'dreaming'], answers: ['I feel as if I were dreaming.'] },
      { type: 'rewrite', ja: 'I wish で始めて書き直す。', from: "I'm sorry I didn't study harder.", answers: ['I wish I had studied harder.'] },
      { type: 'rewrite', ja: 'as if を使って1文にする。', from: "He talks like the boss, but he isn't the boss.", answers: ['He talks as if he were the boss.', 'He talks as if he was the boss.'] },
      { type: 'oral', ja: 'もっと早く始めていればよかった。', answers: ['I wish I had started earlier.', 'I wish I had started sooner.'] },
      { type: 'oral', ja: '会議に出ていればよかった。', answers: ['I wish I had attended the meeting.', 'I wish I had gone to the meeting.', 'I wish I had been at the meeting.'] },
      { type: 'oral', ja: '彼女は、まるで何も起きなかったかのように振る舞った。', answers: ['She acted as if nothing had happened.', 'She behaved as if nothing had happened.'] },
    ],
    myself: {
      task: 'I wish I had＋過去分詞で、過去の後悔を1文で言ってみましょう。',
      samples: ['I wish I had studied English harder in school.', 'I wish I had taken more photos on my trip.'],
      checks: ['過去のことは had＋過去分詞にした'],
    },
  },
  {
    id: 'h18',
    title: 'it で中身をあとに回す（find it 〜 to・It is 〜 that）',
    stage: '高校：必要に応じて扱うもの',
    sources: [
      { doc: 高, where: '第2章第1節 英語コミュニケーションⅠ 2(1)エ（代名詞のうち、it が名詞用法の句及び節を指すもの：必要に応じて扱う）', page: '35' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｲ）e（b）It＋be動詞＋〜（＋for 〜）＋to 不定詞', page: '43' },
    ],
    points: [
      { text: 'It is 〜 to …（修行場31）と同じように、it を先に置き、本当の中身（to 〜・that 〜）をあとに回す言い方です。この it は「それ」と訳しません。' },
      { text: 'find it＋形容詞＋to 〜 は「〜するのは…だと分かる・感じる」。', en: ['I found it easy to speak English.'] },
      { text: 'make it clear that 〜 は「〜ということをはっきりさせる」。', en: ['She made it clear that she disagreed.'] },
      { text: 'It is＋形容詞・名詞＋that 〜 は「〜ということは…だ」。', en: ["It's true that he's ill.", "It's a pity that you can't come."] },
    ],
    examples: [
      { tatoeba: 26177, en: 'I found it easy to speak English.' },
      { tatoeba: 304421, en: 'He found it hard to make friends.' },
      { tatoeba: 43621, en: 'I found it difficult to solve the problem.' },
      { tatoeba: 953454, en: 'I found it necessary to get assistance.' },
      { tatoeba: 284133, en: "It's true that he's ill." },
      { tatoeba: 17704, en: "It's a pity that you can't come." },
      { tatoeba: 6379548, en: "It's strange that Tom hasn't come yet." },
    ],
    mistakes: [],
    exercises: [
      { type: 'fill', ja: '英語を話すのはやさしいと分かった。', text: 'I found ___ easy to speak English.', choices: ['it', 'that', 'this'], answers: ['it'] },
      { type: 'fill', ja: '君が来られないのは残念だ。', text: "It's a pity ___ you can't come.", choices: ['that', 'to', 'it'], answers: ['that'] },
      { type: 'order', ja: 'その問題を解くのは難しいと分かった。', tokens: ['I', 'found', 'it', 'difficult', 'to', 'solve', 'the', 'problem'], answers: ['I found it difficult to solve the problem.'] },
      { type: 'order', ja: '彼は友達を作るのが難しいと感じた。', tokens: ['He', 'found', 'it', 'hard', 'to', 'make', 'friends'], answers: ['He found it hard to make friends.'] },
      { type: 'rewrite', ja: 'I found it で始めて書き直す。', from: 'Working from home was easy for me.', answers: ['I found it easy to work from home.'] },
      { type: 'rewrite', ja: 'It is で始めて書き直す。', from: 'That he is ill is true.', answers: ['It is true that he is ill.', "It's true that he is ill.", "It's true that he's ill."] },
      { type: 'oral', ja: '彼の英語を理解するのは難しいと感じた。', answers: ['I found it difficult to understand his English.', 'I found it hard to understand his English.'] },
      { type: 'oral', ja: '締め切りは金曜日だとはっきり伝えました。', answers: ['I made it clear that the deadline is Friday.', 'I made it clear that the deadline was Friday.'] },
      { type: 'oral', ja: '彼がまだ来ていないのは変だ。', answers: ["It's strange that he hasn't come yet.", 'It is strange that he has not come yet.'] },
    ],
    myself: {
      task: 'I find it 〜 to … で、自分にとって簡単なこと・難しいことを1文で言ってみましょう。',
      samples: ['I find it difficult to speak English on the phone.', 'I find it easy to read emails in English.'],
      checks: ['find の後ろに it を置き、to 〜 をあとに回した'],
    },
  },
  {
    id: 'h19',
    title: '分詞構文（Feeling sick, 〜・Having finished 〜）',
    stage: '高校：必要に応じて扱うもの',
    sources: [
      { doc: 高, where: '第2章第1節 英語コミュニケーションⅠ 2(1)エ（分詞構文：必要に応じて扱う）', page: '35' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）i 現在分詞や過去分詞の形容詞としての用法', page: '50' },
    ],
    points: [
      { text: '-ing や過去分詞で始まるまとまりで、「〜して」「〜なので」「〜すると」などを短く表します。', en: ['Feeling sick, he stayed in bed.'] },
      { text: '分詞が表す動作をするのは、後ろの文の主語と同じ人・物です。', en: ['Hearing his voice, I turned around.'] },
      { text: '先に済ませたことは Having＋過去分詞で表します。', en: ['Having finished lunch, we went skating.'] },
      { text: '「〜されて」は過去分詞で始めます。', en: ['Left alone, she felt very tired.'] },
      { text: '主に書き言葉の形です。話すときは because・when・after などを使った文（修行場23・54）がふつうです。' },
    ],
    examples: [
      { tatoeba: 275225, en: 'Feeling sick, he stayed in bed.' },
      { tatoeba: 322718, en: 'Feeling sleepy, I went to bed.' },
      { tatoeba: 286977, en: 'Hearing his voice, I turned around.' },
      { tatoeba: 238156, en: 'Seeing a policeman, he ran away.' },
      { tatoeba: 277603, en: 'Having finished lunch, we went skating.' },
      { tatoeba: 280567, en: 'Left alone, she felt very tired.' },
      { tatoeba: 37763, en: 'Being very tired, I fell asleep soon.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'Felt sick, he stayed in bed.', right: 'Feeling sick, he stayed in bed.', note: '「〜なので」の意味で文の始めに置くときは、-ing の形（分詞構文）にする。', basis: { doc: 高, page: '35', find: '「分詞構文」については必要に応じて扱う' }, dict: { lemma: 'feel', pos: 'verb', form: 'feeling', tags: ['participle', 'present'] } },
      { kind: 'meaning', wrong: 'Walking in the park, a dog bit me.', intended: '公園を歩いていたら、犬にかまれた', right: 'While I was walking in the park, a dog bit me.', note: '分詞の動作をするのは後ろの文の主語なので、「犬が公園を歩いていて、私をかんだ」と読めてしまう。' },
    ],
    exercises: [
      { type: 'fill', ja: '眠くなったので、私は寝た。', text: '___ sleepy, I went to bed.', choices: ['Feeling', 'Felt', 'Feel'], answers: ['Feeling'] },
      { type: 'fill', ja: '昼食を済ませて、私たちはスケートに行った。', text: 'Having ___ lunch, we went skating.', choices: ['finished', 'finish', 'finishing'], answers: ['finished'] },
      { type: 'order', ja: '彼の声が聞こえたので、私は振り向いた。', tokens: ['Hearing', 'his', 'voice', 'I', 'turned', 'around'], answers: ['Hearing his voice, I turned around.'] },
      { type: 'order', ja: '警官を見て、彼は逃げ出した。', tokens: ['Seeing', 'a', 'policeman', 'he', 'ran', 'away'], answers: ['Seeing a policeman, he ran away.'] },
      { type: 'rewrite', ja: 'Being で始めて、分詞構文に書き直す。', from: 'Because I was very tired, I fell asleep soon.', answers: ['Being very tired, I fell asleep soon.'] },
      { type: 'rewrite', ja: 'Because で始めて、接続詞を使った文に書き直す。', from: 'Feeling sick, he stayed in bed.', answers: ['Because he felt sick, he stayed in bed.', 'Because he was feeling sick, he stayed in bed.'] },
      { type: 'oral', ja: '疲れていたので、早く寝た。（分詞構文で）', answers: ['Feeling tired, I went to bed early.', 'Being tired, I went to bed early.'] },
      { type: 'oral', ja: '仕事を終えて、彼は家に帰った。（分詞構文で）', answers: ['Having finished his work, he went home.', 'Having finished work, he went home.', 'Finishing his work, he went home.'] },
      { type: 'oral', ja: 'メールを読んで、彼女はすぐに返事をした。（分詞構文で）', answers: ['Having read the email, she replied immediately.', 'Reading the email, she replied immediately.'] },
    ],
    myself: {
      task: '分詞構文で、今日したことを1文で書いてみましょう（書き言葉の練習）。',
      samples: ['Having finished my report, I left the office.', 'Feeling hungry, I went out for lunch.'],
      checks: ['分詞の動作をするのが、後ろの文の主語と同じ人になった'],
    },
  },
]
