// 文法（フェーズ9）の中身：修行場11〜16（中学校：時制・助動詞・疑問文）。書き方は items-01-05.mjs の先頭を参照。
const 小 = '小学校学習指導要領（平成29年告示）解説 外国語活動・外国語編'
const 中 = '中学校学習指導要領（平成29年告示）解説 外国語編'

export default [
  {
    id: 'g11',
    title: '現在進行形（今〜しているところ）',
    stage: '中学校：時と助動詞',
    sources: [
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）e 動詞の時制及び相など〈現在進行形，過去進行形〉', page: '46〜47' },
    ],
    points: [
      { text: '「今〜しているところ」は be動詞（am・are・is）＋動詞の -ing 形。', en: ["I'm watching TV.", "He's studying now."] },
      { text: '-ing の付け方：ふつうはそのまま（read → reading）。e で終わる語は e を取る（make → making）。「短母音＋子音字」で終わる語は子音字を重ねる（run → running）。' },
      { text: '否定は be動詞の後ろに not、疑問文は be動詞を主語の前に出します。', en: ['Are you working?', 'What are you doing?'] },
      { text: 'ふだんの習慣は現在形、今の動作は現在進行形で言い分けます（I play tennis. ／ I’m playing tennis now.）。' },
      { text: 'know・like・want のように状態を表す動詞は、ふつう進行形にしません。' },
    ],
    examples: [
      { tatoeba: 2036345, en: "I'm watching TV." },
      { tatoeba: 593282, en: "He's studying now." },
      { tatoeba: 405767, en: "They're eating apples." },
      { tatoeba: 261644, en: 'I am studying.' },
      { tatoeba: 245411, en: 'Are you working?' },
      { tatoeba: 16492, en: 'What are you doing?' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'I am study English.', right: 'I am studying English.', note: 'be動詞の後ろは -ing 形にする。', basis: { doc: 中, page: '47', find: "My mother is talking on the phone." }, dict: { lemma: 'study', pos: 'verb', form: 'studying', tags: ['participle', 'present'] } },
      { kind: 'meaning', wrong: "I'm working at a bank.", intended: '（ずっと）銀行に勤めています', right: 'I work at a bank.', note: '進行形にすると「今のところ・一時的に」の感じが出ることがある。勤め先をふつうに言うなら現在形。' },
    ],
    exercises: [
      { type: 'fill', ja: '彼女は電話で話しているところです。', text: 'She ___ talking on the phone.', choices: ['is', 'are', 'does'], answers: ['is'] },
      { type: 'fill', ja: '私は今、夕食を作っています。', text: "I'm ___ dinner now.", choices: ['cooking', 'cook', 'cooks'], answers: ['cooking'] },
      { type: 'order', ja: '何をしているのですか。', tokens: ['What', 'are', 'you', 'doing'], answers: ['What are you doing?'] },
      { type: 'order', ja: '私たちは新しい計画について話しています。', tokens: ['We', 'are', 'talking', 'about', 'the', 'new', 'plan'], answers: ['We are talking about the new plan.'] },
      { type: 'rewrite', ja: '「今〜しているところ」の文にする。', from: 'I read a book.', answers: ['I am reading a book.', "I'm reading a book."] },
      { type: 'rewrite', ja: '「今〜しているところ」の文にする。', from: 'He writes an email.', answers: ['He is writing an email.', "He's writing an email."] },
      { type: 'oral', ja: '今、報告書を書いています。', answers: ["I'm writing the report now.", "I'm writing a report now."] },
      { type: 'oral', ja: '何をしているの？', answers: ['What are you doing?'] },
      { type: 'oral', ja: '彼は今、昼食をとっています。', answers: ["He's having lunch now.", "He's eating lunch now."] },
    ],
    myself: {
      task: '今まさにしていることを、現在進行形で1文言ってみましょう。',
      samples: ["I'm studying English now.", "I'm waiting for a train."],
      checks: ['be動詞＋-ing 形にした'],
    },
  },
  {
    id: 'g12',
    title: '過去形（〜した）',
    stage: '中学校：時と助動詞',
    sources: [
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）e 動詞の時制及び相など〈過去形〉（規則動詞と不規則動詞）', page: '46〜48' },
      { doc: 小, where: '第2部第2章第2節 2(1)エ（ｱ）f 動名詞や過去形のうち，活用頻度の高い基本的なもの', page: '95〜96' },
    ],
    points: [
      { text: '「〜した」は動詞の過去形。多くは -ed を付けます（play → played）。', en: ['We played baseball.'] },
      { text: '-ed の付け方：e で終わる語は -d（like → liked）。「子音字＋y」は y を i に変えて -ed（study → studied）。「短母音＋子音字」は子音字を重ねる（stop → stopped）。' },
      { text: '形が不規則に変わる動詞もあります：go → went、see → saw、buy → bought、meet → met、have → had など。', en: ['I met Mary yesterday.', 'I went there yesterday.'] },
      { text: '否定は didn’t＋動詞の原形、疑問文は Did＋主語＋動詞の原形。', en: ["I didn't laugh.", 'Did you win?'] },
      { text: 'be動詞の過去形は was（I、he、she、it など1人・1つ）と were（you、we、they と複数）。' },
      { text: '過去形では、主語が he や she でも -s は付けません。' },
    ],
    examples: [
      { tatoeba: 257749, en: 'I met Mary yesterday.' },
      { tatoeba: 257721, en: 'I went there yesterday.' },
      { tatoeba: 249440, en: 'We played baseball.' },
      { tatoeba: 11047477, en: 'I went shopping yesterday.' },
      { tatoeba: 2245693, en: "I didn't laugh." },
      { tatoeba: 2245260, en: 'Did you win?' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'I goed to Tokyo.', right: 'I went to Tokyo.', note: 'go の過去形は went（不規則）。', basis: { doc: 中, page: '39', find: "I went to Okinawa." }, dict: { lemma: 'go', pos: 'verb', form: 'went', tags: ['past'] } },
      { kind: 'error', wrong: 'He buyed a car.', right: 'He bought a car.', note: 'buy の過去形は bought（不規則）。', basis: { doc: 中, page: '44', find: "Yuki bought a doll that had large beautiful eyes." }, dict: { lemma: 'buy', pos: 'verb', form: 'bought', tags: ['past'] } },
      { kind: 'error', wrong: "I didn't went there.", right: "I didn't go there.", note: 'didn’t の後ろは原形（went は過去形）。', basis: { doc: 中, page: '37', find: "I didnʼt go out because it was raining." }, dict: { lemma: 'go', pos: 'verb', form: 'went', tags: ['past'] } },
      { kind: 'error', wrong: 'Did you saw him?', right: 'Did you see him?', note: 'Did の文では動詞は原形（saw は過去形）。', basis: { doc: 中, page: '37', find: "I didnʼt go out because it was raining." }, dict: { lemma: 'see', pos: 'verb', form: 'saw', tags: ['past'] } },
      { kind: 'meaning', wrong: 'I lived in Osaka.', intended: '（今も）大阪に住んでいます', right: 'I live in Osaka.', note: '過去形にすると「前は住んでいた（今は住んでいない）」と受け取られる。' },
    ],
    exercises: [
      { type: 'fill', ja: '私は先週、京都に行きました。', text: 'I ___ to Kyoto last week.', choices: ['went', 'go', 'goed'], answers: ['went'] },
      { type: 'fill', ja: '昨日彼に会いましたか。', text: 'Did you ___ him yesterday?', choices: ['see', 'saw', 'seen'], answers: ['see'] },
      { type: 'fill', ja: '私たちは昨日忙しかった。', text: 'We ___ busy yesterday.', choices: ['were', 'was', 'are'], answers: ['were'] },
      { type: 'order', ja: '私は昨日、会議に出ませんでした。', tokens: ['I', "didn't", 'attend', 'the', 'meeting', 'yesterday'], answers: ["I didn't attend the meeting yesterday.", "Yesterday I didn't attend the meeting."] },
      { type: 'rewrite', ja: 'last Sunday を加えて、過去の文にする。', from: 'I play tennis.', answers: ['I played tennis last Sunday.', 'Last Sunday I played tennis.'] },
      { type: 'rewrite', ja: '疑問文に書き直す。', from: 'She went to Osaka.', answers: ['Did she go to Osaka?'] },
      { type: 'oral', ja: '昨日、田中さんに会いました。', answers: ['I met Mr. Tanaka yesterday.', 'I saw Mr. Tanaka yesterday.'] },
      { type: 'oral', ja: '週末は何をしましたか。', answers: ['What did you do on the weekend?', 'What did you do last weekend?'] },
      { type: 'oral', ja: 'そのメールは受け取っていません（受け取らなかった）。', answers: ["I didn't get the email.", "I didn't receive the email."] },
    ],
    myself: {
      task: '昨日か先週したことを、過去形で1文言ってみましょう。',
      samples: ['I went to the gym yesterday.', 'I finished the report last week.'],
      checks: ['動詞を過去形にした（不規則な形に注意）'],
    },
  },
  {
    id: 'g13',
    title: '過去進行形（そのとき〜していた）',
    stage: '中学校：時と助動詞',
    sources: [
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）e 動詞の時制及び相など〈現在進行形，過去進行形〉', page: '47' },
    ],
    points: [
      { text: '「（そのとき）〜していた」は was / were＋動詞の -ing 形。', en: ['I was reading a book.', 'They were watching television.'] },
      { text: 'was は I・he・she・it など1人・1つ、were は you・we・they と複数。' },
      { text: '過去のある時点で途中だった動作を表します。then（そのとき）、at ten last night、when 〜（〜したとき）などとよく使います。', en: ['I was eating dinner then.'] },
      { text: '否定は was / were の後ろに not、疑問文は was / were を主語の前に出します。' },
    ],
    examples: [
      { tatoeba: 254446, en: 'I was eating dinner then.' },
      { tatoeba: 261751, en: 'I was reading a book.' },
      { tatoeba: 317686, en: 'They were watching television.' },
      { tatoeba: 248426, en: 'We were eating lunch together.' },
      { tatoeba: 2247533, en: 'I was working.' },
    ],
    mistakes: [
      { kind: 'informal', wrong: 'They was working.', right: 'They were working.', note: '地域によっては、くだけた会話で they was と言う母語話者もいるが、標準的な英語では were。正式な場面や書くときは were を使う。', dict: { lemma: 'be', pos: 'verb', form: 'was', tags: ['dialectal', 'past', 'plural'] }, spoken: { wrong: 'they was', wrongCount: 10431, right: 'they were', rightCount: 497822 } },
      { kind: 'meaning', wrong: 'I watched TV when you called.', intended: '電話をもらったとき、（ちょうど）テレビを見ていました', right: 'I was watching TV when you called.', note: '過去形の watched だと「電話をもらってから見た」とも受け取られる。途中だった動作は過去進行形。' },
    ],
    exercises: [
      { type: 'fill', ja: '私はそのとき寝ていました。', text: 'I ___ sleeping at that time.', choices: ['was', 'were', 'am'], answers: ['was'] },
      { type: 'fill', ja: '私が着いたとき、彼らは仕事をしていました。', text: 'They ___ working when I arrived.', choices: ['were', 'was', 'are'], answers: ['were'] },
      { type: 'order', ja: '電話が鳴ったとき、私は夕食を作っていました。', tokens: ['I', 'was', 'cooking', 'dinner', 'when', 'the', 'phone', 'rang'], answers: ['I was cooking dinner when the phone rang.', 'When the phone rang I was cooking dinner.'] },
      { type: 'rewrite', ja: '過去進行形にする。', from: 'They are talking.', answers: ['They were talking.'] },
      { type: 'rewrite', ja: 'at ten last night を加えて、過去進行形にする。', from: 'I read a book.', answers: ['I was reading a book at ten last night.', 'At ten last night I was reading a book.'] },
      { type: 'oral', ja: 'そのとき私は会議に出ていました。', answers: ['I was in a meeting then.', 'I was attending a meeting at that time.'] },
      { type: 'oral', ja: '何をしていたの？', answers: ['What were you doing?'] },
      { type: 'oral', ja: '私たちはその計画について話していました。', answers: ['We were talking about the plan.'] },
    ],
    myself: {
      task: '昨日の夜9時に何をしていたかを、過去進行形で1文言ってみましょう。',
      samples: ['I was watching a movie at nine last night.', 'I was working at nine last night.'],
      checks: ['was / were＋-ing 形にした'],
    },
  },
  {
    id: 'g14',
    title: '未来の表現（will・be going to・進行形）',
    stage: '中学校：時と助動詞',
    sources: [
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）e 動詞の時制及び相など〈助動詞などを用いた未来表現〉', page: '47' },
    ],
    points: [
      { text: '英語の未来は、will や be going to などを使って表します。後ろの動詞は原形。', en: ["It'll rain tomorrow.", "I'm going to go home."] },
      { text: 'will は「〜だろう（予想）」や、その場で決めた「〜します」によく使います。', en: ["I'll take it."] },
      { text: 'be going to は、前から決めている予定や、今の様子から「〜しそうだ」と言うときによく使います。' },
      { text: '近いうちの決まった予定は、現在進行形で言うこともできます。', en: ["We're going to the theater."] },
      { text: '否定は will not（won’t）、be not going to。疑問文は Will＋主語〜？ / be動詞＋主語＋going to 〜？' },
    ],
    examples: [
      { tatoeba: 5469036, en: "It'll rain tomorrow." },
      { tatoeba: 54925, en: "I'll take it." },
      { tatoeba: 2771709, en: "I'll call at seven." },
      { tatoeba: 241603, en: "I'm going to go home." },
      { tatoeba: 25927, en: "We're going to the theater." },
    ],
    mistakes: [
      { kind: 'error', wrong: 'It will rains tomorrow.', right: 'It will rain tomorrow.', note: 'will の後ろは動詞の原形。', basis: { doc: 中, page: '47', find: "I will take that yellow shirt." }, dict: { lemma: 'rain', pos: 'verb', form: 'rains', tags: ['third-person', 'singular', 'present'] } },
      { kind: 'error', wrong: "I'm going to went.", right: "I'm going to go.", note: 'going to の後ろは原形（went は過去形）。', basis: { doc: 中, page: '47', find: "We are going to play basketball after school." }, dict: { lemma: 'go', pos: 'verb', form: 'went', tags: ['past'] } },
    ],
    exercises: [
      { type: 'fill', ja: '明日は雨が降るでしょう。', text: 'It ___ rain tomorrow.', choices: ['will', 'is', 'does'], answers: ['will'] },
      { type: 'fill', ja: '私は取引先を訪ねる予定です。', text: "I'm going ___ visit the client.", choices: ['to', 'for', 'at'], answers: ['to'] },
      { type: 'order', ja: '明日、彼女に電話します。', tokens: ["I'll", 'call', 'her', 'tomorrow'], answers: ["I'll call her tomorrow.", "Tomorrow I'll call her."] },
      { type: 'order', ja: '私たちは来月、新しい店を開く予定です。', tokens: ['We', 'are', 'going', 'to', 'open', 'a', 'new', 'store', 'next', 'month'], answers: ['We are going to open a new store next month.', 'Next month we are going to open a new store.'] },
      { type: 'rewrite', ja: 'be going to と this weekend を使って予定の文にする。', from: 'I visit my parents.', answers: ["I'm going to visit my parents this weekend.", 'I am going to visit my parents this weekend.', "This weekend I'm going to visit my parents.", 'This weekend I am going to visit my parents.'] },
      { type: 'rewrite', ja: 'will と tomorrow を使って予想の文にする。', from: 'It rains.', answers: ['It will rain tomorrow.', "It'll rain tomorrow.", 'Tomorrow it will rain.', "Tomorrow it'll rain."] },
      { type: 'oral', ja: 'あとで折り返し電話します。', answers: ["I'll call you back later."] },
      { type: 'oral', ja: '来週、大阪に出張する予定です。', answers: ["I'm going to go on a business trip to Osaka next week.", "I'm going on a business trip to Osaka next week."] },
      { type: 'oral', ja: '明日は雨でしょう。', answers: ["It'll rain tomorrow.", 'It will rain tomorrow.'] },
    ],
    myself: {
      task: '週末か来週の予定を、be going to で1文言ってみましょう。',
      samples: ["I'm going to visit my parents this weekend.", "I'm going to start a new project next week."],
      checks: ['be going to＋動詞の原形にした'],
    },
  },
  {
    id: 'g15',
    title: '助動詞（may・must・should・have to）と依頼・申し出の疑問文',
    stage: '中学校：時と助動詞',
    sources: [
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）c 助動詞（can の許可・依頼、must、must not、may、should など）', page: '45〜46' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｱ）b 疑問文（May I help you? / Will you close the door? / Shall we eat out tonight?）', page: '37〜38' },
    ],
    points: [
      { text: '助動詞は動詞の前に置き、後ろの動詞は原形にします。主語が he や she でも形は変わりません。' },
      { text: 'can：〜してもいい（許可）、〜してくれる？（依頼）。may：〜してもよい（許可。can より改まった言い方）。', en: ['Can I come in?', 'May I sit here?'] },
      { text: 'must：〜しなければならない。must not：〜してはいけない（禁止）。', en: ['We must hurry.', 'You must not smoke.'] },
      { text: 'should：〜したほうがよい、〜すべきだ。', en: ['You should apologize.'] },
      { text: 'have to も「〜しなければならない」。主語が he や she なら has to。don’t have to は「〜しなくてよい」で、must not（してはいけない）とは意味がちがいます。' },
      { text: '頼むとき・申し出るとき：Will you 〜?（〜してくれますか）、Shall we 〜?（〜しましょうか）、May I 〜?（〜してもいいですか）。目上の人には Could you 〜? がより丁寧です。', en: ['Will you help me?', 'Shall we go?', 'Could you help me?'] },
    ],
    examples: [
      { tatoeba: 61514, en: 'May I sit here?' },
      { tatoeba: 427920, en: 'Can I come in?' },
      { tatoeba: 64405, en: 'Could you help me?' },
      { tatoeba: 262426, en: 'Will you help me?' },
      { tatoeba: 241078, en: 'Shall we go?' },
      { tatoeba: 16023, en: 'You should apologize.' },
      { tatoeba: 2241173, en: 'We must hurry.' },
      { tatoeba: 40654, en: 'You must not smoke.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'You should went.', right: 'You should go.', note: '助動詞の後ろは動詞の原形（went は過去形）。', basis: { doc: 中, page: '43', find: "You should keep this room clean." }, dict: { lemma: 'go', pos: 'verb', form: 'went', tags: ['past'] } },
      { kind: 'error', wrong: 'He have to work.', right: 'He has to work.', note: 'he には has to を使う。', basis: { doc: 中, page: '37', find: "Bill has a lot of CDs" }, dict: { lemma: 'have', pos: 'verb', form: 'has', tags: ['third-person', 'singular', 'present'] } },
      { kind: 'informal', wrong: "She don't have to go.", right: "She doesn't have to go.", note: '主語が he・she などのとき、くだけた会話で don’t と言う母語話者もいるが、標準的な英語では doesn’t。正式な場面や書くときは doesn’t を使う。', dict: { lemma: "don't", pos: 'verb', label: 'nonstandard', gloss: 'Does not.' }, spoken: { wrong: "she don't", wrongCount: 14045, right: "she doesn't", rightCount: 138595 } },
      { kind: 'meaning', wrong: 'You must not come tomorrow.', intended: '明日は来なくてもいいですよ', right: "You don't have to come tomorrow.", note: 'must not は「来てはいけない」（禁止）。「しなくてよい」は don’t have to。' },
    ],
    exercises: [
      { type: 'fill', ja: 'この部屋を使ってもいいですか。', text: '___ I use this room?', choices: ['May', 'Must', 'Shall'], answers: ['May'] },
      { type: 'fill', ja: '明日はスーツを着なくていいですよ。私服の日です。', text: "You ___ wear a suit tomorrow. It's casual.", choices: ["don't have to", 'must not', 'must'], answers: ["don't have to"] },
      { type: 'fill', ja: '急がなければなりません。電車がもうすぐ出ます。', text: 'We ___ hurry. The train leaves soon.', choices: ['must', 'may', 'shall'], answers: ['must'] },
      { type: 'order', ja: '会議を始めましょうか。', tokens: ['Shall', 'we', 'start', 'the', 'meeting'], answers: ['Shall we start the meeting?'] },
      { type: 'order', ja: '医者に診てもらったほうがいいですよ。', tokens: ['You', 'should', 'see', 'a', 'doctor'], answers: ['You should see a doctor.'] },
      { type: 'rewrite', ja: 'have to を使って「〜しなければならない」の文にする。', from: 'I work on Saturday.', answers: ['I have to work on Saturday.', 'On Saturday I have to work.'] },
      { type: 'rewrite', ja: 'Could you で始めて、丁寧な依頼にする。', from: 'Open the window.', answers: ['Could you open the window?', 'Could you open the window, please?', 'Could you please open the window?'] },
      { type: 'oral', ja: '入ってもいいですか。', answers: ['May I come in?', 'Can I come in?'] },
      { type: 'oral', ja: '手伝っていただけますか。', answers: ['Could you help me?', 'Can you help me?'] },
      { type: 'oral', ja: '明日は来なくていいですよ。', answers: ["You don't have to come tomorrow."] },
      { type: 'oral', ja: 'もう行かなければなりません。', answers: ['I have to go now.', 'I must go now.'] },
    ],
    myself: {
      task: '今日か今週しなければならないことを、have to で1文言ってみましょう。',
      samples: ['I have to finish a report today.', 'I have to call a client this afternoon.'],
      checks: ['have to（he・she なら has to）＋動詞の原形にした'],
    },
  },
  {
    id: 'g16',
    title: 'which・whose と「AかBか」の疑問文',
    stage: '中学校：時と助動詞',
    sources: [
      { doc: 中, where: '第2章第2節 2(1)エ（ｱ）b 疑問文のうち，or を含むもの，疑問詞（which，whose）で始まるもの', page: '37〜38' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）a（a）疑問を表す代名詞（which，whose）', page: '44' },
    ],
    points: [
      { text: 'which は「どちら・どれ」。限られたものの中から選ぶときに使います。名詞の前に置いて「どの〜」とも言えます。', en: ['Which is cheaper?', 'Which tooth hurts?'] },
      { text: 'whose は「誰の」。名詞の前に置くか、1語で「誰のもの」。', en: ['Whose is this?', 'Whose are these?'] },
      { text: '「AかBか」は or で聞きます。答えは Yes / No ではなく、どちらかを選んで答えます。', en: ['Would you like coffee or tea?'] },
      { text: '「A か B か」の疑問文は、A を上げ、B で下げて言うのがふつうです。' },
    ],
    examples: [
      { tatoeba: 38002, en: 'Which is mine?' },
      { tatoeba: 4495206, en: 'Which is cheaper?' },
      { tatoeba: 403281, en: 'Which tooth hurts?' },
      { tatoeba: 2302, en: 'Whose is this?' },
      { tatoeba: 4095981, en: 'Whose are these?' },
      { tatoeba: 62273, en: 'Would you like coffee or tea?' },
      { tatoeba: 1080170, en: 'Coffee or tea?' },
    ],
    mistakes: [
      { kind: 'error', wrong: "Who's bag is this?", right: 'Whose bag is this?', note: '「誰の」は whose。who’s は who is。', basis: { doc: 中, page: '38', find: "Whose idea is this?" }, dict: { lemma: 'whose', pos: 'det', gloss: 'Of whom, belonging to whom' } },
      { kind: 'meaning', wrong: '"Would you like tea or coffee?" "Yes."', intended: '紅茶をお願いします', right: '"Would you like tea or coffee?" "Tea, please."', note: 'どちらかを選ぶ疑問文に Yes と答えても、どちらがほしいか伝わらない。' },
    ],
    exercises: [
      { type: 'fill', ja: 'これは誰のかばんですか。—私のです。', text: "___ bag is this? — It's mine.", choices: ['Whose', 'Who', 'Which'], answers: ['Whose'] },
      { type: 'fill', ja: '夏と冬、どちらが好きですか。', text: '___ do you like better, summer or winter?', choices: ['Which', 'Whose', 'Who'], answers: ['Which'] },
      { type: 'order', ja: 'どの部屋が会議室ですか。', tokens: ['Which', 'room', 'is', 'the', 'meeting', 'room'], answers: ['Which room is the meeting room?'] },
      { type: 'order', ja: '紅茶とコーヒー、どちらになさいますか。', tokens: ['Would', 'you', 'like', 'tea', 'or', 'coffee'], answers: ['Would you like tea or coffee?'] },
      { type: 'rewrite', ja: 'Ken’s（誰の）をたずねる疑問文にする。', from: "This is Ken's umbrella.", answers: ['Whose umbrella is this?'] },
      { type: 'rewrite', ja: 'the red one（どれ）をたずねる疑問文にする。', from: 'You want the red one.', answers: ['Which one do you want?'] },
      { type: 'oral', ja: 'どちらの案がいいと思いますか。', answers: ['Which plan do you think is better?', 'Which idea do you think is better?'] },
      { type: 'oral', ja: 'これは誰のパソコンですか。', answers: ['Whose computer is this?', 'Whose laptop is this?'] },
      { type: 'oral', ja: '電車で行きますか、それともバスで行きますか。', answers: ['Will you go by train or by bus?', 'Are you going by train or by bus?'] },
    ],
    myself: {
      task: '「AとBどちらが好き？」と自分に聞いて、自分のことで答えてみましょう。',
      samples: ['Which do you like better, tea or coffee? — I like coffee better.', 'Which do you prefer, morning or evening? — I prefer mornings.'],
      checks: ['質問は Which で始め、答えは Yes / No ではなく片方を選んだ'],
    },
  },
]
