// 文法（フェーズ9）の中身：修行場27〜35（中学校：不定詞・動名詞・比較・受け身）。書き方は items-01-05.mjs の先頭を参照。
const 小 = '小学校学習指導要領（平成29年告示）解説 外国語活動・外国語編'
const 中 = '中学校学習指導要領（平成29年告示）解説 外国語編'

export default [
  {
    id: 'g27',
    title: 'to 不定詞（〜すること）',
    stage: '中学校：不定詞・動名詞',
    sources: [
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）g to 不定詞〈名詞としての用法〉', page: '48〜49' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｲ）b［主語＋動詞＋目的語］（a）主語＋動詞＋to 不定詞', page: '40〜41' },
      { doc: 小, where: '第2部第2章第2節 2(1)エ（ｲ）c（want＋to 不定詞：I want to go to Italy.）', page: '97' },
    ],
    points: [
      { text: 'to＋動詞の原形で「〜すること」。want・hope・decide・need・try・like などの後ろに置きます。', en: ['I want to drive.', 'I need to study.'] },
      { text: 'want to 〜：〜したい。hope to 〜：〜することを望む。decide to 〜：〜することに決める。try to 〜：〜しようとする。need to 〜：〜する必要がある。' },
      { text: 'to の後ろはいつも動詞の原形（主語が he でも、過去の文でも）。', en: ['I tried to escape.'] },
      { text: '「〜することは…だ」と文の主語にもできますが、話すときは It is … to 〜 の形（修行場31）をよく使います。', en: ['To master English is hard.'] },
    ],
    examples: [
      { tatoeba: 258396, en: 'I want to drive.' },
      { tatoeba: 256172, en: 'I like to swim.' },
      { tatoeba: 259696, en: 'I tried to escape.' },
      { tatoeba: 400128, en: 'I need to study.' },
      { tatoeba: 26218, en: 'To master English is hard.' },
    ],
    mistakes: [],
    exercises: [
      { type: 'fill', ja: 'いつか海外で働きたい。', text: 'I want ___ abroad someday.', choices: ['to work', 'work', 'working'], answers: ['to work'] },
      { type: 'fill', ja: '私たちは会議を延期することにしました。', text: 'We decided ___ the meeting.', choices: ['to postpone', 'postpone', 'postponing'], answers: ['to postpone'] },
      { type: 'order', ja: '私は英語を上手に話せるようになりたい。', tokens: ['I', 'want', 'to', 'speak', 'English', 'well'], answers: ['I want to speak English well.'] },
      { type: 'order', ja: '彼はその試験に合格しようとしました。', tokens: ['He', 'tried', 'to', 'pass', 'the', 'exam'], answers: ['He tried to pass the exam.'] },
      { type: 'rewrite', ja: 'want to を使って「〜したい」の文にする。', from: 'I travel abroad.', answers: ['I want to travel abroad.'] },
      { type: 'rewrite', ja: 'decided to を使って「〜することに決めた」の文にする。', from: 'She studies French.', answers: ['She decided to study French.'] },
      { type: 'oral', ja: '新しいことに挑戦したいです。', answers: ['I want to try something new.'] },
      { type: 'oral', ja: 'もっと練習する必要があります。', answers: ['I need to practice more.'] },
      { type: 'oral', ja: '来年、昇進したいと思っています。', answers: ['I hope to get a promotion next year.', 'I want to get promoted next year.'] },
    ],
    myself: {
      task: 'want to 〜 で、将来してみたい仕事や挑戦を1文言ってみましょう。',
      samples: ['I want to work abroad someday.', 'I want to lead a big project.'],
      checks: ['to の後ろは動詞の原形にした'],
    },
  },
  {
    id: 'g28',
    title: 'to 不定詞（〜するための・〜するために・〜して）',
    stage: '中学校：不定詞・動名詞',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｳ）g to 不定詞〈形容詞としての用法〉〈副詞としての用法〉', page: '49' }],
    points: [
      { text: '名詞の後ろに to＋動詞の原形 を置くと「〜するための・〜すべき」。', en: ['I want something to drink.', 'I have nothing to say.'] },
      { text: '動詞の後に to＋原形 を続けると「〜するために」（目的）。', en: ['He went to America to study English.'] },
      { text: 'glad・sorry・surprised などの後ろに to＋原形 を続けると「〜して（うれしい・残念だ）」（気持ちの理由）。', en: ["I'm glad to see you.", "I'm sorry to hear that."] },
      { text: 'どれも to の後ろは動詞の原形です。' },
    ],
    examples: [
      { tatoeba: 25192, en: 'I want something to drink.' },
      { tatoeba: 249876, en: 'I have nothing to say.' },
      { tatoeba: 256237, en: 'He went to America to study English.' },
      { tatoeba: 249354, en: 'We go to school to study.' },
      { tatoeba: 22588, en: "I'm glad to see you." },
      { tatoeba: 41762, en: "I'm sorry to hear that." },
    ],
    mistakes: [],
    exercises: [
      { type: 'fill', ja: '今日はやらなければならない仕事がたくさんあります。', text: 'I have a lot of work ___ today.', choices: ['to do', 'do', 'doing'], answers: ['to do'] },
      { type: 'fill', ja: '彼は日本語を学ぶために日本に来ました。', text: 'He came to Japan ___ Japanese.', choices: ['to study', 'study', 'studied'], answers: ['to study'] },
      { type: 'order', ja: '何か飲み物がほしいです。', tokens: ['I', 'want', 'something', 'to', 'drink'], answers: ['I want something to drink.'] },
      { type: 'order', ja: 'お会いできてうれしいです。', tokens: ["I'm", 'glad', 'to', 'meet', 'you'], answers: ["I'm glad to meet you."] },
      { type: 'rewrite', ja: 'to 不定詞で1文にする（「お金をおろすために銀行に行った」）。', from: 'I went to the bank. I wanted to get some money.', answers: ['I went to the bank to get some money.'] },
      { type: 'rewrite', ja: 'to 不定詞で1文にする（「本を読む時間がない」）。', from: 'I have no time. I want to read books.', answers: ['I have no time to read books.'] },
      { type: 'oral', ja: '今日はやることがたくさんあります。', answers: ['I have a lot of things to do today.', 'I have a lot to do today.'] },
      { type: 'oral', ja: 'それは残念です（それを聞いて残念です）。', answers: ["I'm sorry to hear that."] },
      { type: 'oral', ja: '取引先に会うために大阪へ行きました。', answers: ['I went to Osaka to meet a client.', 'I went to Osaka to see a client.'] },
    ],
    myself: {
      task: '英語を勉強する目的を、to＋動詞の原形 で1文言ってみましょう。',
      samples: ['I study English to talk with overseas clients.', 'I study English to travel around the world.'],
      checks: ['to の後ろは動詞の原形にした'],
    },
  },
  {
    id: 'g29',
    title: '動名詞（〜すること：-ing）',
    stage: '中学校：不定詞・動名詞',
    sources: [
      { doc: 中, where: '第2章第2節 2(1)エ（ｳ）h 動名詞', page: '49' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｲ）b［主語＋動詞＋目的語］（a）主語＋動詞＋動名詞', page: '40〜41' },
      { doc: 小, where: '第2部第2章第2節 2(1)エ（ｱ）f（I am good at swimming. / I enjoyed fishing.）', page: '95〜96' },
    ],
    points: [
      { text: '動詞の -ing 形で「〜すること」。文の主語にも、動詞の後ろにも置けます。', en: ['Speaking English is useful.', 'I like traveling.'] },
      { text: 'enjoy・finish・stop の後ろは -ing 形にします。', en: ['We enjoyed skating.', 'I stopped smoking.'] },
      { text: '前置詞（at・for・about など）の後ろに動詞を続けるときも -ing 形にします。', en: ["I'm good at skiing."] },
      { text: 'like・love・start は、-ing 形と to 不定詞のどちらも続けられます（I like swimming. / I like to swim.）。' },
    ],
    examples: [
      { tatoeba: 248027, en: 'We enjoyed skating.' },
      { tatoeba: 254971, en: 'I stopped smoking.' },
      { tatoeba: 262205, en: 'I like traveling.' },
      { tatoeba: 26187, en: 'Speaking English is useful.' },
      { tatoeba: 324087, en: 'Playing baseball is fun.' },
      { tatoeba: 253954, en: "I'm good at skiing." },
    ],
    mistakes: [
      { kind: 'meaning', wrong: 'I stopped to smoke.', intended: 'たばこをやめました', right: 'I stopped smoking.', note: 'stop to smoke は「たばこを吸うために立ち止まった（手を止めた）」の意味になる。' },
    ],
    exercises: [
      { type: 'fill', ja: 'お話しできて楽しかったです。', text: 'I enjoyed ___ with you.', choices: ['talking', 'to talk', 'talk'], answers: ['talking'] },
      { type: 'fill', ja: 'お招きいただきありがとうございます。', text: 'Thank you for ___ me.', choices: ['inviting', 'invite', 'to invite'], answers: ['inviting'] },
      { type: 'order', ja: '英語を話すのは楽しい。', tokens: ['Speaking', 'English', 'is', 'fun'], answers: ['Speaking English is fun.'] },
      { type: 'order', ja: '彼は報告書を書き終えました。', tokens: ['He', 'finished', 'writing', 'the', 'report'], answers: ['He finished writing the report.'] },
      { type: 'rewrite', ja: 'Swimming で始めて1文にする。', from: 'I swim. It is fun.', answers: ['Swimming is fun.'] },
      { type: 'rewrite', ja: 'to 不定詞を動名詞に変えて書き直す。', from: 'I like to cook.', answers: ['I like cooking.'] },
      { type: 'oral', ja: 'お話しできて楽しかったです。', answers: ['I enjoyed talking with you.'] },
      { type: 'oral', ja: 'お招きいただきありがとうございます。', answers: ['Thank you for inviting me.'] },
      { type: 'oral', ja: '私はプレゼンが得意ではありません。', answers: ["I'm not good at giving presentations.", "I'm not good at making presentations."] },
    ],
    myself: {
      task: 'I’m good at 〜ing か I like 〜ing で、自分の得意なこと・好きなことを1文言ってみましょう。',
      samples: ["I'm good at making plans.", 'I like reading business books.'],
      checks: ['at・for などの後ろ、enjoy・finish の後ろは -ing 形にした'],
    },
  },
  {
    id: 'g30',
    title: '疑問詞＋to 不定詞（how to など）',
    stage: '中学校：不定詞・動名詞',
    sources: [
      { doc: 中, where: '第2章第2節 2(1)エ（ｲ）b［主語＋動詞＋目的語］（a）主語＋動詞＋how（など）to 不定詞', page: '40〜41' },
      { doc: 中, where: '第2章第2節 2(1)エ（ｲ）c［主語＋動詞＋間接目的語＋直接目的語］（b）主語＋動詞＋間接目的語＋how（など）to 不定詞', page: '41〜42' },
    ],
    points: [
      { text: 'how to 〜：〜のしかた。what to 〜：何を〜すべきか。where to 〜：どこで（へ）〜すべきか。when to 〜：いつ〜すべきか。', en: ['I know how to swim.', 'I know what to do.'] },
      { text: 'know・learn などの後ろや、tell・show・teach＋人 の後ろに置けます。', en: ['Tell me when to start.', 'She taught me how to swim.'] },
      { text: '仕事で「〜のしかたを教えてください」と頼むときによく使います（Could you show me how to 〜?）。' },
    ],
    examples: [
      { tatoeba: 256170, en: 'I know how to swim.' },
      { tatoeba: 256407, en: 'I know what to do.' },
      { tatoeba: 24758, en: 'Tell me what to do.' },
      { tatoeba: 65995, en: 'Tell me when to start.' },
      { tatoeba: 314186, en: 'She taught me how to swim.' },
      { tatoeba: 1867862, en: 'Tom taught me how to cook.' },
    ],
    mistakes: [],
    exercises: [
      { type: 'fill', ja: 'この機械の使い方を知っていますか。', text: 'Do you know ___ to use this machine?', choices: ['how', 'what', 'where'], answers: ['how'] },
      { type: 'fill', ja: '何と言えばいいかわかりません。', text: "I don't know ___ to say.", choices: ['what', 'how', 'when'], answers: ['what'] },
      { type: 'order', ja: 'どこで降りればいいか教えてください。', tokens: ['Please', 'tell', 'me', 'where', 'to', 'get', 'off'], answers: ['Please tell me where to get off.'] },
      { type: 'order', ja: '彼女は私に表計算ソフトの使い方を教えてくれました。', tokens: ['She', 'showed', 'me', 'how', 'to', 'use', 'the', 'spreadsheet'], answers: ['She showed me how to use the spreadsheet.'] },
      { type: 'rewrite', ja: 'I don’t know what to で始めて書き直す。', from: 'What should I do?', answers: ["I don't know what to do."] },
      { type: 'rewrite', ja: 'Could you tell me how to で始めて書き直す。', from: 'How can I get to the station?', answers: ['Could you tell me how to get to the station?'] },
      { type: 'oral', ja: 'このコピー機の使い方を教えていただけますか。', answers: ['Could you show me how to use this copier?', 'Could you tell me how to use this copy machine?'] },
      { type: 'oral', ja: '何と言えばいいかわかりません。', answers: ["I don't know what to say."] },
      { type: 'oral', ja: 'いつ始めればいいか教えてください。', answers: ['Please tell me when to start.'] },
    ],
    myself: {
      task: '最近できるようになったことを、I learned how to 〜 で1文言ってみましょう。',
      samples: ['I learned how to make a pivot table.', 'I learned how to cook curry.'],
      checks: ['how to＋動詞の原形 にした'],
    },
  },
  {
    id: 'g31',
    title: 'It is …（for 人）to 〜（〜するのは…だ）',
    stage: '中学校：不定詞・動名詞',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｲ）e（b）It＋be動詞＋〜（＋for〜）＋to 不定詞', page: '43' }],
    points: [
      { text: '「〜するのは…だ」は It is …＋to＋動詞の原形。it は後ろの to 〜 を指します（「それ」とは訳さない）。', en: ["It's fun to travel.", "It's easy to use."] },
      { text: '「（人）にとって」を入れるときは to の前に for＋人。', en: ['It is easy for me to swim.'] },
      { text: '…には easy・hard・difficult・important・necessary・fun・nice などがよく入ります。' },
      { text: '過去のことは It was …、これからのことは It will be … にします。' },
    ],
    examples: [
      { tatoeba: 325560, en: "It's fun to travel." },
      { tatoeba: 2182396, en: "It's hard to believe." },
      { tatoeba: 12281012, en: "It's easy to use." },
      { tatoeba: 26217, en: "It's hard to master English." },
      { tatoeba: 26404, en: 'It is easy for me to swim.' },
      { tatoeba: 16156, en: 'It is necessary for you to go.' },
    ],
    mistakes: [],
    exercises: [
      { type: 'fill', ja: '細かい点を確認することが大切です。', text: "It's important ___ check the details.", choices: ['to', 'for', 'of'], answers: ['to'] },
      { type: 'fill', ja: '人前で話すのは私には難しい。', text: "It's difficult ___ me to speak in public.", choices: ['for', 'of', 'to'], answers: ['for'] },
      { type: 'order', ja: '英語で話すのは私には難しい。', tokens: ['It', 'is', 'difficult', 'for', 'me', 'to', 'speak', 'in', 'English'], answers: ['It is difficult for me to speak in English.'] },
      { type: 'order', ja: '毎日運動することは大切です。', tokens: ['It', 'is', 'important', 'to', 'exercise', 'every', 'day'], answers: ['It is important to exercise every day.'] },
      { type: 'rewrite', ja: 'It で始めて書き直す。', from: 'To use this app is easy.', answers: ['It is easy to use this app.', "It's easy to use this app."] },
      { type: 'rewrite', ja: 'It is fun for me to で始めて書き直す。', from: 'Learning English is fun for me.', answers: ['It is fun for me to learn English.'] },
      { type: 'oral', ja: '締め切りを守ることが大切です。', answers: ['It is important to meet the deadline.', "It's important to meet deadlines."] },
      { type: 'oral', ja: 'お会いできてよかったです。', answers: ['It was nice to meet you.', "It's nice to meet you."] },
      { type: 'oral', ja: '私にはそれを1日で終えるのは無理です。', answers: ["It's impossible for me to finish it in a day.", 'It is impossible for me to finish it in one day.'] },
    ],
    myself: {
      task: 'It is … for me to 〜 で、自分にとって難しいこと・楽しいことを1文言ってみましょう。',
      samples: ['It is hard for me to get up early.', 'It is fun for me to talk with new people.'],
      checks: ['It is …＋for＋人＋to＋動詞の原形 の順にした'],
    },
  },
  {
    id: 'g32',
    title: '「人に〜してほしい・するよう言う」（want・tell・ask＋人＋to 〜）',
    stage: '中学校：不定詞・動名詞',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｲ）e（c）主語＋tell，want など＋目的語＋to 不定詞', page: '43' }],
    points: [
      { text: 'want＋人＋to＋原形：人に〜してほしい。', en: ['I want you to go.', 'I wanted her to win.'] },
      { text: 'tell＋人＋to＋原形：人に〜するように言う。ask＋人＋to＋原形：人に〜するように頼む。', en: ['Please tell him to wait.', 'She told him to study.'] },
      { text: '人は me・him・her・us・them の形にします。' },
      { text: '丁寧に頼むときは I would like you to 〜（I’d like you to 〜）と言うこともできます。' },
    ],
    examples: [
      { tatoeba: 17473, en: 'I want you to go.' },
      { tatoeba: 308896, en: 'I wanted her to win.' },
      { tatoeba: 17493, en: 'I want you to work harder.' },
      { tatoeba: 464989, en: 'Please tell him to wait.' },
      { tatoeba: 887460, en: 'She told him to study.' },
      { tatoeba: 1867794, en: 'Tom wants me to apologize.' },
    ],
    mistakes: [
      { kind: 'meaning', wrong: 'I want to call you.', intended: 'あなたに電話してほしい', right: 'I want you to call me.', note: 'I want to call you. は「私があなたに電話したい」。してほしい相手は want の直後に置く。' },
    ],
    exercises: [
      { type: 'fill', ja: 'あなたに会議に参加してほしい。', text: 'I want ___ to join the meeting.', choices: ['you', 'your', 'for you'], answers: ['you'] },
      { type: 'fill', ja: '上司は私に金曜日までに報告書を仕上げるよう言いました。', text: 'My boss told me ___ the report by Friday.', choices: ['to finish', 'finish', 'finishing'], answers: ['to finish'] },
      { type: 'order', ja: '彼に折り返し電話するよう伝えてください。', tokens: ['Please', 'tell', 'him', 'to', 'call', 'me', 'back'], answers: ['Please tell him to call me back.'] },
      { type: 'order', ja: '私は彼女に手伝ってくれるよう頼みました。', tokens: ['I', 'asked', 'her', 'to', 'help', 'me'], answers: ['I asked her to help me.'] },
      { type: 'rewrite', ja: 'I want で始めて「あなたに早く来てほしい」の文にする。', from: 'You come early.', answers: ['I want you to come early.'] },
      { type: 'rewrite', ja: 'told を使って書き直す。', from: 'He said to me, "Wait here."', answers: ['He told me to wait here.'] },
      { type: 'oral', ja: '明日までにお返事をいただきたいのですが。', answers: ["I'd like you to reply by tomorrow.", 'I want you to reply by tomorrow.'] },
      { type: 'oral', ja: '彼女に会議室を予約するよう頼みました。', answers: ['I asked her to book the meeting room.', 'I asked her to reserve the meeting room.'] },
      { type: 'oral', ja: '上司に早く帰るように言われました。', answers: ['My boss told me to go home early.'] },
    ],
    myself: {
      task: '同僚か家族にしてほしいことを、I want＋人＋to 〜 で1文言ってみましょう。',
      samples: ['I want my team to share ideas more.', 'I want my family to try my cooking.'],
      checks: ['want＋人＋to＋動詞の原形 の順にした'],
    },
  },
  {
    id: 'g33',
    title: '比較級・最上級（〜より…・一番…）',
    stage: '中学校：比べる・される',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｳ）f 形容詞や副詞を用いた比較表現', page: '48' }],
    points: [
      { text: '2つを比べて「〜より…」は 比較級＋than。3つ以上の中で「一番…」は the＋最上級。', en: ['Tom is taller than I.', 'Tokyo is the largest city in Japan.'] },
      { text: '短い語は -er・-est（tall → taller → tallest）。長い語は more・most を前に置く（important → more important → most important）。', en: ['Health is more important than money.'] },
      { text: '形が変わる語：good・well → better → best、bad → worse → worst、many・much → more → most。', en: ['Laughter is the best medicine.'] },
      { text: '最上級の後ろは、場所や集団なら in（in Japan、in the class）、複数のものなら of（of the three）。' },
      { text: 'more と -er を重ねて使うことはしません（more taller とは言わない）。' },
    ],
    examples: [
      { tatoeba: 37109, en: 'Tom is taller than I.' },
      { tatoeba: 55961, en: 'This is smaller than that.' },
      { tatoeba: 238981, en: 'Health is more important than money.' },
      { tatoeba: 55960, en: 'This is more expensive than that.' },
      { tatoeba: 279794, en: 'Tokyo is the largest city in Japan.' },
      { tatoeba: 1229089, en: "I'm the tallest one in the class." },
      { tatoeba: 268199, en: 'Laughter is the best medicine.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'He is more taller than his brother.', right: 'He is taller than his brother.', note: 'taller だけで比較級。more は付けない。', dict: { lemma: 'tall', pos: 'adj', form: 'taller', tags: ['comparative'] } },
      { kind: 'error', wrong: 'This is the most biggest.', right: 'This is the biggest.', note: 'biggest だけで最上級。most は付けない。', dict: { lemma: 'big', pos: 'adj', form: 'biggest', tags: ['superlative'] } },
      { kind: 'error', wrong: 'She is tall than her sister.', right: 'She is taller than her sister.', note: 'than の前は比較級にする。', dict: { lemma: 'tall', pos: 'adj', form: 'taller', tags: ['comparative'] } },
    ],
    exercises: [
      { type: 'fill', ja: 'この案はあの案より安い。', text: 'This plan is ___ than that one.', choices: ['cheaper', 'cheap', 'cheapest'], answers: ['cheaper'] },
      { type: 'fill', ja: 'これが一番大事な点です。', text: 'This is the ___ important point.', choices: ['most', 'more', 'best'], answers: ['most'] },
      { type: 'fill', ja: '彼女は私より英語を上手に話します。', text: 'She speaks English ___ than me.', choices: ['better', 'good', 'best'], answers: ['better'] },
      { type: 'order', ja: 'こちらはあちらより値段が高い。', tokens: ['This', 'is', 'more', 'expensive', 'than', 'that'], answers: ['This is more expensive than that.'] },
      { type: 'order', ja: '東京は日本で一番大きい都市です。', tokens: ['Tokyo', 'is', 'the', 'largest', 'city', 'in', 'Japan'], answers: ['Tokyo is the largest city in Japan.'] },
      { type: 'rewrite', ja: 'than that one を加えて比較級の文にする。', from: 'This room is big.', answers: ['This room is bigger than that one.'] },
      { type: 'rewrite', ja: 'of the three を加えて最上級の文にする。', from: 'This is a good plan.', answers: ['This is the best plan of the three.'] },
      { type: 'oral', ja: 'こちらのほうが安いです。', answers: ['This one is cheaper.', 'This is cheaper.'] },
      { type: 'oral', ja: 'それが一番大事な点です。', answers: ["That's the most important point.", 'That is the most important point.'] },
      { type: 'oral', ja: '前回よりよくなりました。', answers: ["It's better than last time."] },
    ],
    myself: {
      task: '比較級か最上級で、自分の好みを1文言ってみましょう。',
      samples: ['I like summer better than winter.', 'Sushi is my favorite food. It is the best food in the world.'],
      checks: ['比較級は than、最上級は the を付けた'],
    },
  },
  {
    id: 'g34',
    title: 'as … as（同じくらい…・〜ほど…ない）',
    stage: '中学校：比べる・される',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｳ）f 形容詞や副詞を用いた比較表現（原級を用いた文：My town is as large as yours.）', page: '48' }],
    points: [
      { text: 'as＋形容詞・副詞の元の形＋as で「〜と同じくらい…」。', en: ["I'm as tall as you.", "She's as busy as Tom."] },
      { text: 'not as … as で「〜ほど…ない」。', en: ["I'm not as tall as you."] },
      { text: 'as … as possible、as … as 主語＋can で「できるだけ…」。仕事でよく使います。', en: ['Come as soon as possible.', 'Run as fast as you can.'] },
      { text: 'twice as … as で「〜の2倍…」と言えます。' },
    ],
    examples: [
      { tatoeba: 252720, en: "I'm as tall as you." },
      { tatoeba: 311824, en: "She's as busy as Tom." },
      { tatoeba: 252886, en: "I'm not as tall as you." },
      { tatoeba: 1418242, en: "I'm not as intelligent as him." },
      { tatoeba: 39515, en: 'Come as soon as possible.' },
      { tatoeba: 39510, en: 'Run as fast as you can.' },
    ],
    mistakes: [],
    exercises: [
      { type: 'fill', ja: 'この部屋はあの部屋と同じくらい広い。', text: 'This room is as large ___ that one.', choices: ['as', 'than', 'so'], answers: ['as'] },
      { type: 'fill', ja: 'できるだけ早くお返事ください。', text: 'Please reply as soon as ___.', choices: ['possible', 'possibly', 'can'], answers: ['possible'] },
      { type: 'order', ja: '彼は私ほど背が高くありません。', tokens: ['He', 'is', 'not', 'as', 'tall', 'as', 'me'], answers: ['He is not as tall as me.'] },
      { type: 'order', ja: 'できるだけ早く来てください。', tokens: ['Please', 'come', 'as', 'soon', 'as', 'possible'], answers: ['Please come as soon as possible.', 'Come as soon as possible, please.'] },
      { type: 'rewrite', ja: 'as … as を使って「私のかばんはあなたのと同じくらい軽い」にする。', from: 'My bag is light. Your bag is light too.', answers: ['My bag is as light as yours.', 'My bag is as light as your bag.'] },
      { type: 'rewrite', ja: 'Ken を主語にして not as … as の文にする。', from: 'Tom is taller than Ken.', answers: ['Ken is not as tall as Tom.', "Ken isn't as tall as Tom."] },
      { type: 'oral', ja: 'できるだけ早くお返事します。', answers: ["I'll reply as soon as possible.", "I'll get back to you as soon as possible."] },
      { type: 'oral', ja: 'これはあれと同じくらい便利です。', answers: ['This is as useful as that.', 'This is as convenient as that one.'] },
      { type: 'oral', ja: '思ったほど難しくありませんでした。', answers: ["It wasn't as difficult as I thought."] },
    ],
    myself: {
      task: 'as … as か not as … as で、自分と誰か（何か）を比べて1文言ってみましょう。',
      samples: ["I'm not as good at English as my sister.", 'My new job is as interesting as my old one.'],
      checks: ['as と as の間は形容詞・副詞の元の形にした'],
    },
  },
  {
    id: 'g35',
    title: '受け身（〜される・〜された）',
    stage: '中学校：比べる・される',
    sources: [{ doc: 中, where: '第2章第2節 2(1)エ（ｳ）j 受け身', page: '50〜51' }],
    points: [
      { text: '「〜される」は be動詞＋過去分詞。だれにされるかは by 〜 で表します（言わなくてよいときは省きます）。', en: ['English is spoken in Canada.', 'The picture was painted by Picasso.'] },
      { text: '過去分詞：多くは過去形と同じ -ed（use → used）。不規則なもの：make → made、write → written、speak → spoken、build → built、hold → held など。' },
      { text: '過去は was / were＋過去分詞、これからは will be＋過去分詞。', en: ['Disneyland was built in 1955.'] },
      { text: '否定は be動詞の後ろに not、疑問文は be動詞を主語の前に出します。' },
      { text: '「生まれる」は be born（I was born in 〜）。', en: ['I was born in 1960.'] },
    ],
    examples: [
      { tatoeba: 26297, en: 'English is spoken in Canada.' },
      { tatoeba: 264520, en: 'Automobiles are made in factories.' },
      { tatoeba: 39709, en: 'Disneyland was built in 1955.' },
      { tatoeba: 49008, en: 'The picture was painted by Picasso.' },
      { tatoeba: 57007, en: 'This book was written by Haley.' },
      { tatoeba: 252429, en: 'I was born in 1960.' },
    ],
    mistakes: [
      { kind: 'error', wrong: 'English is speak in Canada.', right: 'English is spoken in Canada.', note: '受け身は be動詞＋過去分詞。', dict: { lemma: 'speak', pos: 'verb', form: 'spoken', tags: ['participle', 'past'] } },
      { kind: 'error', wrong: 'The book was wrote by him.', right: 'The book was written by him.', note: 'write の過去分詞は written（wrote は過去形）。', dict: { lemma: 'write', pos: 'verb', form: 'written', tags: ['participle', 'past'] } },
      { kind: 'error', wrong: 'He was invite to the party.', right: 'He was invited to the party.', note: 'be動詞の後ろは過去分詞。', dict: { lemma: 'invite', pos: 'verb', form: 'invited', tags: ['participle', 'past'] } },
      { kind: 'error', wrong: "I'm interesting in music.", right: "I'm interested in music.", note: '「（人が）興味がある」は interested。interesting は「（物事が）おもしろい」。', dict: { lemma: 'interest', pos: 'verb', form: 'interested', tags: ['participle', 'past'] } },
    ],
    exercises: [
      { type: 'fill', ja: 'この車はドイツで作られました。', text: 'This car was ___ in Germany.', choices: ['made', 'make', 'making'], answers: ['made'] },
      { type: 'fill', ja: '会議は来週行われます。', text: 'The meeting will be ___ next week.', choices: ['held', 'hold', 'holding'], answers: ['held'] },
      { type: 'order', ja: 'この本は多くの人に読まれています。', tokens: ['This', 'book', 'is', 'read', 'by', 'many', 'people'], answers: ['This book is read by many people.'] },
      { type: 'order', ja: '私たちはパーティーに招待されました。', tokens: ['We', 'were', 'invited', 'to', 'the', 'party'], answers: ['We were invited to the party.'] },
      { type: 'rewrite', ja: '受け身の文にする。', from: 'Many people use this app.', answers: ['This app is used by many people.'] },
      { type: 'rewrite', ja: '受け身の文にする（this bridge を主語に）。', from: 'They built this bridge in 2010.', answers: ['This bridge was built in 2010.', 'This bridge was built by them in 2010.'] },
      { type: 'oral', ja: 'その会議は延期されました。', answers: ['The meeting was postponed.'] },
      { type: 'oral', ja: 'この製品は日本で作られています。', answers: ['This product is made in Japan.'] },
      { type: 'oral', ja: '私は大阪で生まれました。', answers: ['I was born in Osaka.'] },
    ],
    myself: {
      task: '自分の会社・学校・町について、受け身で1文言ってみましょう。',
      samples: ['My company was founded in 1990.', 'My town is known for its hot springs.'],
      checks: ['be動詞＋過去分詞 にした'],
    },
  },
]
